import { createClient } from 'npm:@supabase/supabase-js@2';
const cors={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'content-type,x-bos-session','Access-Control-Allow-Methods':'POST,OPTIONS'};
const json=(x:any,s=200)=>new Response(JSON.stringify(x),{status:s,headers:{...cors,'Content-Type':'application/json'}});
function b64u(a:Uint8Array){let s='';for(const b of a)s+=String.fromCharCode(b);return btoa(s).replace(/=/g,'').replace(/\+/g,'-').replace(/\//g,'_')}
async function hmac(msg:string,secret:string){const key=await crypto.subtle.importKey('raw',new TextEncoder().encode(secret),{name:'HMAC',hash:'SHA-256'},false,['sign']);return b64u(new Uint8Array(await crypto.subtle.sign('HMAC',key,new TextEncoder().encode(msg))))}
async function verifySession(token:string,secret:string){const p=String(token||'').split('.');if(p.length!==3||!/^[A-Za-z0-9_-]{1,128}$/.test(p[0])||!/^[0-9]+$/.test(p[1]))return null;if(Number(p[1])<Math.floor(Date.now()/1000))return null;const exp=await hmac(`${p[0]}.${p[1]}`,secret);if(exp.length!==p[2].length)return null;let m=0;for(let i=0;i<exp.length;i++)m|=exp.charCodeAt(i)^p[2].charCodeAt(i);return m===0?p[0]:null}
async function findStaff(db:any,value:any){const id=String(value||'').trim();if(!id)return null;let q=await db.from('business_staff').select('*').eq('external_id',id).eq('is_active',true).maybeSingle();if(q.error)throw q.error;if(q.data)return q.data;q=await db.from('business_staff').select('*').eq('id',id).eq('is_active',true).maybeSingle();if(q.error)throw q.error;return q.data||null}
Deno.serve(async(req)=>{if(req.method==='OPTIONS')return new Response('ok',{headers:cors});try{const body=await req.json();const action=String(body.action||'');if(!['setOrderType','requestReschedule'].includes(action))return json({ok:false,error:'UNKNOWN_ACTION'},404);const url=Deno.env.get('SUPABASE_URL')!,key=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!,secret=Deno.env.get('VK_APP_SECRET')||'';const db=createClient(url,key,{auth:{persistSession:false}});const uid=await verifySession(req.headers.get('x-bos-session')||'',secret);if(!uid)return json({ok:false,error:'Доступ не подтверждён'},401);const aq=await db.from('business_staff').select('*').eq('external_id',uid).eq('is_active',true).maybeSingle();if(aq.error)throw aq.error;if(!aq.data)return json({ok:false,error:'Сотрудник не найден'},403);
if(action==='setOrderType'){if(!['owner','manager','dispatcher'].includes(String(aq.data.role)))return json({ok:false,error:'Недостаточно прав'},403);const type=['work','measurement'].includes(String(body.order_type))?String(body.order_type):'work';const r=await db.from('orders').update({order_type:type,updated_at:new Date().toISOString()}).eq('id',String(body.id||'')).select().single();if(r.error)throw r.error;return json({ok:true,order:r.data})}
let master=aq.data;if(String(master.role)==='owner'&&body.acting_master_vk_id){master=await findStaff(db,body.acting_master_vk_id);if(!master||String(master.role)!=='master')return json({ok:false,error:'Мастер не найден'},404)}else if(String(master.role)!=='master')return json({ok:false,error:'Запрос на перенос может отправить только мастер'},403);
const orderId=String(body.id||body.order_id||'').trim(),reason=String(body.reason||'').trim();if(!orderId)return json({ok:false,error:'ORDER_ID_REQUIRED'},400);if(reason.length<3)return json({ok:false,error:'Укажите причину переноса'},400);if(reason.length>1000)return json({ok:false,error:'Причина переноса слишком длинная'},400);const q=await db.from('orders').select('id,status,master_staff_id').eq('id',orderId).single();if(q.error)throw q.error;if(String(q.data.master_staff_id||'')!==String(master.id))return json({ok:false,error:'Эта заявка назначена другому мастеру'},403);if(['Выполнена','Отменена'].includes(String(q.data.status||'')))return json({ok:false,error:'Завершённую заявку нельзя перенести'},409);const now=new Date().toISOString();const r=await db.from('orders').update({reschedule_requested:true,reschedule_reason:reason,reschedule_requested_at:now,reschedule_requested_by:master.id,updated_at:now}).eq('id',orderId).select('id,reschedule_requested,reschedule_reason,reschedule_requested_at,reschedule_requested_by').single();if(r.error)throw r.error;return json({ok:true,order:r.data})}catch(e){return json({ok:false,error:e instanceof Error?e.message:String(e)},500)}});
