const ROLE_NAMES={owner:'Владелец',manager:'Руководитель',dispatcher:'Диспетчер',master:'Мастер'};
const cfg=window.BUSINESS_OS_CONFIG;
// Capture before asynchronous bridge calls or navigation can change the URL.
// Keep the original query bytes; URLSearchParams encodes only the outer request.
const initialLaunchParams=window.location.search.slice(1);
const state={page:'home',user:null,orders:[],masters:[],sources:[],users:[],settings:{},vkUser:null};
const $=s=>document.querySelector(s);
const esc=s=>String(s??'').replace(/[&<>'\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#039;','\"':'&quot;'}[c]));
const money=n=>Number(n||0).toLocaleString('ru-RU')+' ₽';
const canEdit=()=>['owner','manager','dispatcher'].includes(state.user?.role);
function statusClass(s){return s==='Выполнена'?'ok':s==='Отменена'?'bad':s==='Новая'?'new':'info'}
function nav(show=true){document.querySelector('nav').style.display=show?'grid':'none'}
function setRoleBadge(text){$('#roleBadge').textContent=text}
function masterName(vkId){return state.masters.find(m=>String(m.vk_user_id)===String(vkId))?.full_name||'Не назначен'}
function launchParams(){return initialLaunchParams}
function api(action,payload={}){return new Promise((resolve,reject)=>{if(!cfg.GAS_WEB_APP_URL)return reject(new Error('GAS_URL_NOT_CONFIGURED'));const cb='boscb_'+Date.now()+'_'+Math.random().toString(36).slice(2);const s=document.createElement('script');const timer=setTimeout(()=>{cleanup();reject(new Error('API_TIMEOUT'))},15000);function cleanup(){clearTimeout(timer);delete window[cb];s.remove()}window[cb]=data=>{cleanup();resolve(data)};const q=new URLSearchParams({action,callback:cb,launch_params:launchParams(),full_name:[state.vkUser?.first_name,state.vkUser?.last_name].filter(Boolean).join(' '),payload:encodeURIComponent(JSON.stringify(payload))});s.src=cfg.GAS_WEB_APP_URL+'?'+q.toString();s.onerror=()=>{cleanup();reject(new Error('API_LOAD_FAILED'))};document.body.appendChild(s)})}
async function init(){nav(false);setRoleBadge('VK ID');renderLoading('Подключаем Google Sheets…');try{if(window.vkBridge){await vkBridge.send('VKWebAppInit');try{state.vkUser=await vkBridge.send('VKWebAppGetUserInfo')}catch{}}if(!cfg.GAS_WEB_APP_URL)return renderSetup();const launch=new URLSearchParams(launchParams());if(!launch.get('vk_user_id')||!launch.get('sign'))return renderVkOnly();const data=await api('bootstrap');if(!data.ok)throw new Error(data.error||'BOOTSTRAP_FAILED');Object.assign(state,{user:data.user,orders:data.orders||[],masters:data.masters||[],sources:data.sources||[],users:data.users||[],settings:data.settings||{}});setRoleBadge(ROLE_NAMES[state.user.role]||state.user.role);nav(true);show('home')}catch(e){console.error(e);renderError(e.message)}}
function renderLoading(text){$('#content').innerHTML=`<section class="hero"><div class="eyebrow">GOOGLE SHEETS</div><h2>${esc(text)}</h2><p class="muted">Вход выполняется автоматически через VK.</p></section>`}
function renderSetup(){setRoleBadge('Нужна настройка');$('#content').innerHTML=`<section class="hero"><div class="eyebrow">GOOGLE SHEETS</div><h2>Остался один шаг</h2><p class="muted">Нужно вставить URL опубликованного Google Apps Script Web App.</p></section><section class="card"><p>После публикации Apps Script передайте URL — я подключу его к приложению.</p></section>`}
function renderVkOnly(){setRoleBadge('Откройте в VK');$('#content').innerHTML=`<section class="hero"><h2>Откройте Business OS внутри VK</h2><p class="muted">Авторизация работает через подписанные параметры VK Mini Apps.</p></section>`}
function renderError(msg){setRoleBadge('Ошибка');const map={INVALID_VK_SIGNATURE:'Не прошла проверка подписи VK.',ACCESS_DENIED:'Ваш VK ID пока не добавлен в список сотрудников.',API_TIMEOUT:'Google Apps Script не ответил вовремя.',API_LOAD_FAILED:'Не удалось подключиться к Google Apps Script.'};$('#content').innerHTML=`<section class="hero"><h2>Не удалось подключиться</h2><p class="muted">${esc(map[msg]||msg)}</p></section>`}
const pages={
home(){const active=state.orders.filter(o=>['Назначена','В работе'].includes(String(o.status))).length;const revenue=state.orders.filter(o=>o.status==='Выполнена').reduce((a,o)=>a+Number(o.amount||0),0);return `<section class="hero"><div class="eyebrow">${ROLE_NAMES[state.user.role]||state.user.role}</div><h2>Добрый день 👋</h2><div class="muted">${esc(state.user.full_name)} · ${esc(state.user.city||'')}</div></section><div class="grid"><div class="card metric"><span class="muted">Заявок</span><strong>${state.orders.length}</strong></div><div class="card metric"><span class="muted">В работе</span><strong>${active}</strong></div><div class="card metric"><span class="muted">Выручка</span><strong>${money(revenue)}</strong></div><div class="card metric"><span class="muted">Мастеров</span><strong>${state.masters.length}</strong></div></div><section class="card"><div class="row"><h3>Ближайшие заявки</h3><button class="linkBtn" onclick="show('orders')">Все</button></div>${state.orders.slice(0,3).map(orderMini).join('')||'<p class="muted">Нет заявок</p>'}</section>`},
orders(){return `<div class="row"><div><h2>Заявки</h2><div class="muted">${state.orders.length} шт.</div></div>${canEdit()?'<button class="primary" onclick="openOrderForm()">+ Новая</button>':''}</div><div class="filters"><button onclick="filterOrders('all')">Все</button><button onclick="filterOrders('Новая')">Новые</button><button onclick="filterOrders('В работе')">В работе</button><button onclick="filterOrders('Выполнена')">Готово</button></div><div id="ordersList">${state.orders.map(orderCard).join('')}</div>`},
dispatch(){if(state.user.role==='master')return `<h2>Мой график</h2>${state.orders.map(o=>`<section class="card"><b>${esc(o.scheduled_date||'Без даты')} · ${esc(o.scheduled_time||'')}</b><p>${esc(o.work)} · ${esc(o.address)}</p></section>`).join('')||'<p class="muted">Нет назначенных заявок</p>'}`;return `<h2>Диспетчерская</h2>${state.orders.slice(0,10).map(o=>`<section class="card"><div class="row"><div><b>${esc(o.scheduled_date||'Без даты')} · ${esc(o.scheduled_time||'')}</b><p class="muted">${esc(o.work)} · ${esc(o.master_name||'Не назначен')}</p></div><span class="status ${statusClass(o.status)}">${esc(o.status)}</span></div></section>`).join('')}`},
team(){if(state.user.role==='master')return `<h2>Профиль</h2><section class="card"><b>${esc(state.user.full_name)}</b><p class="muted">${ROLE_NAMES[state.user.role]} · ${esc(state.user.city||'')}</p></section>`;const owner=state.user.role==='owner';return `<h2>Команда</h2>${state.users.map(u=>`<section class="card"><div class="row"><div><b>${esc(u.full_name)}</b><p class="muted">VK ${esc(u.vk_user_id)} · ${esc(u.city||'')}</p></div>${owner?`<select onchange="changeRole('${esc(u.vk_user_id)}',this.value)">${Object.entries(ROLE_NAMES).map(([v,n])=>`<option value="${v}" ${u.role===v?'selected':''}>${n}</option>`).join('')}</select>`:`<span class="status info">${ROLE_NAMES[u.role]||u.role}</span>`}</div></section>`).join('')}`}
};
function orderMini(o){return `<button class="miniOrder" onclick="openOrder('${esc(o.id)}')"><span><b>${esc(o.scheduled_time||'—')} · ${esc(o.work)}</b><small>${esc(o.master_name||masterName(o.master_vk_id))} · ${esc(o.address)}</small></span><span class="status ${statusClass(o.status)}">${esc(o.status)}</span></button>`}
function orderCard(o){return `<section class="card order" data-status="${esc(o.status)}" onclick="openOrder('${esc(o.id)}')"><div class="row"><small>${esc(o.id)} · ${esc(o.scheduled_date||'')} ${esc(o.scheduled_time||'')}</small><span class="status ${statusClass(o.status)}">${esc(o.status)}</span></div><h3>${esc(o.work)}</h3><div class="muted">${esc(o.client)} · ${esc(o.master_name||masterName(o.master_vk_id))}</div><div class="orderMeta"><span>${esc(o.address)}</span><b>${money(o.amount)}</b></div></section>`}
function show(name){state.page=name;$('#content').innerHTML=pages[name]();document.querySelectorAll('nav button').forEach(b=>b.classList.toggle('active',b.dataset.page===name))}
function filterOrders(status){document.querySelectorAll('#ordersList .order').forEach(el=>el.style.display=status==='all'||el.dataset.status===status?'block':'none')}
function openOrder(id){const o=state.orders.find(x=>String(x.id)===String(id));if(!o)return;const actions=canEdit()?`<div class="actionGrid"><button onclick="setStatus('${esc(o.id)}','Назначена')">Назначить</button><button onclick="setStatus('${esc(o.id)}','В работе')">В работу</button><button onclick="setStatus('${esc(o.id)}','Выполнена')">Выполнена</button><button class="danger" onclick="setStatus('${esc(o.id)}','Отменена')">Отменить</button></div><button class="secondary wide" onclick="openOrderForm('${esc(o.id)}')">Редактировать</button>`:`<button class="primary wide" onclick="setStatus('${esc(o.id)}','В работе')">Начать работу</button><button class="secondary wide" onclick="setStatus('${esc(o.id)}','Выполнена')">Завершить</button>`;openModal(`<div class="row"><div><small>${esc(o.id)}</small><h2>${esc(o.work)}</h2></div><span class="status ${statusClass(o.status)}">${esc(o.status)}</span></div><div class="detailGrid"><div><span>Клиент</span><b>${esc(o.client)}</b></div><div><span>Телефон</span><b>${esc(o.phone||'—')}</b></div><div><span>Адрес</span><b>${esc(o.address)}</b></div><div><span>Дата и время</span><b>${esc(o.scheduled_date||'—')} · ${esc(o.scheduled_time||'—')}</b></div><div><span>Мастер</span><b>${esc(o.master_name||masterName(o.master_vk_id))}</b></div><div><span>Сумма</span><b>${money(o.amount)}</b></div><div><span>Источник</span><b>${esc(o.source||'—')}</b></div><div><span>Город</span><b>${esc(o.city||'')}</b></div></div><section class="note"><span>Комментарий</span><p>${esc(o.comment||'—')}</p></section>${actions}`)}
function openOrderForm(id){if(!canEdit())return;const o=id?state.orders.find(x=>String(x.id)===String(id)):null;openModal(`<h2>${o?'Редактировать заявку':'Новая заявка'}</h2><form id="orderForm" class="form"><input name="client" placeholder="Клиент" required value="${esc(o?.client||'')}"><input name="phone" placeholder="Телефон" value="${esc(o?.phone||'')}"><input name="address" placeholder="Адрес" required value="${esc(o?.address||'')}"><input name="work" placeholder="Что нужно сделать" required value="${esc(o?.work||'')}"><div class="two"><input type="date" name="scheduled_date" value="${esc(o?.scheduled_date||new Date().toISOString().slice(0,10))}"><input type="time" name="scheduled_time" value="${esc(o?.scheduled_time||'12:00')}"></div><select name="master_vk_id"><option value="">Не назначен</option>${state.masters.map(m=>`<option value="${esc(m.vk_user_id)}" ${String(o?.master_vk_id||'')===String(m.vk_user_id)?'selected':''}>${esc(m.full_name)}</option>`).join('')}</select><div class="two"><input type="number" name="amount" placeholder="Сумма" value="${esc(o?.amount||'')}"><select name="source">${state.sources.map(s=>`<option ${o?.source===s.source?'selected':''}>${esc(s.source)}</option>`).join('')}</select></div><textarea name="comment" placeholder="Комментарий">${esc(o?.comment||'')}</textarea><button class="primary wide" type="submit">${o?'Сохранить':'Создать заявку'}</button><p id="formMsg" class="muted"></p></form>`);$('#orderForm').onsubmit=async e=>{e.preventDefault();const f=Object.fromEntries(new FormData(e.target));const m=state.masters.find(x=>String(x.vk_user_id)===String(f.master_vk_id));const payload={...f,master_name:m?.full_name||'',amount:Number(f.amount||0),city:state.user.city||state.settings.default_city||'Москва'};$('#formMsg').textContent='Сохраняем…';try{let data;if(o){payload.id=o.id;data=await api('updateOrder',payload)}else data=await api('createOrder',payload);if(!data.ok)throw new Error(data.error);closeModal();await refresh();show('orders')}catch(err){$('#formMsg').textContent=err.message}}}
async function setStatus(id,status){try{const data=await api('updateOrder',{id,status});if(!data.ok)throw new Error(data.error);closeModal();await refresh();show(state.page)}catch(e){alert(e.message)}}
async function changeRole(vk_user_id,role){try{const data=await api('setUserRole',{vk_user_id,role});if(!data.ok)throw new Error(data.error);await refresh();show('team')}catch(e){alert(e.message)}}
async function refresh(){const data=await api('bootstrap');if(data.ok){state.user=data.user;state.orders=data.orders||[];state.masters=data.masters||[];state.sources=data.sources||[];state.users=data.users||[];state.settings=data.settings||{}}}
function openModal(html){$('#modalRoot').innerHTML=`<div class="modalBackdrop" onclick="if(event.target===this)closeModal()"><div class="modal"><button class="closeBtn" onclick="closeModal()">×</button>${html}</div></div>`;document.body.classList.add('modalOpen')}
function closeModal(){$('#modalRoot').innerHTML='';document.body.classList.remove('modalOpen')}
document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>show(b.dataset.page));$('#profileBtn').onclick=()=>{if(!state.user)return;openModal(`<h2>Профиль</h2><section class="card"><b>${esc(state.user.full_name)}</b><p class="muted">${ROLE_NAMES[state.user.role]||state.user.role} · ${esc(state.user.city||'')}</p><p>VK ID: ${esc(state.user.vk_user_id)}</p></section>`)};init();
