const ROLE_NAMES={owner:'Владелец',manager:'Руководитель',dispatcher:'Диспетчер',master:'Мастер'};
const cfg=window.BUSINESS_OS_CONFIG;
const sb=window.supabase.createClient(cfg.SUPABASE_URL,cfg.SUPABASE_PUBLISHABLE_KEY);
const state={page:'home',session:null,profile:null,orders:[],team:[],vkUser:null};
const $=s=>document.querySelector(s);
const esc=s=>String(s??'').replace(/[&<>'\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#039;','\"':'&quot;'}[c]));
const money=n=>Number(n||0).toLocaleString('ru-RU')+' ₽';
const canEdit=()=>['owner','manager','dispatcher'].includes(state.profile?.role);
function statusClass(s){return s==='Выполнена'?'ok':s==='Отменена'?'bad':s==='Новая'?'new':'info'}
function orderNumber(o){return 'З-'+String(o.id).padStart(4,'0')}
function nav(show=true){document.querySelector('nav').style.display=show?'grid':'none'}
function setRoleBadge(text){$('#roleBadge').textContent=text}
function masterName(id){return state.team.find(p=>p.id===id)?.full_name||'Не назначен'}

async function init(){
  nav(false);setRoleBadge('VK ID');renderLoading('Входим через VK…');
  try{
    if(window.vkBridge){await vkBridge.send('VKWebAppInit');try{state.vkUser=await vkBridge.send('VKWebAppGetUserInfo')}catch{}}
    const {data:{session}}=await sb.auth.getSession();
    if(session){state.session=session;return loadApp()}
    if(!location.search.includes('vk_user_id=')||!location.search.includes('sign='))return renderVkOnly();
    const res=await fetch(cfg.SUPABASE_URL+'/functions/v1/vk-auth',{method:'POST',headers:{'Content-Type':'application/json','apikey':cfg.SUPABASE_PUBLISHABLE_KEY},body:JSON.stringify({launchParams:location.search,firstName:state.vkUser?.first_name,lastName:state.vkUser?.last_name,photo100:state.vkUser?.photo_100,photo200:state.vkUser?.photo_200})});
    const auth=await res.json();if(!res.ok)throw new Error(auth.error||'VK auth failed');
    const verified=await sb.auth.verifyOtp({token_hash:auth.token_hash,type:'magiclink'});if(verified.error)throw verified.error;
    state.session=verified.data.session;await loadApp();
  }catch(e){console.error(e);renderAuthError(e.message)}
}
function renderLoading(text){$('#content').innerHTML=`<section class="hero"><div class="eyebrow">VK ID</div><h2>${esc(text)}</h2><p class="muted">Пароль и email не нужны.</p></section>`}
function renderVkOnly(){setRoleBadge('Откройте в VK');$('#content').innerHTML=`<section class="hero"><h2>Откройте Business OS внутри VK</h2><p class="muted">Авторизация работает по защищённым параметрам запуска VK Mini Apps.</p></section>`}
function renderAuthError(msg){setRoleBadge('Ошибка входа');$('#content').innerHTML=`<section class="hero"><h2>Не удалось войти через VK</h2><p class="muted">${esc(msg)}</p></section><section class="card"><p>Проверьте, что функция <b>vk-auth</b> опубликована в Supabase и секрет VK_APP_SECRET добавлен в Edge Function Secrets.</p></section>`}

async function loadApp(){try{
  const uid=state.session.user.id;
  const {data:profile,error:pe}=await sb.from('profiles').select('*').eq('id',uid).single();if(pe)throw pe;state.profile=profile;
  const [{data:team,error:te},{data:orders,error:oe}]=await Promise.all([
    sb.from('profiles').select('id,vk_user_id,full_name,role,city,avatar_url,is_active').order('full_name'),
    sb.from('orders').select('*').order('scheduled_date',{ascending:true}).order('scheduled_time',{ascending:true})
  ]);if(te)throw te;if(oe)throw oe;state.team=team||[];state.orders=orders||[];setRoleBadge(ROLE_NAMES[profile.role]||profile.role);nav(true);show(state.page);
}catch(e){renderAuthError(e.message)}}

const pages={
 home(){const active=state.orders.filter(o=>['Назначена','В работе'].includes(o.status)).length;const revenue=state.orders.filter(o=>o.status==='Выполнена').reduce((a,o)=>a+Number(o.amount||0),0);return `<section class="hero"><div class="eyebrow">${ROLE_NAMES[state.profile.role]}</div><h2>Добрый день${state.profile.full_name?' · '+esc(state.profile.full_name):''} 👋</h2><div class="muted">Вход выполнен через VK ID · ${esc(state.profile.city)}</div></section><div class="grid"><div class="card metric"><span class="muted">Заявок</span><strong>${state.orders.length}</strong></div><div class="card metric"><span class="muted">В работе</span><strong>${active}</strong></div><div class="card metric"><span class="muted">Выручка</span><strong>${money(revenue)}</strong></div><div class="card metric"><span class="muted">Команда</span><strong>${state.team.filter(x=>x.is_active).length}</strong></div></div><section class="card"><div class="row"><h3>Ближайшие заявки</h3><button class="linkBtn" onclick="show('orders')">Все</button></div>${state.orders.slice(0,3).map(orderMini).join('')||'<p class="muted">Нет заявок</p>'}</section>`},
 orders(){return `<div class="row"><div><h2>Заявки</h2><div class="muted">${state.orders.length} шт.</div></div>${canEdit()?'<button class="primary" onclick="openOrderForm()">+ Новая</button>':''}</div><div class="filters"><button onclick="filterOrders('all')">Все</button><button onclick="filterOrders('Новая')">Новые</button><button onclick="filterOrders('В работе')">В работе</button><button onclick="filterOrders('Выполнена')">Готово</button></div><div id="ordersList">${state.orders.map(orderCard).join('')}</div>`},
 dispatch(){if(state.profile.role==='master')return `<h2>Мой график</h2>${state.orders.map(o=>`<section class="card"><b>${esc(o.scheduled_date||'Без даты')} · ${esc(o.scheduled_time?.slice(0,5)||'')}</b><p>${esc(o.work)} · ${esc(o.address)}</p></section>`).join('')||'<p class="muted">Нет назначенных заявок</p>'}`;return `<h2>Диспетчерская</h2>${state.orders.slice(0,12).map(o=>`<section class="card"><div class="row"><div><b>${esc(o.scheduled_date||'Без даты')} · ${esc(o.scheduled_time?.slice(0,5)||'')}</b><p class="muted">${esc(o.work)} · ${esc(masterName(o.master_id))}</p></div><span class="status ${statusClass(o.status)}">${esc(o.status)}</span></div></section>`).join('')}`},
 team(){if(state.profile.role==='master')return `<h2>Профиль</h2><section class="card"><b>${esc(state.profile.full_name)}</b><p class="muted">Мастер · VK ID ${esc(state.profile.vk_user_id||'')}</p></section>`;const owner=state.profile.role==='owner';return `<h2>Команда</h2><p class="muted">Сотруднику достаточно один раз открыть приложение через VK — профиль создастся автоматически.</p>${state.team.map(p=>`<section class="card"><div class="row"><div><b>${esc(p.full_name)}</b><p class="muted">VK ID ${esc(p.vk_user_id||'—')} · ${esc(p.city)}</p></div>${owner?`<select onchange="updateTeamRole('${p.id}',this.value)" ${p.id===state.profile.id?'disabled':''}>${Object.entries(ROLE_NAMES).map(([v,n])=>`<option value="${v}" ${p.role===v?'selected':''}>${n}</option>`).join('')}</select>`:`<span class="status info">${ROLE_NAMES[p.role]||p.role}</span>`}</div></section>`).join('')}`}
};
function orderMini(o){return `<button class="miniOrder" onclick="openOrder(${o.id})"><span><b>${esc(o.scheduled_time?.slice(0,5)||'—')} · ${esc(o.work)}</b><small>${esc(masterName(o.master_id))} · ${esc(o.address)}</small></span><span class="status ${statusClass(o.status)}">${esc(o.status)}</span></button>`}
function orderCard(o){return `<section class="card order" data-status="${esc(o.status)}" onclick="openOrder(${o.id})"><div class="row"><small>${orderNumber(o)} · ${esc(o.scheduled_date||'')} ${esc(o.scheduled_time?.slice(0,5)||'')}</small><span class="status ${statusClass(o.status)}">${esc(o.status)}</span></div><h3>${esc(o.work)}</h3><div class="muted">${esc(o.client)} · ${esc(masterName(o.master_id))}</div><div class="orderMeta"><span>${esc(o.address)}</span><b>${money(o.amount)}</b></div></section>`}
function show(name){state.page=name;if(!state.profile)return;$('#content').innerHTML=pages[name]();document.querySelectorAll('nav button').forEach(b=>b.classList.toggle('active',b.dataset.page===name))}
function filterOrders(status){document.querySelectorAll('#ordersList .order').forEach(el=>el.style.display=status==='all'||el.dataset.status===status?'block':'none')}
async function updateTeamRole(id,role){if(state.profile.role!=='owner')return;const {error}=await sb.from('profiles').update({role}).eq('id',id);if(error)return alert(error.message);const m=state.team.find(x=>x.id===id);if(m)m.role=role;show('team')}

function openOrder(id){const o=state.orders.find(x=>x.id===id);if(!o)return;const actions=canEdit()?`<div class="actionGrid"><button onclick="setStatus(${o.id},'Назначена')">Назначить</button><button onclick="setStatus(${o.id},'В работе')">В работу</button><button onclick="setStatus(${o.id},'Выполнена')">Выполнена</button><button class="danger" onclick="setStatus(${o.id},'Отменена')">Отменить</button></div><button class="secondary wide" onclick="openOrderForm(${o.id})">Редактировать</button>`:`<button class="primary wide" onclick="setStatus(${o.id},'В работе')">Начать работу</button><button class="secondary wide" onclick="setStatus(${o.id},'Выполнена')">Завершить</button>`;openModal(`<div class="row"><div><small>${orderNumber(o)}</small><h2>${esc(o.work)}</h2></div><span class="status ${statusClass(o.status)}">${esc(o.status)}</span></div><div class="detailGrid"><div><span>Клиент</span><b>${esc(o.client)}</b></div><div><span>Телефон</span><b>${esc(o.phone||'—')}</b></div><div><span>Адрес</span><b>${esc(o.address)}</b></div><div><span>Дата и время</span><b>${esc(o.scheduled_date||'—')} · ${esc(o.scheduled_time?.slice(0,5)||'—')}</b></div><div><span>Мастер</span><b>${esc(masterName(o.master_id))}</b></div><div><span>Сумма</span><b>${money(o.amount)}</b></div><div><span>Источник</span><b>${esc(o.source||'—')}</b></div><div><span>Город</span><b>${esc(o.city)}</b></div></div><section class="note"><span>Комментарий</span><p>${esc(o.comment||'—')}</p></section>${actions}`)}
function openOrderForm(id){if(!canEdit())return;const o=id?state.orders.find(x=>x.id===id):null;const masters=state.team.filter(p=>p.role==='master'&&p.is_active);openModal(`<h2>${o?'Редактировать заявку':'Новая заявка'}</h2><form id="orderForm" class="form"><input name="client" placeholder="Клиент" required value="${esc(o?.client||'')}"><input name="phone" placeholder="Телефон" value="${esc(o?.phone||'')}"><input name="address" placeholder="Адрес" required value="${esc(o?.address||'')}"><input name="work" placeholder="Что нужно сделать" required value="${esc(o?.work||'')}"><div class="two"><input type="date" name="scheduled_date" value="${esc(o?.scheduled_date||new Date().toISOString().slice(0,10))}"><input type="time" name="scheduled_time" value="${esc(o?.scheduled_time?.slice(0,5)||'12:00')}"></div><select name="master_id"><option value="">Не назначен</option>${masters.map(m=>`<option value="${m.id}" ${o?.master_id===m.id?'selected':''}>${esc(m.full_name)}</option>`).join('')}</select><div class="two"><input type="number" name="amount" placeholder="Сумма" value="${o?.amount||''}"><select name="source">${['VK','Телефон','Сайт','Реклама'].map(s=>`<option ${o?.source===s?'selected':''}>${s}</option>`).join('')}</select></div><textarea name="comment" placeholder="Комментарий">${esc(o?.comment||'')}</textarea><button class="primary wide" type="submit">${o?'Сохранить':'Создать заявку'}</button><p id="formMsg" class="muted"></p></form>`);$('#orderForm').onsubmit=async e=>{e.preventDefault();const f=Object.fromEntries(new FormData(e.target));const payload={client:f.client,phone:f.phone,address:f.address,work:f.work,scheduled_date:f.scheduled_date||null,scheduled_time:f.scheduled_time||null,master_id:f.master_id||null,amount:Number(f.amount||0),source:f.source,comment:f.comment,city:state.profile.city,status:f.master_id?(o?.status==='В работе'||o?.status==='Выполнена'?o.status:'Назначена'):'Новая'};$('#formMsg').textContent='Сохраняем…';let error;if(o){({error}=await sb.from('orders').update(payload).eq('id',o.id))}else{payload.created_by=state.profile.id;({error}=await sb.from('orders').insert(payload))}if(error)return $('#formMsg').textContent=error.message;closeModal();await refreshOrders();show('orders')}}
async function setStatus(id,status){let error;if(state.profile.role==='master'){({error}=await sb.rpc('master_set_order_status',{p_order_id:id,p_status:status}))}else{({error}=await sb.from('orders').update({status}).eq('id',id))}if(error)return alert(error.message);closeModal();await refreshOrders();show(state.page)}
async function refreshOrders(){const {data,error}=await sb.from('orders').select('*').order('scheduled_date',{ascending:true}).order('scheduled_time',{ascending:true});if(!error)state.orders=data||[]}
function openModal(html){$('#modalRoot').innerHTML=`<div class="modalBackdrop" onclick="if(event.target===this)closeModal()"><div class="modal"><button class="closeBtn" onclick="closeModal()">×</button>${html}</div></div>`;document.body.classList.add('modalOpen')}
function closeModal(){$('#modalRoot').innerHTML='';document.body.classList.remove('modalOpen')}
document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>show(b.dataset.page));
$('#profileBtn').onclick=()=>{if(!state.profile)return;openModal(`<h2>Профиль VK</h2><section class="card"><b>${esc(state.profile.full_name)}</b><p class="muted">${ROLE_NAMES[state.profile.role]} · VK ID ${esc(state.profile.vk_user_id||'')}</p></section><button class="secondary wide" id="reauthBtn">Обновить вход через VK</button>`);$('#reauthBtn').onclick=async()=>{await sb.auth.signOut();location.reload()}};
init();
