(()=>{
const cfg=window.BUSINESS_OS_CONFIG||{};
const API=cfg.API_URL||'https://obsropbslfwtanyspjbi.supabase.co/functions/v1/mini-app-api';
const PIN_API='https://obsropbslfwtanyspjbi.supabase.co/functions/v1/test-pin-session';
const SESSION='bos_v2_session';
const ROLE={owner:'Владелец',manager:'Руководитель',dispatcher:'Диспетчер',master:'Мастер'};
const state={page:'home',user:null,orders:[],users:[],masters:[],schedule:[]};
const $=s=>document.querySelector(s);
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const money=n=>Number(n||0).toLocaleString('ru-RU',{maximumFractionDigits:2})+' ₽';
function session(){try{return localStorage.getItem(SESSION)||''}catch(_){return ''}}
function saveSession(v){try{localStorage.setItem(SESSION,v)}catch(_){}}
function clearSession(){try{localStorage.removeItem(SESSION)}catch(_){}}
function shell(show=true){document.querySelector('header').style.display=show?'flex':'none';document.querySelector('nav').style.display=show?'flex':'none'}
function roleBadge(){const r=$('#roleBadge');if(r&&state.user)r.textContent=ROLE[state.user.role]||state.user.role||'Сотрудник';const a=$('#profileBtn');if(a&&state.user)a.textContent=String(state.user.full_name||'П').trim().split(/\s+/).map(x=>x[0]).join('').slice(0,2).toUpperCase()||'П'}
async function api(action,payload={}){const s=session();if(!s)throw Object.assign(new Error('Требуется вход'),{status:401});let r;try{r=await fetch(API,{method:'POST',headers:{'Content-Type':'application/json','X-BOS-Session':s},body:JSON.stringify({action,...payload})})}catch(_){throw new Error('Не удалось подключиться к серверу')};const d=await r.json().catch(()=>({}));if(r.status===401){clearSession();throw Object.assign(new Error('Сессия завершена'),{status:401})}if(!r.ok||d.ok===false)throw new Error(d.error||('Ошибка сервера '+r.status));return d}
async function bootstrap(){const d=await api('bootstrap');state.user=d.user;state.orders=d.orders||[];state.users=d.users||[];state.masters=d.masters||[];state.schedule=d.masterSchedule||[];roleBadge();shell(true);render(state.page)}
function login(){shell(false);$('#modalRoot').innerHTML='';$('#content').innerHTML=`<section class="hero" style="margin-top:48px"><div class="eyebrow">BUSINESS OS v2</div><h2>Тестовый вход</h2><p class="muted">Временный вход для разработки внутри VK. Google Drive и VK-авторизация сейчас отключены.</p><form id="pinForm" class="form" style="margin-top:22px"><input name="pin" inputmode="numeric" autocomplete="one-time-code" maxlength="6" placeholder="6-значный PIN" required><button class="primary wide" type="submit">Войти</button><p id="pinMsg" class="muted"></p></form></section>`;const f=$('#pinForm');f.onsubmit=async e=>{e.preventDefault();const msg=$('#pinMsg');msg.textContent='Входим…';try{const r=await fetch(PIN_API,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({pin:f.elements.pin.value})});const d=await r.json().catch(()=>({}));if(!r.ok||!d.ok)throw new Error(d.error||'Не удалось войти');saveSession(d.session_token);state.page='home';await bootstrap()}catch(err){msg.textContent=err.message}}}
function nav(){document.querySelectorAll('nav button').forEach(b=>b.classList.toggle('active',b.dataset.page===state.page))}
function render(page){state.page=page;nav();if(page==='home')home();else if(page==='orders')orders();else if(page==='dispatch')dispatch();else if(page==='team')team();else profile()}
function home(){const active=state.orders.filter(o=>o.status==='В работе').length,done=state.orders.filter(o=>o.status==='Выполнена'),rev=done.reduce((a,o)=>a+Number(o.amount||0),0);$('#content').innerHTML=`<div class="eyebrow">РАБОЧАЯ ПАНЕЛЬ</div><h2>Здравствуйте, ${esc(state.user?.full_name||'')}</h2><div class="grid"><section class="card metric"><span class="muted">Заявок</span><strong>${state.orders.length}</strong></section><section class="card metric"><span class="muted">В работе</span><strong>${active}</strong></section><section class="card metric"><span class="muted">Мастеров</span><strong>${state.masters.length}</strong></section><section class="card metric"><span class="muted">Выручка</span><strong>${money(rev)}</strong></section></div><section class="card"><h3>Business OS v2</h3><p class="muted">Сейчас работает чистое ядро на Supabase. Google Drive, отчёты и VK-авторизация временно отключены.</p></section>`}
function orders(){const can=state.user?.role==='owner'||state.user?.role==='dispatcher'||state.user?.role==='manager';$('#content').innerHTML=`<div class="row"><div><h2>Заявки</h2><div class="muted">${state.orders.length} шт.</div></div>${can?'<button id="newOrder" class="primary">+ Новая</button>':''}</div><div id="orderList">${state.orders.map(o=>`<section class="card orderCard" data-id="${esc(o.id)}"><div class="row"><b>${esc(o.client||'Клиент')}</b><span class="status info">${esc(o.status||'В работе')}</span></div><h3>${esc(o.work||'Работа')}</h3><p class="muted">${esc(o.address||'')}</p><div class="row"><span>${esc(o.master_name||'Не назначен')}</span><b>${money(o.amount)}</b></div></section>`).join('')||'<p class="muted">Заявок пока нет.</p>'}</div>`;if(can)$('#newOrder').onclick=()=>orderForm();document.querySelectorAll('.orderCard').forEach(x=>x.onclick=()=>orderDetails(x.dataset.id))}
function orderDetails(id){const o=state.orders.find(x=>String(x.id)===String(id));if(!o)return;openModal(`<h2>${esc(o.work||'Заявка')}</h2><p><b>${esc(o.client||'')}</b> · ${esc(o.phone||'')}</p><p>${esc(o.address||'')}</p><p class="muted">Мастер: ${esc(o.master_name||'Не назначен')}</p><p>Сумма: <b>${money(o.amount)}</b></p><label>Статус</label><select id="orderStatus"><option ${o.status==='В работе'?'selected':''}>В работе</option><option ${o.status==='Выполнена'?'selected':''}>Выполнена</option><option ${o.status==='Отменена'?'selected':''}>Отменена</option></select><label>Мастер</label><select id="orderMaster"><option value="">Не назначен</option>${state.masters.map(m=>`<option value="${esc(m.vk_user_id||m.id)}" ${String(o.master_vk_id||'')===String(m.vk_user_id||m.id)?'selected':''}>${esc(m.full_name)}</option>`).join('')}</select><button id="saveOrderQuick" class="primary wide">Сохранить</button><p id="quickMsg" class="muted"></p>`);$('#saveOrderQuick').onclick=async()=>{const msg=$('#quickMsg');msg.textContent='Сохраняем…';try{const d=await api('updateOrder',{id:o.id,status:$('#orderStatus').value,master_vk_id:$('#orderMaster').value});const i=state.orders.findIndex(x=>String(x.id)===String(o.id));state.orders[i]=d.order;closeModal();render('orders')}catch(e){msg.textContent=e.message}}}
function orderForm(){openModal(`<h2>Новая заявка</h2><form id="orderForm" class="form"><input name="client" placeholder="Клиент" required><input name="phone" placeholder="Телефон"><input name="address" placeholder="Адрес" required><input name="work" placeholder="Работа" required><div class="two"><input name="scheduled_date" type="date"><input name="scheduled_time" type="time"></div><select name="master_vk_id"><option value="">Мастер не назначен</option>${state.masters.map(m=>`<option value="${esc(m.vk_user_id||m.id)}">${esc(m.full_name)}</option>`).join('')}</select><input name="amount" type="number" min="0" step="0.01" placeholder="Сумма"><textarea name="comment" placeholder="Комментарий"></textarea><button class="primary wide" type="submit">Создать заявку</button><p id="orderMsg" class="muted"></p></form>`);$('#orderForm').onsubmit=async e=>{e.preventDefault();const f=e.currentTarget,msg=$('#orderMsg'),p=Object.fromEntries(new FormData(f));p.amount=Number(p.amount||0);msg.textContent='Создаём…';try{const d=await api('createOrder',p);state.orders.unshift(d.order);closeModal();render('orders')}catch(err){msg.textContent=err.message}}}
function dispatch(){const dated=state.orders.filter(o=>o.scheduled_date).sort((a,b)=>String(a.scheduled_date+a.scheduled_time).localeCompare(String(b.scheduled_date+b.scheduled_time)));$('#content').innerHTML=`<h2>График</h2><p class="muted">Пока показываем заявки, назначенные по дате и времени. Редактор смен мастеров будет следующим этапом.</p>${dated.map(o=>`<section class="card"><div class="row"><b>${esc(o.scheduled_date||'')} ${esc(o.scheduled_time||'')}</b><span>${esc(o.status||'')}</span></div><p>${esc(o.work||'')} · ${esc(o.master_name||'Не назначен')}</p></section>`).join('')||'<p class="muted">Запланированных заявок пока нет.</p>'}`}
function team(){const owner=state.user?.role==='owner';$('#content').innerHTML=`<div class="row"><div><h2>Команда</h2><div class="muted">${state.users.length} сотрудников</div></div>${owner?'<button id="newEmployee" class="primary">+ Сотрудник</button>':''}</div>${state.users.map(u=>`<section class="card"><div class="row"><div><b>${esc(u.full_name)}</b><p class="muted">${esc(u.phone||'')} · ${esc(u.city||'')}</p></div><span class="status info">${esc(ROLE[u.role]||u.role)}</span></div><p class="muted">${esc(u.specialization||'')}</p></section>`).join('')||'<p class="muted">Сотрудников пока нет.</p>'}`;if(owner)$('#newEmployee').onclick=employeeForm}
function employeeForm(){openModal(`<h2>Новый сотрудник</h2><form id="employeeForm" class="form"><input name="full_name" placeholder="Имя" required><input name="phone" type="tel" placeholder="Телефон" required><input name="city" placeholder="Город" value="Москва"><select name="role"><option value="master">Мастер</option><option value="dispatcher">Диспетчер</option><option value="manager">Руководитель</option></select><input name="specialization" placeholder="Специализация"><div class="two"><input name="work_start" type="time" value="09:00"><input name="work_end" type="time" value="18:00"></div><button class="primary wide" type="submit">Добавить</button><p id="employeeMsg" class="muted"></p></form>`);$('#employeeForm').onsubmit=async e=>{e.preventDefault();const f=e.currentTarget,msg=$('#employeeMsg'),p=Object.fromEntries(new FormData(f));msg.textContent='Добавляем…';try{const d=await api('addEmployee',p);state.users.push(d.user);if(d.master)state.masters.push(d.master);closeModal();render('team')}catch(err){msg.textContent=err.message}}}
function profile(){$('#content').innerHTML=`<h2>Профиль</h2><section class="card"><h3>${esc(state.user?.full_name||'')}</h3><p class="muted">${esc(ROLE[state.user?.role]||state.user?.role||'')}</p><p>${esc(state.user?.phone||'')}</p><button id="logout" class="wide">Выйти</button></section>`;$('#logout').onclick=()=>{clearSession();state.user=null;login()}}
function openModal(html){$('#modalRoot').innerHTML=`<div class="modalBackdrop"><div class="modal"><button id="closeModal" class="modalClose">×</button>${html}</div></div>`;$('#closeModal').onclick=closeModal}
function closeModal(){$('#modalRoot').innerHTML=''}
document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>render(b.dataset.page));
document.querySelector('#profileBtn').onclick=()=>render('profile');
(async()=>{if(!session())return login();try{await bootstrap()}catch(e){if(e.status===401)return login();shell(false);$('#content').innerHTML=`<section class="hero"><h2>Ошибка запуска</h2><p class="muted">${esc(e.message)}</p><button id="retry" class="primary">Повторить</button></section>`;$('#retry').onclick=()=>location.reload()}})();
})();