const cfg=window.BUSINESS_OS_CONFIG||{};
const ROLE_NAMES={owner:'Владелец',manager:'Руководитель',dispatcher:'Диспетчер',master:'Мастер'};
const state={page:'home',user:{full_name:'Илья',role:'owner',city:'Москва'},orders:[],masters:[],users:[],sources:[],settings:{},busy:false};
const $=s=>document.querySelector(s);
const esc=s=>String(s??'').replace(/[&<>'\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#039;','\"':'&quot;'}[c]));
const money=n=>Number(n||0).toLocaleString('ru-RU')+' ₽';
function api(action,payload={}){return new Promise((resolve,reject)=>{if(!cfg.GAS_WEB_APP_URL)return reject(new Error('Не настроен Google Apps Script'));const cb='bos_'+Date.now()+'_'+Math.random().toString(36).slice(2);const s=document.createElement('script');const timer=setTimeout(()=>{cleanup();reject(new Error('Сервер не ответил. Повторите.'))},30000);function cleanup(){clearTimeout(timer);delete window[cb];s.remove()}window[cb]=d=>{cleanup();resolve(d)};const q=new URLSearchParams({action,callback:cb,payload:JSON.stringify(payload)});s.src=cfg.GAS_WEB_APP_URL+'?'+q.toString();s.onerror=()=>{cleanup();reject(new Error('Не удалось подключиться к Google Apps Script'))};document.body.appendChild(s)})}
async function init(){try{$('#roleBadge').textContent='Владелец';$('#content').innerHTML='<section class="hero"><h2>Загружаем данные…</h2><p class="muted">Без авторизации</p></section>';const d=await api('bootstrap');if(!d.ok)throw new Error(d.error);Object.assign(state,{user:d.user||state.user,orders:d.orders||[],masters:d.masters||[],users:d.users||[],sources:d.sources||[],settings:d.settings||{}});show(state.page||'home')}catch(e){$('#content').innerHTML=`<section class="hero"><h2>Не удалось загрузить данные</h2><p class="muted">${esc(e.message)}</p><button class="primary" onclick="init()">Повторить</button></section>`}}
const pages={
home(){const rev=state.orders.filter(o=>o.status==='Выполнена').reduce((a,o)=>a+Number(o.amount||0),0);return `<section class="hero"><div class="eyebrow">ВЛАДЕЛЕЦ · БЕЗ ВХОДА</div><h2>Business OS</h2><p class="muted">Google Sheets подключены напрямую через Apps Script.</p></section><div class="grid"><div class="card metric"><span class="muted">Заявок</span><strong>${state.orders.length}</strong></div><div class="card metric"><span class="muted">Мастеров</span><strong>${state.masters.length}</strong></div><div class="card metric"><span class="muted">В работе</span><strong>${state.orders.filter(o=>['Назначена','В работе'].includes(o.status)).length}</strong></div><div class="card metric"><span class="muted">Выручка</span><strong>${money(rev)}</strong></div></div>`},
orders(){return `<div class="row"><div><h2>Заявки</h2><div class="muted">${state.orders.length} шт.</div></div><button class="primary" onclick="openOrderForm()">+ Новая</button></div>${state.orders.map(o=>`<section class="card" onclick="openOrder('${esc(o.id)}')"><div class="row"><b>${esc(o.id)}</b><span class="status info">${esc(o.status)}</span></div><h3>${esc(o.work)}</h3><p class="muted">${esc(o.client)} · ${esc(o.address)}</p><div class="row"><span>${esc(o.master_name||'Не назначен')}</span><b>${money(o.amount)}</b></div></section>`).join('')||'<p class="muted">Заявок пока нет.</p>'}`},
dispatch(){return `<h2>График</h2>${state.orders.filter(o=>o.scheduled_date).map(o=>`<section class="card"><b>${esc(o.scheduled_date)} · ${esc(o.scheduled_time||'')}</b><p>${esc(o.work)} · ${esc(o.master_name||'Не назначен')}</p></section>`).join('')||'<p class="muted">Нет запланированных заявок.</p>'}`},
team(){return `<div class="row"><div><h2>Команда</h2><div class="muted">${state.users.length} сотрудников · ${state.masters.length} мастеров</div></div><button class="primary" onclick="openEmployeeForm()">+ Сотрудник</button></div>${state.users.map(u=>`<section class="card"><div class="row"><div><b>${esc(u.full_name)}</b><p class="muted">${esc(u.city||'')} · ${esc(u.phone||'')}</p></div><span class="status info">${esc(ROLE_NAMES[u.role]||u.role)}</span></div></section>`).join('')||'<p class="muted">Сотрудников пока нет.</p>'}`}
};
function show(name){state.page=name;$('#content').innerHTML=pages[name]();document.querySelectorAll('nav button').forEach(b=>b.classList.toggle('active',b.dataset.page===name))}
function openModal(html){$('#modalRoot').innerHTML=`<div class="modalBackdrop" onclick="if(event.target===this)closeModal()"><div class="modal"><button class="modalClose" onclick="closeModal()">×</button>${html}</div></div>`}function closeModal(){$('#modalRoot').innerHTML=''}
function setBusy(form,busy){state.busy=busy;form.querySelectorAll('button,input,select,textarea').forEach(el=>el.disabled=busy)}
function openOrder(id){const o=state.orders.find(x=>String(x.id)===String(id));if(!o)return;openModal(`<h2>${esc(o.id)}</h2><p><b>${esc(o.work)}</b></p><p>${esc(o.client)} · ${esc(o.phone||'')}</p><p>${esc(o.address)}</p><p>Мастер: ${esc(o.master_name||'Не назначен')}</p><p>Сумма: ${money(o.amount)}</p><button class="secondary wide" onclick="openOrderForm('${esc(o.id)}')">Редактировать</button>`)}
function openOrderForm(id){const o=id?state.orders.find(x=>String(x.id)===String(id)):null;openModal(`<h2>${o?'Редактировать':'Новая заявка'}</h2><form id="orderForm" class="form"><input name="client" placeholder="Клиент" required value="${esc(o?.client||'')}"><input name="phone" placeholder="Телефон" value="${esc(o?.phone||'')}"><input name="address" placeholder="Адрес" required value="${esc(o?.address||'')}"><input name="work" placeholder="Работа" required value="${esc(o?.work||'')}"><div class="two"><input type="date" name="scheduled_date" value="${esc(o?.scheduled_date||'')}"><input type="time" name="scheduled_time" value="${esc(o?.scheduled_time||'')}"></div><select name="master_vk_id"><option value="">Не назначен</option>${state.masters.map(m=>`<option value="${esc(m.vk_user_id)}" ${String(o?.master_vk_id||'')===String(m.vk_user_id)?'selected':''}>${esc(m.full_name)}</option>`).join('')}</select><input type="number" name="amount" min="0" step="0.01" placeholder="Сумма" value="${esc(o?.amount||'')}"><select name="source">${(state.sources.length?state.sources:[{source:'VK'}]).map(s=>`<option ${o?.source===s.source?'selected':''}>${esc(s.source)}</option>`).join('')}</select><textarea name="comment" placeholder="Комментарий">${esc(o?.comment||'')}</textarea><button class="primary wide" type="submit">Сохранить</button><p id="formMsg" class="muted"></p></form>`);const form=$('#orderForm');form.onsubmit=async e=>{e.preventDefault();if(state.busy)return;const f=Object.fromEntries(new FormData(form));const m=state.masters.find(x=>String(x.vk_user_id)===String(f.master_vk_id));const p={...f,master_name:m?.full_name||'',amount:Number(f.amount||0),city:'Москва'};if(o)p.id=o.id;const msg=$('#formMsg');msg.textContent='Сохраняем…';setBusy(form,true);try{const d=await api(o?'updateOrder':'createOrder',p);if(!d.ok)throw new Error(d.error);if(o){const i=state.orders.findIndex(x=>String(x.id)===String(o.id));if(i>=0)state.orders[i]=d.order}else state.orders.unshift(d.order);closeModal();show('orders')}catch(err){msg.textContent=err.message;setBusy(form,false)}}}
function openEmployeeForm(){openModal(`<h2>Новый сотрудник</h2><form id="empForm" class="form"><input name="full_name" placeholder="Имя" required><input name="phone" placeholder="Телефон"><input name="city" placeholder="Город" value="Москва"><select name="role"><option value="master">Мастер</option><option value="dispatcher">Диспетчер</option><option value="manager">Руководитель</option><option value="owner">Владелец</option></select><input name="specialization" placeholder="Специализация"><div class="two"><input type="time" name="work_start" value="09:00"><input type="time" name="work_end" value="18:00"></div><button class="primary wide" type="submit">Добавить</button><p id="empMsg" class="muted"></p></form>`);const form=$('#empForm');form.onsubmit=async e=>{e.preventDefault();if(state.busy)return;const p=Object.fromEntries(new FormData(form));const msg=$('#empMsg');msg.textContent='Добавляем…';setBusy(form,true);try{const d=await api('addEmployee',p);if(!d.ok)throw new Error(d.error);state.users.push(d.user);if(d.user.role==='master')state.masters.push({vk_user_id:d.user.vk_user_id,full_name:d.user.full_name,phone:d.user.phone,city:d.user.city,specialization:p.specialization||'',is_active:true,work_start:p.work_start||'09:00',work_end:p.work_end||'18:00'});closeModal();show('team')}catch(err){msg.textContent=err.message;setBusy(form,false)}}}
document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>show(b.dataset.page));init();