const ROLE_NAMES={owner:'Владелец',manager:'Руководитель',dispatcher:'Диспетчер',master:'Мастер'};
const DEFAULT_ORDERS=[
{id:'З-1048',client:'Анна',phone:'+7 999 123-45-67',address:'ул. Центральная, 18',work:'Ремонт стиральной машины',master:'Алексей',status:'В работе',sum:8500,date:'2026-09-08',time:'14:30',source:'VK',comment:'Не сливает воду',city:'Москва'},
{id:'З-1049',client:'Михаил',phone:'+7 999 765-43-21',address:'пр-т Мира, 41',work:'Диагностика холодильника',master:'Не назначен',status:'Новая',sum:0,date:'2026-09-08',time:'16:00',source:'Телефон',comment:'Слабо морозит',city:'Москва'},
{id:'З-1050',client:'Ольга',phone:'+7 916 100-20-30',address:'ул. Лесная, 7',work:'Установка посудомоечной машины',master:'Сергей',status:'Назначена',sum:6900,date:'2026-09-09',time:'11:00',source:'Сайт',comment:'Нужна установка и проверка подключения',city:'Москва'}
];
const state={role:localStorage.getItem('bos_role')||'owner',page:'home',orders:JSON.parse(localStorage.getItem('bos_orders')||'null')||DEFAULT_ORDERS};
const $=s=>document.querySelector(s);const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#039;','"':'&quot;'}[c]));
function money(n){return Number(n||0).toLocaleString('ru-RU')+' ₽'}function save(){localStorage.setItem('bos_orders',JSON.stringify(state.orders));localStorage.setItem('bos_role',state.role)}
function canEdit(){return state.role!=='master'}function visibleOrders(){return state.role==='master'?state.orders.filter(o=>o.master==='Алексей'):state.orders}
function statusClass(s){return s==='Выполнена'?'ok':s==='Отменена'?'bad':s==='Новая'?'new':'info'}
const pages={
home(){const list=visibleOrders();const active=list.filter(o=>['Назначена','В работе'].includes(o.status)).length;const revenue=list.filter(o=>o.status==='Выполнена').reduce((a,o)=>a+Number(o.sum||0),0);return `<section class="hero"><div class="eyebrow">${ROLE_NAMES[state.role]}</div><h2>Добрый день 👋</h2><div class="muted">Управление сервисной компанией</div></section><div class="grid"><div class="card metric"><span class="muted">Заявок</span><strong>${list.length}</strong></div><div class="card metric"><span class="muted">В работе</span><strong>${active}</strong></div><div class="card metric"><span class="muted">Выручка</span><strong>${money(revenue)}</strong></div><div class="card metric"><span class="muted">Роль</span><strong class="roleMetric">${ROLE_NAMES[state.role]}</strong></div></div><section class="card"><div class="row"><h3>Ближайшие заявки</h3><button class="linkBtn" onclick="show('orders')">Все</button></div>${list.slice(0,3).map(orderMini).join('')||'<p class="muted">Нет заявок</p>'}</section>`},
orders(){const list=visibleOrders();return `<div class="row"><div><h2>Заявки</h2><div class="muted">${ROLE_NAMES[state.role]} · ${list.length} шт.</div></div>${canEdit()?'<button class="primary" onclick="openOrderForm()">+ Новая</button>':''}</div><div class="filters"><button onclick="filterOrders('all')">Все</button><button onclick="filterOrders('Новая')">Новые</button><button onclick="filterOrders('В работе')">В работе</button><button onclick="filterOrders('Выполнена')">Готово</button></div><div id="ordersList">${list.map(orderCard).join('')}</div>`},
dispatch(){const disabled=state.role==='master';return `<h2>Диспетчерская</h2>${disabled?'<section class="card"><h3>Ваш график</h3><p>12:00 · З-1048 · Центральная, 18</p><p>17:00 · свободное окно</p></section>':'<section class="card"><h3>Сегодня</h3><p>09:00 · Сергей — выполнено</p><p>12:00 · Алексей — в работе</p><p>15:30 · Сергей — назначено</p></section><section class="card"><h3>Свободные мастера</h3><p>Иван · свободен с 14:00</p><p>Дмитрий · свободен с 16:30</p></section>'}`},
team(){if(state.role==='master')return `<h2>Профиль</h2><section class="card"><h3>Алексей</h3><p class="muted">Мастер · активен</p><p>Сегодня заявок: ${visibleOrders().length}</p></section>`;return `<h2>Команда</h2>${[['Алексей','Мастер'],['Сергей','Мастер'],['Иван','Мастер'],['Дмитрий','Мастер'],['Мария','Диспетчер']].map(([n,r])=>`<section class="card"><div class="row"><div><b>${n}</b><p class="muted">${r}</p></div><span class="status ok">Активен</span></div></section>`).join('')}`}
};
function orderMini(o){return `<button class="miniOrder" onclick="openOrder('${o.id}')"><span><b>${esc(o.time)} · ${esc(o.work)}</b><small>${esc(o.master)} · ${esc(o.address)}</small></span><span class="status ${statusClass(o.status)}">${esc(o.status)}</span></button>`}
function orderCard(o){return `<section class="card order" data-status="${esc(o.status)}" onclick="openOrder('${o.id}')"><div class="row"><small>${esc(o.id)} · ${esc(o.date)} ${esc(o.time)}</small><span class="status ${statusClass(o.status)}">${esc(o.status)}</span></div><h3>${esc(o.work)}</h3><div class="muted">${esc(o.client)} · ${esc(o.master)}</div><div class="orderMeta"><span>${esc(o.address)}</span><b>${money(o.sum)}</b></div></section>`}
function show(name){state.page=name;$('#content').innerHTML=pages[name]();document.querySelectorAll('nav button').forEach(b=>b.classList.toggle('active',b.dataset.page===name))}
function filterOrders(status){document.querySelectorAll('#ordersList .order').forEach(el=>el.style.display=status==='all'||el.dataset.status===status?'block':'none')}
function openOrder(id){const o=state.orders.find(x=>x.id===id);if(!o)return;const actions=canEdit()?`<div class="actionGrid"><button onclick="setStatus('${o.id}','Назначена')">Назначить</button><button onclick="setStatus('${o.id}','В работе')">В работу</button><button onclick="setStatus('${o.id}','Выполнена')">Выполнена</button><button class="danger" onclick="setStatus('${o.id}','Отменена')">Отменить</button></div><button class="secondary wide" onclick="openOrderForm('${o.id}')">Редактировать</button>`:`<button class="primary wide" onclick="setStatus('${o.id}','В работе')">Начать работу</button><button class="secondary wide" onclick="setStatus('${o.id}','Выполнена')">Завершить</button>`;openModal(`<div class="row"><div><small>${esc(o.id)}</small><h2>${esc(o.work)}</h2></div><span class="status ${statusClass(o.status)}">${esc(o.status)}</span></div><div class="detailGrid"><div><span>Клиент</span><b>${esc(o.client)}</b></div><div><span>Телефон</span><b>${esc(o.phone)}</b></div><div><span>Адрес</span><b>${esc(o.address)}</b></div><div><span>Дата и время</span><b>${esc(o.date)} · ${esc(o.time)}</b></div><div><span>Мастер</span><b>${esc(o.master)}</b></div><div><span>Сумма</span><b>${money(o.sum)}</b></div><div><span>Источник</span><b>${esc(o.source)}</b></div><div><span>Город</span><b>${esc(o.city)}</b></div></div><section class="note"><span>Комментарий</span><p>${esc(o.comment||'—')}</p></section>${actions}`)}
function openOrderForm(id){if(!canEdit())return;const o=id?state.orders.find(x=>x.id===id):null;openModal(`<h2>${o?'Редактировать заявку':'Новая заявка'}</h2><form id="orderForm" class="form"><input name="client" placeholder="Клиент" required value="${esc(o?.client||'')}"><input name="phone" placeholder="Телефон" value="${esc(o?.phone||'')}"><input name="address" placeholder="Адрес" required value="${esc(o?.address||'')}"><input name="work" placeholder="Что нужно сделать" required value="${esc(o?.work||'')}"><div class="two"><input type="date" name="date" required value="${esc(o?.date||new Date().toISOString().slice(0,10))}"><input type="time" name="time" value="${esc(o?.time||'12:00')}"></div><select name="master"><option>Не назначен</option>${['Алексей','Сергей','Иван','Дмитрий'].map(m=>`<option ${o?.master===m?'selected':''}>${m}</option>`).join('')}</select><div class="two"><input type="number" name="sum" placeholder="Сумма" value="${o?.sum||''}"><select name="source">${['VK','Телефон','Сайт','Реклама'].map(s=>`<option ${o?.source===s?'selected':''}>${s}</option>`).join('')}</select></div><textarea name="comment" placeholder="Комментарий">${esc(o?.comment||'')}</textarea><button class="primary wide" type="submit">${o?'Сохранить':'Создать заявку'}</button></form>`);$('#orderForm').onsubmit=e=>{e.preventDefault();const f=Object.fromEntries(new FormData(e.target));if(o){Object.assign(o,f,{sum:Number(f.sum||0)})}else{const n=Math.max(...state.orders.map(x=>Number(x.id.replace(/\D/g,''))),1050)+1;state.orders.unshift({id:'З-'+n,status:f.master==='Не назначен'?'Новая':'Назначена',city:'Москва',...f,sum:Number(f.sum||0)})}save();closeModal();show('orders')}}
function setStatus(id,status){const o=state.orders.find(x=>x.id===id);if(!o)return;o.status=status;save();closeModal();show(state.page)}
function openModal(html){$('#modalRoot').innerHTML=`<div class="modalBackdrop" onclick="if(event.target===this)closeModal()"><div class="modal"><button class="closeBtn" onclick="closeModal()">×</button>${html}</div></div>`;document.body.classList.add('modalOpen')}
function closeModal(){$('#modalRoot').innerHTML='';document.body.classList.remove('modalOpen')}
document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>show(b.dataset.page));$('#roleSelect').value=state.role;$('#roleSelect').onchange=e=>{state.role=e.target.value;save();show('home')};$('#profileBtn').onclick=()=>openModal(`<h2>Профиль</h2><section class="card"><b>Business OS</b><p class="muted">Текущая роль: ${ROLE_NAMES[state.role]}</p><p>VK Mini App ID: 54758847</p></section>`);if(window.vkBridge){vkBridge.send('VKWebAppInit').catch(()=>{});}show('home');