(()=>{
'use strict';
const OWNER=new Set(['owner','manager']);
const icon=n=>({home:'<svg viewBox="0 0 24 24"><rect x="4" y="4" width="6" height="6" rx="1"/><rect x="14" y="4" width="6" height="6" rx="1"/><rect x="4" y="14" width="6" height="6" rx="1"/><rect x="14" y="14" width="6" height="6" rx="1"/></svg>',orders:'<svg viewBox="0 0 24 24"><rect x="5" y="4" width="14" height="17" rx="2"/><path d="M9 4V2h6v2M8 9h8M8 13h8M8 17h5"/></svg>',dispatch:'<svg viewBox="0 0 24 24"><rect x="3" y="5" width="18" height="16" rx="2"/><path d="M7 3v4M17 3v4M3 9h18M8 13h.01M12 13h.01M16 13h.01M8 17h.01M12 17h.01"/></svg>',team:'<svg viewBox="0 0 24 24"><path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2M9 11a4 4 0 1 0 0-8 4 4 0 0 0 0 8ZM22 21v-2a4 4 0 0 0-3-3.87M16 3.13a4 4 0 0 1 0 7.75"/></svg>',profile:'<svg viewBox="0 0 24 24"><circle cx="12" cy="8" r="4"/><path d="M4 21a8 8 0 0 1 16 0"/></svg>'}[n]||'');
const A={from:'',to:'',city:'',master:'',dispatcher:'',status:'',q:'',source:''};
function ownerMode(){return OWNER.has(String(state.user?.role||'owner'))&&!(typeof isMasterPreview==='function'&&isMasterPreview())&&!(typeof isDispatcherPreview==='function'&&isDispatcherPreview())}
function roleLabel(){return 'Руководитель'}
function head(t){return `<section class="astraPageHead"><div class="astraPageHeadRow"><div><div class="astraEyebrow">BUSINESS OS / ${roleLabel()}</div><h1>${esc(t)}</h1></div><button class="astraCreate" onclick="openOrderForm()">＋ Заявка</button></div></section>`}
const ymdLocal=d=>{const x=new Date(d.getTime()-d.getTimezoneOffset()*60000);return x.toISOString().slice(0,10)};
function setRange(kind){const e=new Date(),s=new Date(e);if(kind==='today'){}else if(kind==='week')s.setDate(e.getDate()-6);else s.setDate(1);A.from=ymdLocal(s);A.to=ymdLocal(e);renderCurrent()}
function renderCurrent(){show(state.page||'home')}
window.astraSetRange=setRange;window.astraFilter=(k,v)=>{A[k]=v;renderCurrent()};
function unique(key){return [...new Set(state.orders.map(o=>String(o[key]||'').trim()).filter(Boolean))].sort()}
function filters(){const masters=[...new Map((state.masters||[]).map(m=>[String(m.vk_user_id||m.external_id||m.id),m])).entries()];const disp=unique('dispatcher_name');return `<section class="astraFilters"><div class="astraPeriods"><button onclick="astraSetRange('today')">Сегодня</button><button onclick="astraSetRange('week')">Неделя</button><button onclick="astraSetRange('month')">Месяц</button></div><div class="astraDateRow"><label>С <input type="date" value="${esc(A.from)}" onchange="astraFilter('from',this.value)"></label><label>По <input type="date" value="${esc(A.to)}" onchange="astraFilter('to',this.value)"></label></div><div class="astraFilterGrid"><select onchange="astraFilter('city',this.value)"><option value="">Все города</option>${unique('city').map(v=>`<option ${A.city===v?'selected':''}>${esc(v)}</option>`).join('')}</select><select onchange="astraFilter('master',this.value)"><option value="">Все мастера</option>${masters.map(([id,m])=>`<option value="${esc(id)}" ${A.master===id?'selected':''}>${esc(m.full_name||m.name||id)}</option>`).join('')}</select><select onchange="astraFilter('dispatcher',this.value)"><option value="">Все диспетчеры</option>${disp.map(v=>`<option ${A.dispatcher===v?'selected':''}>${esc(v)}</option>`).join('')}</select><select onchange="astraFilter('status',this.value)"><option value="">Все статусы</option>${['В работе','Выполнена','Рекламация','Отменена'].map(v=>`<option ${A.status===v?'selected':''}>${v}</option>`).join('')}</select></div><input class="astraSearch" value="${esc(A.q)}" placeholder="Номер, клиент, телефон, адрес, мастер" onchange="astraFilter('q',this.value)"><input class="astraSearch" value="${esc(A.source)}" placeholder="Источник" onchange="astraFilter('source',this.value)"></section>`}
function filtered(){const q=A.q.toLowerCase();return state.orders.filter(o=>{const d=String(o.scheduled_date||o.created_at||'').slice(0,10),mid=String(o.master_vk_id||o.master_staff_id||'');const hay=[o.id,o.client,o.phone,o.address,o.work,o.master_name].join(' ').toLowerCase();return(!A.from||d>=A.from)&&(!A.to||d<=A.to)&&(!A.city||String(o.city||'')===A.city)&&(!A.master||mid===A.master)&&(!A.dispatcher||String(o.dispatcher_name||'')===A.dispatcher)&&(!A.status||String(o.status||'')===A.status)&&(!q||hay.includes(q))&&(!A.source||String(o.source||'').toLowerCase().includes(A.source.toLowerCase()))})}
function orderCard(o){const status=String(o.status||'В работе');return `<section class="astraOrderCard" onclick="openOrder('${esc(o.id)}')"><div class="astraOrderTop"><span class="astraOrderNo">№ ${esc(o.id)}</span><span class="astraOrderStatus ${status==='Выполнена'?'done':status==='Рекламация'?'claim':status==='Отменена'?'cancel':''}">${esc(status)}</span></div><div class="astraOrderTitle">${esc(o.work||'Заявка')}</div><div class="astraOrderMuted">${esc(o.client||'Клиент')}</div><div class="astraOrderMuted">${esc(o.address||'')}</div><div class="astraOrderBottom"><span>${esc(String(o.scheduled_date||'').slice(0,10))}${o.scheduled_time?' · '+esc(o.scheduled_time):''}</span><b>${money(o.amount)}</b></div></section>`}
function chart(list){const start=A.from?new Date(A.from+'T00:00:00'):weekStart(),days=['Пн','Вт','Ср','Чт','Пт','Сб','Вс'];const totalMasters=Math.max(A.master?1:(state.masters||[]).length,1);const rows=days.map((label,i)=>{const d=new Date(start);d.setDate(start.getDate()+i);const date=ymdLocal(d);const dayOrders=list.filter(o=>String(o.scheduled_date||'').slice(0,10)===date&&o.status!=='Отменена');const busy=new Set(dayOrders.map(o=>String(o.master_vk_id||o.master_staff_id||'')).filter(Boolean)).size;const pct=Math.min(100,Math.round(busy/totalMasters*100));return{label,day:d.getDate(),pct,busy}});return `<section class="card loadCard astraLoadCard"><div class="row"><div><div class="eyebrow">ПЛАН РАБОТЫ</div><h2>Загруженность мастеров</h2></div><span class="softChip">${totalMasters} маст.</span></div><div class="loadLegend"><span><i class="dot busyDot"></i>Занят</span><span><i class="dot freeDot"></i>Свободен</span></div><div class="loadBars">${rows.map(x=>`<div class="loadDay"><div class="bar"><span class="barFree" style="height:${100-x.pct}%"></span><span class="barBusy" style="height:${x.pct}%"></span></div><b>${x.label}</b><small>${x.day}</small><strong>${x.pct}%</strong></div>`).join('')}</div></section>`}
function metrics(list){const done=list.filter(o=>o.status==='Выполнена'),rev=done.reduce((a,o)=>a+Number(o.amount||0),0),active=list.filter(o=>o.status==='В работе').length,claims=list.filter(o=>o.status==='Рекламация').length;return `<div class="dashMetrics"><section class="card dashMetric astraMetricCard"><span class="muted">Заявок</span><strong>${list.length}</strong></section><section class="card dashMetric astraMetricCard"><span class="muted">Мастеров</span><strong>${A.master?1:(state.masters||[]).length}</strong></section><section class="card dashMetric astraMetricCard"><span class="muted">В работе</span><strong>${active}</strong></section><section class="card dashMetric astraMetricCard"><span class="muted">Выручка</span><strong>${money(rev)}</strong></section><section class="card dashMetric astraMetricCard"><span class="muted">Рекламации</span><strong>${claims}</strong></section></div>`}
function homePage(){const list=filtered();return `${head('Главная')}<div class="astraBody">${filters()}${chart(list)}${metrics(list)}</div>`}
function ordersPage(){const list=filtered();return `${head('Заявки')}<div class="astraBody">${filters()}${list.map(orderCard).join('')||'<p class="muted">По выбранным фильтрам заявок нет.</p>'}</div>`}
function schedulePage(){const list=filtered().filter(o=>o.scheduled_date).sort((a,b)=>String(a.scheduled_date||'').localeCompare(String(b.scheduled_date||''))||String(a.scheduled_time||'').localeCompare(String(b.scheduled_time||'')));return `${head('График')}<div class="astraBody">${filters()}${chart(list)}<div class="astraScheduleList"><h2>Запланированные заявки</h2>${list.map(orderCard).join('')||'<p class="muted">Нет заявок на выбранный период.</p>'}</div></div>`}
function teamPage(){return `${head('Команда')}<div class="astraBody"><div class="astraTeamTop"><h2>Команда</h2><button class="astraLightBtn" onclick="openEmployeeForm()">Добавить сотрудника</button></div>${(state.users||[]).map(u=>`<section class="astraTeamCard"><div class="astraTeamAvatar">${esc(String(u.full_name||'?').slice(0,1).toUpperCase())}</div><div class="astraTeamName">${esc(u.full_name||'Сотрудник')}</div><div class="astraTeamMeta">${esc(ROLE_NAMES[u.role]||u.role||'')} · ${esc(u.city||'Санкт-Петербург')}</div><div class="astraTeamState">${u.active===false?'Неактивен':'Активен'} <span class="astraTeamEdit">Изменить</span></div></section>`).join('')||'<p class="muted">Сотрудников пока нет.</p>'}</div>`}
function profilePage(){const u=state.user||{};return `${head('Профиль')}<div class="astraBody"><section class="astraProfileCard"><div class="astraAvatar">${esc(String(u.full_name||'И').slice(0,1).toUpperCase())}</div><div class="astraProfileName">${esc(u.full_name||'Илья')}</div><div class="astraProfileMeta">${roleLabel()} · ${esc(u.city||'Санкт-Петербург')}</div><div style="margin-top:22px"><div class="astraProfileLink" onclick="typeof openOwnerTools==='function'?openOwnerTools():null"><span class="icon">◉</span><span>Диспетчерская</span><span class="arrow">›</span></div><div class="astraProfileLink"><span class="icon">♧</span><span>Клиенты</span><span class="arrow">›</span></div><div class="astraProfileLink"><span class="icon">♢</span><span>Уведомления</span><span class="arrow">›</span></div></div><button class="astraGhostBtn" onclick="reloadData(true)">Обновить профиль</button></section><div class="astraFooterNote">Business OS · ${roleLabel()}</div></div>`}
function navButton(p,l){return `<button data-page="${p}" onclick="show('${p}')"><span class="astraNavIcon">${icon(p)}</span><span>${l}</span></button>`}
function installNav(){const n=document.querySelector('nav');if(!n||!ownerMode())return;n.innerHTML=navButton('home','Главная')+navButton('orders','Заявки')+navButton('dispatch','График')+navButton('team','Команда')+navButton('profile','Профиль')}
if(!ownerMode())return;pages.home=homePage;pages.orders=ordersPage;pages.dispatch=schedulePage;pages.team=teamPage;pages.profile=profilePage;
const originalShow=show;window.show=function(name){originalShow(name);if(ownerMode()){installNav();document.querySelectorAll('nav button').forEach(b=>b.classList.toggle('active',b.dataset.page===name))}};
installNav();setTimeout(()=>window.show(state.page||'home'),40);
})();