(()=>{'use strict';
const META='https://obsropbslfwtanyspjbi.supabase.co/functions/v1/employee-meta-api';
const DIST=['Адмиралтейский','Василеостровский','Выборгский','Калининский','Кировский','Колпинский','Красногвардейский','Красносельский','Кронштадтский','Курортный','Московский','Невский','Петроградский','Петродворцовый','Приморский','Пушкинский','Фрунзенский','Центральный'];
const eid=u=>String(u?.id||u?.staff_id||'');
async function headers(){const h=window.BOS_AUTH_HEADERS?await window.BOS_AUTH_HEADERS():{};h['Content-Type']='application/json';return h}
async function saveMeta(payload){const r=await fetch(META,{method:'POST',headers:await headers(),body:JSON.stringify(payload)});const d=await r.json().catch(()=>({}));if(!r.ok||!d.ok)throw new Error(d.error||'Не удалось сохранить сотрудника');return d.user}
window.astraEditEmployee=function(id){const u=(state.users||[]).find(x=>eid(x)===String(id)||String(x.vk_user_id||x.external_id||'')===String(id));if(!u)return;openModal(`<h2>Сотрудник</h2><form id="astraEmpEdit" class="form"><label>Имя</label><input name="full_name" required value="${esc(u.full_name||'')}"><label>Телефон</label><input name="phone" value="${esc(u.phone||'')}"><label>Роль</label><select name="role">${[['master','Мастер'],['dispatcher','Диспетчер'],['manager','Руководитель'],['owner','Владелец']].map(([v,n])=>`<option value="${v}" ${u.role===v?'selected':''}>${n}</option>`).join('')}</select><label>Город</label><input name="city" value="${esc(u.city||'Санкт-Петербург')}" readonly><label>Район</label><input name="district" list="astraDistricts" value="${esc(u.district||'')}" placeholder="Район города"><datalist id="astraDistricts">${DIST.map(x=>`<option value="${x}">`).join('')}</datalist><label>Специализация</label><input name="specialization" value="${esc(u.specialization||'')}"><div class="two"><div><label>Начало</label><input type="time" name="work_start" value="${esc(String(u.work_start||'09:00').slice(0,5))}"></div><div><label>Конец</label><input type="time" name="work_end" value="${esc(String(u.work_end||'18:00').slice(0,5))}"></div></div><label>Комментарий</label><textarea name="comment">${esc(u.comment||'')}</textarea><label class="astraSwitch"><input type="checkbox" name="is_active" ${u.is_active!==false&&u.active!==false?'checked':''}><span>Сотрудник активен</span></label><button class="primary wide" type="submit">Сохранить изменения</button><p id="astraEmpMsg" class="muted"></p></form>`);const f=document.getElementById('astraEmpEdit');f.onsubmit=async e=>{e.preventDefault();if(state.busy)return;const msg=document.getElementById('astraEmpMsg'),fd=new FormData(f);msg.textContent='Сохраняем…';setBusy(f,true);try{const saved=await saveMeta({id:eid(u),full_name:fd.get('full_name'),phone:fd.get('phone'),role:fd.get('role'),city:'Санкт-Петербург',district:fd.get('district'),specialization:fd.get('specialization'),work_start:fd.get('work_start'),work_end:fd.get('work_end'),comment:fd.get('comment'),is_active:fd.get('is_active')==='on'});const i=state.users.findIndex(x=>eid(x)===eid(u));if(i>=0)state.users[i]={...state.users[i],...saved};const mi=state.masters.findIndex(x=>String(x.id||x.staff_id||'')===eid(u)||String(x.vk_user_id||x.external_id||'')===String(u.vk_user_id||u.external_id||''));if(mi>=0){if(saved.role==='master')state.masters[mi]={...state.masters[mi],...saved};else state.masters.splice(mi,1)}else if(saved.role==='master')state.masters.push(saved);state.busy=false;closeModal();show('team')}catch(err){msg.textContent=err.message;setBusy(f,false)}finally{state.busy=false}}};
function wireTeam(){if(state.page!=='team')return;document.querySelectorAll('.astraTeamCard').forEach((c,i)=>{const u=(state.users||[])[i];if(!u)return;const id=eid(u)||u.vk_user_id||u.external_id;c.onclick=()=>astraEditEmployee(id);const edit=c.querySelector('.astraTeamEdit');if(edit)edit.onclick=e=>{e.stopPropagation();astraEditEmployee(id)}})}
const prev=window.show;window.show=function(n){prev(n);setTimeout(wireTeam,0)};setTimeout(wireTeam,80);
const st=document.createElement('style');st.textContent='.astraTeamCard{cursor:pointer}.astraTeamCard:active{transform:scale(.995)}.astraSwitch{display:flex!important;align-items:center;gap:12px;padding:10px 0}.astraSwitch input{width:22px!important;height:22px!important;min-height:0!important}.astraTeamEdit{text-decoration:underline;text-underline-offset:3px}';document.head.appendChild(st)
})();