(()=>{
'use strict';
const ASTRA_OWNER_ROLES=new Set(['owner','manager']);
const icon=(name)=>({home:'<svg viewBox="0 0 24 24"><rect x="4" y="4" width="6" height="6" rx="1"/><rect x="14" y="4" width="6" height="6" rx="1"/><rect x="4" y="14" width="6" height="6" rx="1"/><rect x="14" y="14" width="6" height="6" rx="1"/></svg>',orders:'<svg viewBox="0 0 24 24"><rect x="5" y="4" width="14" height="17" rx="2"/><path d="M9 4V2h6v2M8 9h8M8 13h8M8 17h5"/></svg>',dispatch:'<svg viewBox="0 0 24 24"><rect x="3" y="5" width="18" height="16" rx="2"/><path d="M7 3v4M17 3v4M3 9h18M8 13h.01M12 13h.01M16 13h.01M8 17h.01M12 17h.01"/></svg>',team:'<svg viewBox="0 0 24 24"><path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2M9 11a4 4 0 1 0 0-8 4 4 0 0 0 0 8ZM22 21v-2a4 4 0 0 0-3-3.87M16 3.13a4 4 0 0 1 0 7.75"/></svg>',profile:'<svg viewBox="0 0 24 24"><circle cx="12" cy="8" r="4"/><path d="M4 21a8 8 0 0 1 16 0"/></svg>'}[name]||'');
function ownerMode(){return ASTRA_OWNER_ROLES.has(String(state.user?.role||'owner'))&&!(typeof isMasterPreview==='function'&&isMasterPreview())&&!(typeof isDispatcherPreview==='function'&&isDispatcherPreview())}
function roleLabel(){const role=String(state.user?.role||'owner');return role==='manager'?'Руководитель':'Руководитель'}
function head(title){return `<section class="astraPageHead"><div class="astraPageHeadRow"><div><div class="astraEyebrow">BUSINESS OS / ${roleLabel()}</div><h1>${esc(title)}</h1></div><button class="astraCreate" onclick="openOrderForm()">＋ Заявка</button></div></section>`}
function initials(name){return String(name||'И').trim().slice(0,1).toUpperCase()||'И'}
function profilePage(){const u=state.user||{};return `${head('Профиль')}<div class="astraBody"><section class="astraProfileCard"><div class="astraAvatar">${esc(initials(u.full_name))}</div><div class="astraProfileName">${esc(u.full_name||'Илья')}</div><div class="astraProfileMeta">${roleLabel()} · ${esc(u.city||'Санкт-Петербург')}</div><div style="margin-top:22px"><div class="astraProfileLink" onclick="typeof openOwnerTools==='function'?openOwnerTools():null"><span class="icon">◉</span><span>Диспетчерская</span><span class="arrow">›</span></div><div class="astraProfileLink"><span class="icon">♧</span><span>Клиенты</span><span class="arrow">›</span></div><div class="astraProfileLink"><span class="icon">♢</span><span>Уведомления</span><span class="arrow">›</span></div></div><button class="astraGhostBtn" onclick="reloadData(true)">Обновить профиль</button></section><div class="astraFooterNote">Business OS · ${roleLabel()}</div></div>`}
function wrap(title,html){return `${head(title)}<div class="astraBody">${html}</div>`}
function installPages(){if(!ownerMode())return;const base={home:pages.home,orders:pages.orders,dispatch:pages.dispatch,team:pages.team};pages.home=function(){return wrap('Главная',base.home())};pages.orders=function(){return wrap('Заявки',base.orders())};pages.dispatch=function(){return wrap('График',base.dispatch())};pages.team=function(){return wrap('Команда',base.team())};pages.profile=profilePage}
function navButton(page,label){return `<button data-page="${page}" onclick="show('${page}')"><span class="astraNavIcon">${icon(page)}</span><span>${label}</span></button>`}
function installNav(){const nav=document.querySelector('nav');if(!nav||!ownerMode())return;nav.innerHTML=navButton('home','Главная')+navButton('orders','Заявки')+navButton('dispatch','График')+navButton('team','Команда')+navButton('profile','Профиль')}
function enhanceTeam(){if(!ownerMode()||state.page!=='team')return;const body=document.querySelector('.astraBody');if(!body)return;body.querySelectorAll('.card').forEach(c=>c.classList.add('astraTeamCard'))}
function enhanceOrders(){if(!ownerMode()||state.page!=='orders')return;const body=document.querySelector('.astraBody');if(!body)return;body.querySelectorAll('.order,.dashOrder').forEach(c=>c.classList.add('astraOrderCard'))}
const originalShow=show;
window.show=function(name){originalShow(name);if(ownerMode()){installNav();document.querySelectorAll('nav button').forEach(b=>b.classList.toggle('active',b.dataset.page===name));enhanceTeam();enhanceOrders()}}
installPages();installNav();
setTimeout(()=>{if(ownerMode())window.show(state.page||'home')},40);
})();