const CLAIMS_API='https://obsropbslfwtanyspjbi.supabase.co/functions/v1/business-os-api';
state.claims=state.claims||[];
async function claimsApi(action,payload={}){const r=await fetch(CLAIMS_API,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,actor_role:state.user?.role||'owner',...payload})});const d=await r.json();if(!r.ok||!d.ok)throw new Error(d.error||'Ошибка сервера');return d}
async function refreshClaims(){try{const d=await claimsApi('bootstrap');state.claims=d.claims||[];if(d.orders?.length)state.supabaseOrders=d.orders}catch(e){console.warn(e)}return state.claims}
function claimOrder(c){return (state.supabaseOrders||[]).find(o=>String(o.id)===String(c.order_id))||state.orders.find(o=>String(o.supabase_id||o.id)===String(c.order_id))}
function claimMasterName(c){const m=(state.masters||[]).find(x=>String(x.id||x.vk_user_id)===String(c.master_id));return m?.profiles?.full_name||m?.full_name||'Мастер'}
function claimOverdue(c){if(c.status!=='open'||!c.scheduled_date)return false;const t=new Date(String(c.scheduled_date)+'T'+String(c.scheduled_time||'23:59:00'));return t.getTime()<Date.now()}
function claimsDashboardHtml(){const a=state.claims||[],open=a.filter(c=>c.status==='open'),closed=a.filter(c=>c.status==='closed'),late=open.filter(claimOverdue);const pay=a.reduce((s,c)=>s+Number(c.revisit_payment||0),0);const byMaster={};a.forEach(c=>{const n=claimMasterName(c);byMaster[n]=(byMaster[n]||0)+1});const stats=Object.entries(byMaster).sort((x,y)=>y[1]-x[1]);return `<div class="row"><div><h2>Претензии</h2><div class="muted">Контроль повторных выездов</div></div><button class="secondary" onclick="refreshClaims().then(()=>showClaims())">Обновить</button></div><div class="grid"><div class="card metric"><span class="muted">Открыто</span><strong>${open.length}</strong></div><div class="card metric"><span class="muted">Просрочено</span><strong>${late.length}</strong></div><div class="card metric"><span class="muted">Закрыто</span><strong>${closed.length}</strong></div><div class="card metric"><span class="muted">Повторные выезды</span><strong>${money(pay)}</strong></div></div>${open.length?`<h3>Открытые</h3>${open.map(claimCardHtml).join('')}`:'<section class="card"><p class="muted">Открытых претензий нет.</p></section>'}${closed.length?`<h3>Закрытые</h3>${closed.slice(0,20).map(claimCardHtml).join('')}`:''}${stats.length?`<section class="card"><h3>По мастерам</h3>${stats.map(([n,c])=>`<div class="row"><span>${esc(n)}</span><b>${c}</b></div>`).join('')}</section>`:''}`}
function claimCardHtml(c){const o=claimOrder(c),late=claimOverdue(c);return `<section class="card" onclick="openClaimDetails('${esc(c.id)}')"><div class="row"><b>${o?esc(o.id):'Заявка '+esc(c.order_id)}</b><span class="status ${late?'danger':'info'}">${c.status==='closed'?'Закрыта':late?'Просрочена':'Открыта'}</span></div><p><b>${esc(c.reason||'Претензия')}</b></p><p class="muted">${esc(claimMasterName(c))}${c.scheduled_date?' · '+esc(c.scheduled_date)+' '+esc(String(c.scheduled_time||'').slice(0,5)):''}</p>${c.pay_revisit?`<p>Оплата выезда: <b>${money(c.revisit_payment||0)}</b></p>`:'<p class="muted">Повторный выезд без оплаты</p>'}</section>`}
function showClaims(){state.page='claims';$('#content').innerHTML=claimsDashboardHtml();document.querySelectorAll('nav button').forEach(b=>b.classList.remove('active'))}
function openClaimDetails(id){const c=(state.claims||[]).find(x=>String(x.id)===String(id));if(!c)return;const o=claimOrder(c);openModal(`<h2>Претензия</h2><p><b>Причина:</b> ${esc(c.reason||'')}</p><p><b>Что исправить:</b> ${esc(c.required_work||'—')}</p><p><b>Мастер:</b> ${esc(claimMasterName(c))}</p><p><b>Повторный выезд:</b> ${c.pay_revisit?money(c.revisit_payment||0):'без оплаты'}</p>${c.payment_note?`<p class="muted">${esc(c.payment_note)}</p>`:''}${o?`<button class="primary wide" onclick="closeModal();openOrder('${esc(o.id)}')">Открыть заявку</button>`:''}<button class="secondary wide" onclick="closeModal()">Закрыть</button>`)}
function openReopenClaimForm(orderId){const o=(state.supabaseOrders||[]).find(x=>String(x.id)===String(orderId))||state.orders.find(x=>String(x.supabase_id||x.id)===String(orderId));if(!o)return;openModal(`<h2>Открыть претензию</h2><form id="claimForm" class="form"><textarea name="reason" placeholder="Причина претензии" required></textarea><textarea name="required_work" placeholder="Что нужно исправить"></textarea><div class="two"><input type="date" name="scheduled_date"><input type="time" name="scheduled_time"></div><label><input id="claimPay" type="checkbox"> Оплатить повторный выезд</label><div id="claimPayBox" style="display:none"><input type="number" name="revisit_payment" min="0" step="0.01" placeholder="Сумма мастеру"><input name="payment_note" placeholder="Комментарий к оплате"></div><button class="primary wide" type="submit">Открыть претензию</button><p id="claimMsg" class="muted"></p></form>`);$('#claimPay').onchange=()=>$('#claimPayBox').style.display=$('#claimPay').checked?'block':'none';$('#claimForm').onsubmit=async e=>{e.preventDefault();const f=Object.fromEntries(new FormData(e.currentTarget)),msg=$('#claimMsg');msg.textContent='Открываем…';try{const d=await claimsApi('reopenClaim',{id:o.id,reason:f.reason,required_work:f.required_work,scheduled_date:f.scheduled_date||null,scheduled_time:f.scheduled_time||null,pay_revisit:$('#claimPay').checked,revisit_payment:Number(f.revisit_payment||0),payment_note:f.payment_note||''});state.claims.unshift(d.claim);if(d.order){const arr=state.supabaseOrders||[];const i=arr.findIndex(x=>String(x.id)===String(d.order.id));if(i>=0)arr[i]=d.order}closeModal();showClaims()}catch(err){msg.textContent=err.message}}}
const claimsHomeBase=pages.home;pages.home=function(){const base=claimsHomeBase();if(typeof isMasterPreview==='function'&&isMasterPreview())return base;setTimeout(()=>refreshClaims(),0);return base+`<section class="card"><div class="row"><div><h3>Претензии</h3><p class="muted">Открытые и повторные выезды</p></div><button class="primary" onclick="refreshClaims().then(()=>showClaims())">Открыть</button></div></section>`};
const claimsOpenOrderBase=openOrder;openOrder=function(id){claimsOpenOrderBase(id);if(typeof isMasterPreview==='function'&&isMasterPreview())return;const o=state.orders.find(x=>String(x.id)===String(id));if(!o||o.status!=='Выполнена')return;const supId=o.supabase_id||(/^[0-9]+$/.test(String(o.id))?o.id:null);if(!supId)return;const modal=document.querySelector('.modal');if(modal)modal.insertAdjacentHTML('beforeend',`<button class="secondary wide" onclick="openReopenClaimForm('${esc(supId)}')">Открыть претензию</button>`)};