const originalHome=pages.home;
pages.home=function(){
  const done=state.orders.filter(o=>o.status==='Выполнена');
  const rev=done.reduce((a,o)=>a+Number(o.amount||0),0);
  const extras=done.reduce((a,o)=>a+Number(o.extra_work_amount||0),0);
  const uncompleted=done.reduce((a,o)=>a+Number(o.uncompleted_work_amount||0),0);
  const collected=rev+extras;
  const masters=done.reduce((a,o)=>a+(window.BOS_ORDER_PAYROLL?.directMaster(o)??payout(o.amount)),0);
  const company=done.reduce((a,o)=>a+Number(window.BOS_ORDER_PAYROLL?.companyShare?.(o)??0),0);
  return `<section class="hero"><div class="eyebrow">ВЛАДЕЛЕЦ · БЕЗ ВХОДА</div><h2>Business OS</h2><p class="muted">Google Sheets синхронизированы с приложением.</p></section><div class="grid"><div class="card metric"><span class="muted">Заявок</span><strong>${state.orders.length}</strong></div><div class="card metric"><span class="muted">Мастеров</span><strong>${state.masters.length}</strong></div><div class="card metric"><span class="muted">В работе</span><strong>${state.orders.filter(o=>o.status==='В работе').length}</strong></div><div class="card metric"><span class="muted">Выручка по заявкам</span><strong>${money(rev)}</strong></div><div class="card metric"><span class="muted">Допработы</span><strong>${money(extras)}</strong></div><div class="card metric"><span class="muted">Невыполненные работы</span><strong>− ${money(uncompleted)}</strong></div><div class="card metric"><span class="muted">Получено с допработами</span><strong>${money(collected)}</strong></div><div class="card metric"><span class="muted">Мастерам</span><strong>${money(masters)}</strong></div><div class="card metric"><span class="muted">Доля компании</span><strong>${money(company)}</strong></div></div><section class="card"><h3>Формулы</h3><p class="muted">Выплата мастеру рассчитывается по действующей формуле источника без изменений.</p><p class="muted">Руководителю и диспетчеру отдельная зарплата по заявкам не начисляется. Остаток после выплаты мастеру относится к доле компании.</p><p class="muted">Допработы учитываются отдельно и полностью относятся к выплате мастеру.</p></section>`;
};