(()=>{
'use strict';
if(window.BOS_NOTIFICATIONS_V26)return;window.BOS_NOTIFICATIONS_V26=true;
const READ='bos_notifications_read_v26:',SNAP='bos_notifications_snapshot_v26:';
let open=false,lastSig='';
const escv=v=>typeof esc==='function'?esc(v):String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const role=()=>String(state?.user?.role||'');
const uid=()=>String(state?.user?.external_id||state?.user?.vk_user_id||state?.user?.id||role()||'guest');
const orderId=o=>String(o?.id||'');
const dateOf=o=>String(o?.scheduled_date||'').slice(0,10);
const timeOf=o=>String(o?.scheduled_time||o?.time_slot||'').slice(0,5);
const active=o=>!['Выполнена','Отменена','completed','cancelled'].includes(String(o?.status||''));
const today=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};
function late(o){const d=dateOf(o),t=timeOf(o);if(!d||!/^\d{2}:\d{2}$/.test(t))return false;if(d<today())return true;if(d!==today())return false;const n=new Date(),[h,m]=t.split(':').map(Number);return n.getHours()*60+n.getMinutes()>h*60+m+15}
function readSet(){try{return new Set(JSON.parse(localStorage.getItem(READ+uid())||'[]'))}catch(_){return new Set()}}
function saveRead(set){try{localStorage.setItem(READ+uid(),JSON.stringify([...set].slice(-300)))}catch(_){}}
function oldSnap(){try{return JSON.parse(localStorage.getItem(SNAP+uid())||'{}')||{}}catch(_){return{}}}
function ownOrders(){const r=role(),me=state?.user||{};if(r!=='master')return[];if(typeof window.ownOrders==='function')return window.ownOrders()||[];return(state?.orders||[]).filter(o=>String(o.master_staff_id||'')===String(me.id||'')||String(o.master_vk_id||'')===String(me.external_id||me.vk_user_id||''))}
function masterEvents(){const prev=oldSnap(),next={},out=[];for(const o of ownOrders().filter(active)){const id=orderId(o),sig=[o.master_staff_id||o.master_vk_id||'',dateOf(o),timeOf(o)].join('|');next[id]=sig;const changed=Boolean(prev[id]&&prev[id]!==sig);out.push({key:`master:${id}:${sig}`,kind:changed?'changed':'assigned',priority:changed?1:3,order:id,title:changed?'Изменено время заявки':'Заявка назначена',text:`№ ${id} · ${dateOf(o)||'без даты'} ${timeOf(o)||''} · ${o.client||'Клиент'}`})}try{localStorage.setItem(SNAP+uid(),JSON.stringify(next))}catch(_){}return out}
function opsEvents(){if(!['dispatcher','manager','owner'].includes(role()))return[];const out=[];for(const o of(state?.orders||[]).filter(active)){const id=orderId(o);if(o.reschedule_requested)out.push({key:`reschedule:${id}:${o.reschedule_requested_at||o.reschedule_reason||'1'}`,kind:'reschedule',priority:0,order:id,title:'Запрошен перенос',text:`№ ${id} · ${o.client||'Клиент'}${o.reschedule_reason?` · ${o.reschedule_reason}`:''}`});if(!o.master_staff_id&&!o.master_vk_id)out.push({key:`unassigned:${id}`,kind:'unassigned',priority:2,order:id,title:'Без мастера',text:`№ ${id} · ${dateOf(o)||'без даты'} ${timeOf(o)||''} · ${o.client||'Клиент'}`});if(late(o))out.push({key:`overdue:${id}:${dateOf(o)}:${timeOf(o)}`,kind:'overdue',priority:1,order:id,title:'Время заявки прошло',text:`№ ${id} · ${dateOf(o)} ${timeOf(o)} · ${o.master_name||'мастер не назначен'}`})}return out}
function events(){return[...masterEvents(),...opsEvents()].sort((a,b)=>a.priority-b.priority||a.title.localeCompare(b.title,'ru'))}
function ensureButton(){if(!state?.user)return null;const header=document.querySelector('#app header')||document.querySelector('header');if(!header)return null;let b=document.getElementById('bosNotificationsBtn');if(!b){b=document.createElement('button');b.id='bosNotificationsBtn';b.className='bosNotifBtn';b.type='button';b.setAttribute('aria-label','Уведомления');b.innerHTML='<span aria-hidden="true">🔔</span><b class="bosNotifBadge" hidden>0</b>';b.onclick=()=>{open=!open;render()};const profile=document.getElementById('profileBtn');if(profile&&profile.parentElement===header)header.insertBefore(b,profile);else header.appendChild(b)}return b}
function mark(key){const s=readSet();s.add(key);saveRead(s);render()}
function openEvent(key,id){mark(key);open=false;render();if(id&&typeof window.openOrder==='function')window.openOrder(id)}
window.bosNotificationOpen=openEvent;
window.bosNotificationsMarkAll=function(){const s=readSet();events().forEach(x=>s.add(x.key));saveRead(s);render()};
function panelHtml(list,reads){return `<div class="bosNotifBackdrop" onclick="if(event.target===this){window.bosNotificationsToggle()}"><aside class="bosNotifPanel"><div class="bosNotifHead"><div><small>ЦЕНТР УВЕДОМЛЕНИЙ</small><h3>Требует внимания</h3></div><button type="button" class="secondary" onclick="window.bosNotificationsToggle()">×</button></div>${list.length?`<div class="bosNotifTools"><span>${list.filter(x=>!reads.has(x.key)).length} непрочитано</span><button type="button" class="secondary" onclick="window.bosNotificationsMarkAll()">Прочитать все</button></div><div class="bosNotifList">${list.map(x=>`<button type="button" class="bosNotifItem ${reads.has(x.key)?'read':''} ${escv(x.kind)}" onclick="bosNotificationOpen('${escv(x.key)}','${escv(x.order)}')"><i></i><span><b>${escv(x.title)}</b><small>${escv(x.text)}</small></span></button>`).join('')}</div>`:'<div class="bosNotifEmpty"><b>Всё спокойно</b><span>Новых уведомлений нет.</span></div>'}</aside></div>`}
window.bosNotificationsToggle=function(){open=!open;render()};
function render(){const b=ensureButton();if(!b)return;const list=events(),reads=readSet(),unread=list.filter(x=>!reads.has(x.key)).length,badge=b.querySelector('.bosNotifBadge');if(badge){badge.textContent=String(unread);badge.hidden=!unread}b.classList.toggle('hasUnread',unread>0);let root=document.getElementById('bosNotificationsRoot');if(!root){root=document.createElement('div');root.id='bosNotificationsRoot';document.body.appendChild(root)}const sig=JSON.stringify([open,list.map(x=>x.key),[...reads].filter(x=>list.some(n=>n.key===x))]);if(sig===lastSig)return;lastSig=sig;root.innerHTML=open?panelHtml(list,reads):''}
window.__bosNotificationsRefresh=()=>{lastSig='';render()};
let queued=false;new MutationObserver(()=>{if(queued)return;queued=true;requestAnimationFrame(()=>{queued=false;render()})}).observe(document.documentElement,{childList:true,subtree:true});
setInterval(()=>{lastSig='';render()},30000);setTimeout(render,0);
const st=document.createElement('style');st.textContent=`.bosNotifBtn{position:relative;width:38px;height:38px;display:grid;place-items:center;border:1px solid rgba(127,127,127,.16);border-radius:11px;background:rgba(127,127,127,.06);color:inherit;cursor:pointer}.bosNotifBadge{position:absolute;right:-5px;top:-5px;min-width:18px;height:18px;padding:0 4px;border-radius:99px;background:#dc2626;color:#fff;font-size:10px;line-height:18px}.bosNotifBackdrop{position:fixed;inset:0;z-index:1200000;background:rgba(4,8,14,.62);display:flex;justify-content:flex-end}.bosNotifPanel{width:min(92vw,430px);height:100%;overflow:auto;background:var(--card,#101b2a);color:inherit;padding:18px;box-shadow:-20px 0 50px rgba(0,0,0,.28)}.bosNotifHead,.bosNotifTools{display:flex;align-items:center;justify-content:space-between;gap:10px}.bosNotifHead small{font-size:10px;color:var(--muted,#91a3b7);font-weight:800}.bosNotifHead h3{margin:3px 0}.bosNotifHead>button{width:38px}.bosNotifTools{margin:14px 0;font-size:12px}.bosNotifList{display:grid;gap:8px}.bosNotifItem{width:100%;display:grid;grid-template-columns:10px 1fr;gap:9px;text-align:left;padding:11px;border:1px solid rgba(127,127,127,.16);border-radius:12px;background:rgba(127,127,127,.055);color:inherit}.bosNotifItem i{width:8px;height:8px;margin-top:5px;border-radius:50%;background:#2563eb}.bosNotifItem.reschedule i,.bosNotifItem.overdue i{background:#dc2626}.bosNotifItem.read{opacity:.62}.bosNotifItem.read i{background:#94a3b8}.bosNotifItem span{display:grid;gap:3px}.bosNotifItem small{color:var(--muted,#91a3b7);line-height:1.35}.bosNotifEmpty{min-height:220px;display:grid;place-content:center;text-align:center;gap:5px}.bosNotifEmpty span{color:var(--muted,#91a3b7);font-size:12px}@media(max-width:520px){.bosNotifPanel{width:100vw}.bosNotifBtn{width:34px;height:34px}}`;document.head.appendChild(st);
})();