import { createClient } from 'npm:@supabase/supabase-js@2';
const cors={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'content-type,apikey,authorization,x-vk-launch-params,x-bos-session','Access-Control-Allow-Methods':'POST,OPTIONS'};
const json=(x:any,s=200)=>new Response(JSON.stringify(x),{status:s,headers:{...cors,'Content-Type':'application/json'}});
const round=(n:any)=>Math.round(Number(n||0)*100)/100;
const payouts=(a:any)=>{const x=round(a);return{master_payout:round(x*.85*.35),manager_payout:round(x*.85*.94*.20),dispatcher_payout:round(x*.85*.94*.15)}};
function bytes(b64:string){const raw=atob(String(b64||'').replace(/^data:[^;]+;base64,/,'')),out=new Uint8Array(raw.length);for(let i=0;i<raw.length;i++)out[i]=raw.charCodeAt(i);return out}
function safe(s:string){return String(s||'file').replace(/[^a-zA-Z0-9._-]+/g,'_').slice(-120)}
function b64u(a:Uint8Array){let s='';for(const b of a)s+=String.fromCharCode(b);return btoa(s).replace(/=/g,'').replace(/\+/g,'-').replace(/\//g,'_')}
async function hmac(msg:string,secret:string){const key=await crypto.subtle.importKey('raw',new TextEncoder().encode(secret),{name:'HMAC',hash:'SHA-256'},false,['sign']);return b64u(new Uint8Array(await crypto.subtle.sign('HMAC',key,new TextEncoder().encode(msg))))}
async function verifyLaunch(raw:string,secret:string){if(!raw)return null;const p=new URLSearchParams(raw.startsWith('?')?raw.slice(1):raw),sign=p.get('sign'),app=p.get('vk_app_id'),uid=p.get('vk_user_id');if(!sign||app!=='54758847'||!uid||!/^[1-9]\d*$/.test(uid))return null;const c=[...p.entries()].filter(([k])=>k.startsWith('vk_')).sort(([a],[b])=>a.localeCompare(b)).map(([k,v])=>`${k}=${encodeURIComponent(v)}`).join('&'),exp=await hmac(c,secret);if(exp.length!==sign.length)return null;let m=0;for(let i=0;i<exp.length;i++)m|=exp.charCodeAt(i)^sign.charCodeAt(i);return m===0?uid:null}
async function verifySession(token:string,secret:string){const p=String(token||'').split('.');if(p.length!==3||!/^[A-Za-z0-9_-]+$/.test(p[0])||!/^[0-9]+$/.test(p[1]))return null;if(Number(p[1])<Math.floor(Date.now()/1000))return null;const exp=await hmac(`${p[0]}.${p[1]}`,secret);if(exp.length!==p[2].length)return null;let m=0;for(let i=0;i<exp.length;i++)m|=exp.charCodeAt(i)^p[2].charCodeAt(i);return m===0?p[0]:null}
async function makeSession(uid:string,secret:string){const exp=Math.floor(Date.now()/1000)+43200,msg=`${uid}.${exp}`;return`${msg}.${await hmac(msg,secret)}`}
Deno.serve(async req=>{if(req.method==='OPTIONS')return new Response('ok',{headers:cors});try{const body=await req.json();const allowed=['uploadMasterReport','uploadReportFile','finalizeMasterReport'];if(!allowed.includes(body.action))return json({ok:false,error:'UNKNOWN_ACTION'},404);const url=Deno.env.get('SUPABASE_URL')!,key=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!,secret=Deno.env.get('VK_APP_SECRET')||'',bucket='business-os-vk-files';if(!url||!key||!secret)throw new Error('Server configuration missing');const db=createClient(url,key,{auth:{persistSession:false}});let uid=await verifySession(req.headers.get('x-bos-session')||'',secret),session_token='';if(!uid){uid=await verifyLaunch(req.headers.get('x-vk-launch-params')||'',secret);if(uid)session_token=await makeSession(uid,secret)}if(!uid)return json({ok:false,error:'Доступ не подтверждён'},401);const aq=await db.from('business_staff').select('*').eq('external_id',uid).eq('is_active',true).maybeSingle();if(aq.error)throw aq.error;let actor=aq.data;if(!actor)return json({ok:false,error:'Сотрудник не найден'},403);
if(actor.role==='owner'&&body.acting_master_vk_id){const target=String(body.acting_master_vk_id);const tq=await db.from('business_staff').select('*').eq('external_id',target).eq('role','master').eq('is_active',true).maybeSingle();if(tq.error)throw tq.error;if(!tq.data)return json({ok:false,error:'Мастер не найден'},404);actor=tq.data}else if(actor.role!=='master')return json({ok:false,error:'Отчёт может загрузить только мастер'},403);
const orderId=String(body.order_id||'');if(!orderId)return json({ok:false,error:'ORDER_ID_REQUIRED'},400);const q=await db.from('orders').select('*').eq('id',orderId).single();if(q.error)throw q.error;if(String(q.data.master_staff_id||'')!==String(actor.id))return json({ok:false,error:'Эта заявка назначена другому мастеру'},403);const token=String(body.upload_token||'');if(!token)return json({ok:false,error:'UPLOAD_TOKEN_REQUIRED'},400);const base=`orders/${orderId}/${safe(token)}`;async function put(name:string,mime:string,data:string){if(!data)return '';const path=`${base}/${safe(name)}`;const up=await db.storage.from(bucket).upload(path,bytes(data),{contentType:mime||'application/octet-stream',upsert:true});if(up.error)throw up.error;const sig=await db.storage.from(bucket).createSignedUrl(path,60*60*24*365);if(sig.error)throw sig.error;return sig.data.signedUrl}
if(body.action==='uploadReportFile'){const kind=String(body.file_kind||'');if(!['act','photo'].includes(kind))return json({ok:false,error:'INVALID_FILE_KIND'},400);if(!body.file_data)return json({ok:false,error:'FILE_REQUIRED'},400);const idx=Number(body.file_index||0),name=kind==='act'?`act_${safe(body.file_name||'act')}`:`photo_${idx}_${safe(body.file_name||'photo.jpg')}`;const out=await put(name,String(body.file_mime||''),String(body.file_data||''));return json({ok:true,session_token:session_token||undefined,url:out})}
if(body.action==='finalizeMasterReport'){const act=String(body.act_url||'');const photos=Array.isArray(body.photo_urls)?body.photo_urls.filter(Boolean).slice(0,5):[];if(!act)return json({ok:false,error:'ACT_REQUIRED'},400);if(!photos.length)return json({ok:false,error:'PHOTO_REQUIRED'},400);const original=Number(q.data.original_amount||q.data.amount||0),unfinished=Number(body.uncompleted_work_amount||0),amount=round(original-unfinished),now=new Date().toISOString();const patch:any={status:'Выполнена',amount,extra_work_done:!!body.extra_work_done,extra_work_description:String(body.extra_work_description||''),extra_work_amount:round(body.extra_work_amount||0),uncompleted_work_done:!!body.uncompleted_work_done,uncompleted_work_description:String(body.uncompleted_work_description||''),uncompleted_work_amount:round(unfinished),report_type:'work',report_act_url:act,report_measurement_url:null,report_photo_urls:JSON.stringify(photos),report_uploaded_at:now,report_upload_token:token,report_review_status:'pending',report_reviewed_by:null,report_reviewed_at:null,report_review_comment:'',drive_archive_status:'pending',drive_archive_error:null,completed_at:now,sync_status:'pending_sheet',updated_at:now,...payouts(amount)};const r=await db.from('orders').update(patch).eq('id',orderId).select().single();if(r.error)throw r.error;return json({ok:true,session_token:session_token||undefined,order:r.data,drive_archive_status:'pending'})}
if(!body.act_data)return json({ok:false,error:'ACT_REQUIRED'},400);let photos:any[]=[];try{photos=JSON.parse(body.photos_json||'[]')}catch{}if(!photos.length)return json({ok:false,error:'PHOTO_REQUIRED'},400);const act=await put(body.act_name||'act',body.act_mime,body.act_data);const photoUrls=[];for(const [i,p] of photos.slice(0,5).entries())photoUrls.push(await put(p.name||`photo_${i+1}.jpg`,p.mime||'image/jpeg',p.data));const original=Number(q.data.original_amount||q.data.amount||0),unfinished=Number(body.uncompleted_work_amount||0),amount=round(original-unfinished),now=new Date().toISOString();const patch:any={status:'Выполнена',amount,extra_work_done:!!body.extra_work_done,extra_work_description:String(body.extra_work_description||''),extra_work_amount:round(body.extra_work_amount||0),uncompleted_work_done:!!body.uncompleted_work_done,uncompleted_work_description:String(body.uncompleted_work_description||''),uncompleted_work_amount:round(unfinished),report_type:'work',report_act_url:act,report_measurement_url:null,report_photo_urls:JSON.stringify(photoUrls),report_uploaded_at:now,report_upload_token:token,report_review_status:'pending',report_reviewed_by:null,report_reviewed_at:null,report_review_comment:'',drive_archive_status:'pending',drive_archive_error:null,completed_at:now,sync_status:'pending_sheet',updated_at:now,...payouts(amount)};const r=await db.from('orders').update(patch).eq('id',orderId).select().single();if(r.error)throw r.error;return json({ok:true,session_token:session_token||undefined,order:r.data,drive_archive_status:'pending'})}catch(e){return json({ok:false,error:e instanceof Error?e.message:String(e)},500)}});
