import { createClient } from 'npm:@supabase/supabase-js@2';
const cors={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'content-type,x-bos-session,x-vk-launch-params','Access-Control-Allow-Methods':'POST,OPTIONS'};
const json=(x:any,s=200)=>new Response(JSON.stringify(x),{status:s,headers:{...cors,'Content-Type':'application/json'}});
function b64u(a:Uint8Array){let s='';for(const b of a)s+=String.fromCharCode(b);return btoa(s).replace(/=/g,'').replace(/\+/g,'-').replace(/\//g,'_')}
async function hmac(msg:string,secret:string){const key=await crypto.subtle.importKey('raw',new TextEncoder().encode(secret),{name:'HMAC',hash:'SHA-256'},false,['sign']);return b64u(new Uint8Array(await crypto.subtle.sign('HMAC',key,new TextEncoder().encode(msg))))}
async function verifySession(token:string,secret:string){const p=String(token||'').split('.');if(p.length!==3||!/^[A-Za-z0-9_-]+$/.test(p[0])||!/^[0-9]+$/.test(p[1]))return null;if(Number(p[1])<Math.floor(Date.now()/1000))return null;const e=await hmac(`${p[0]}.${p[1]}`,secret);if(e.length!==p[2].length)return null;let m=0;for(let i=0;i<e.length;i++)m|=e.charCodeAt(i)^p[2].charCodeAt(i);return m===0?p[0]:null}
async function verifyLaunch(raw:string,secret:string){if(!raw)return null;const p=new URLSearchParams(raw.startsWith('?')?raw.slice(1):raw),sign=p.get('sign'),app=p.get('vk_app_id'),uid=p.get('vk_user_id');if(!sign||app!=='54758847'||!uid||!/^[1-9]\d*$/.test(uid))return null;const c=[...p.entries()].filter(([k])=>k.startsWith('vk_')).sort(([a],[b])=>a.localeCompare(b)).map(([k,v])=>`${k}=${encodeURIComponent(v)}`).join('&'),e=await hmac(c,secret);if(e.length!==sign.length)return null;let m=0;for(let i=0;i<e.length;i++)m|=e.charCodeAt(i)^sign.charCodeAt(i);return m===0?uid:null}
function bytes(b64:string){const raw=atob(String(b64||'').replace(/^data:[^;]+;base64,/,'')),out=new Uint8Array(raw.length);for(let i=0;i<raw.length;i++)out[i]=raw.charCodeAt(i);return out}
function safeName(v:string){return String(v||'file').replace(/[^a-zA-Z0-9._-]+/g,'_').slice(-120)}
Deno.serve(async req=>{if(req.method==='OPTIONS')return new Response('ok',{headers:cors});if(req.method!=='POST')return json({ok:false,error:'METHOD_NOT_ALLOWED'},405);try{const url=Deno.env.get('SUPABASE_URL')!,key=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!,secret=Deno.env.get('VK_APP_SECRET')||'';if(!url||!key||!secret)throw new Error('Server configuration missing');const db=createClient(url,key,{auth:{persistSession:false}});let uid=await verifySession(req.headers.get('x-bos-session')||'',secret);if(!uid)uid=await verifyLaunch(req.headers.get('x-vk-launch-params')||'',secret);if(!uid)return json({ok:false,error:'Доступ не подтверждён'},401);const aq=await db.from('business_staff').select('*').eq('external_id',uid).eq('is_active',true).maybeSingle();if(aq.error)throw aq.error;const actor=aq.data;if(!actor)return json({ok:false,error:'Сотрудник не найден'},403);const body=await req.json().catch(()=>({})),action=String(body.action||'list'),role=String(actor.role||'');if(action==='list'){if(!['owner','manager','master'].includes(role))return json({ok:false,error:'Недостаточно прав'},403);const q=await db.from('master_memo_materials').select('*').order('created_at',{ascending:false});if(q.error)throw q.error;const items=[];for(const x of q.data||[]){let file_url='';if(x.storage_path){const s=await db.storage.from('business-os-vk-files').createSignedUrl(x.storage_path,60*60*24*7);if(!s.error)file_url=s.data.signedUrl}items.push({...x,file_url})}return json({ok:true,items})}
if(action==='upload'){if(!['owner','manager'].includes(role))return json({ok:false,error:'Только владелец или руководитель может управлять памяткой'},403);const category=String(body.category||''),title=String(body.title||'').trim(),note=String(body.note||'').trim();if(!['acts','measurements','price','tips'].includes(category))return json({ok:false,error:'Неверный раздел'},400);if(!title)return json({ok:false,error:'Укажите название'},400);let path:string|null=null,fileName:string|null=null,mime:string|null=null;if(body.file_data){const data=bytes(body.file_data);if(data.byteLength>10*1024*1024)return json({ok:false,error:'Файл больше 10 МБ'},400);fileName=safeName(String(body.file_name||'file'));mime=String(body.file_mime||'application/octet-stream');path=`master-memo/${category}/${Date.now()}_${crypto.randomUUID()}_${fileName}`;const up=await db.storage.from('business-os-vk-files').upload(path,data,{contentType:mime,upsert:false});if(up.error)throw up.error}const r=await db.from('master_memo_materials').insert({category,title,note:note||null,file_name:fileName,mime,storage_path:path,created_by:actor.id}).select().single();if(r.error){if(path)await db.storage.from('business-os-vk-files').remove([path]);throw r.error}return json({ok:true,item:r.data})}
if(action==='delete'){if(!['owner','manager'].includes(role))return json({ok:false,error:'Только владелец или руководитель может управлять памяткой'},403);const q=await db.from('master_memo_materials').select('*').eq('id',String(body.id||'')).maybeSingle();if(q.error)throw q.error;if(!q.data)return json({ok:false,error:'Материал не найден'},404);if(q.data.storage_path)await db.storage.from('business-os-vk-files').remove([q.data.storage_path]);const d=await db.from('master_memo_materials').delete().eq('id',q.data.id);if(d.error)throw d.error;return json({ok:true})}return json({ok:false,error:'UNKNOWN_ACTION'},404)}catch(e){return json({ok:false,error:e instanceof Error?e.message:String(e)},500)}});
