import { createClient } from 'npm:@supabase/supabase-js@2';
const cors={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'content-type,x-bos-session,x-vk-launch-params','Access-Control-Allow-Methods':'POST,OPTIONS'};
const json=(x:any,s=200)=>new Response(JSON.stringify(x),{status:s,headers:{...cors,'Content-Type':'application/json'}});
function b64u(a:Uint8Array){let s='';for(const b of a)s+=String.fromCharCode(b);return btoa(s).replace(/=/g,'').replace(/\+/g,'-').replace(/\//g,'_')}
async function hmac(msg:string,secret:string){const key=await crypto.subtle.importKey('raw',new TextEncoder().encode(secret),{name:'HMAC',hash:'SHA-256'},false,['sign']);return b64u(new Uint8Array(await crypto.subtle.sign('HMAC',key,new TextEncoder().encode(msg))))}
async function verifySession(token:string,secret:string){const p=String(token||'').split('.');if(p.length!==3||!/^[A-Za-z0-9_-]+$/.test(p[0])||!/^[0-9]+$/.test(p[1]))return null;if(Number(p[1])<Math.floor(Date.now()/1000))return null;const exp=await hmac(`${p[0]}.${p[1]}`,secret);if(exp.length!==p[2].length)return null;let m=0;for(let i=0;i<exp.length;i++)m|=exp.charCodeAt(i)^p[2].charCodeAt(i);return m===0?p[0]:null}
async function verifyLaunch(raw:string,secret:string){if(!raw)return null;const p=new URLSearchParams(raw.startsWith('?')?raw.slice(1):raw),sign=p.get('sign'),app=p.get('vk_app_id'),uid=p.get('vk_user_id');if(!sign||app!=='54758847'||!uid)return null;const c=[...p.entries()].filter(([k])=>k.startsWith('vk_')).sort(([a],[b])=>a.localeCompare(b)).map(([k,v])=>`${k}=${encodeURIComponent(v)}`).join('&'),exp=await hmac(c,secret);if(exp.length!==sign.length)return null;let m=0;for(let i=0;i<exp.length;i++)m|=exp.charCodeAt(i)^sign.charCodeAt(i);return m===0?uid:null}
function safe(s:string){return String(s||'file').replace(/[^a-zA-Z0-9._-]+/g,'_').slice(-120)}
Deno.serve(async req=>{if(req.method==='OPTIONS')return new Response('ok',{headers:cors});try{const url=Deno.env.get('SUPABASE_URL')!,key=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!,secret=Deno.env.get('VK_APP_SECRET')||'',bucket='business-os-vk-files';const db=createClient(url,key,{auth:{persistSession:false}});let uid=await verifySession(req.headers.get('x-bos-session')||'',secret);if(!uid)uid=await verifyLaunch(req.headers.get('x-vk-launch-params')||'',secret);if(!uid)return json({ok:false,error:'Доступ не подтверждён'},401);const aq=await db.from('business_staff').select('*').eq('external_id',uid).eq('is_active',true).maybeSingle();if(aq.error)throw aq.error;let actor=aq.data;if(!actor)return json({ok:false,error:'Сотрудник не найден'},403);const f=await req.formData(),orderId=String(f.get('order_id')||''),token=String(f.get('upload_token')||''),kind=String(f.get('file_kind')||''),idx=Number(f.get('file_index')||0),acting=String(f.get('acting_master_vk_id')||'');if(actor.role==='owner'&&acting){const tq=await db.from('business_staff').select('*').eq('external_id',acting).eq('role','master').eq('is_active',true).maybeSingle();if(tq.error)throw tq.error;if(!tq.data)return json({ok:false,error:'Мастер не найден'},404);actor=tq.data}else if(actor.role!=='master')return json({ok:false,error:'Отчёт может загрузить только мастер'},403);if(!orderId||!token||!['act','photo'].includes(kind))return json({ok:false,error:'Некорректные параметры загрузки'},400);const oq=await db.from('orders').select('id,master_staff_id').eq('id',orderId).maybeSingle();if(oq.error)throw oq.error;if(!oq.data)return json({ok:false,error:'Заявка не найдена'},404);if(String(oq.data.master_staff_id||'')!==String(actor.id))return json({ok:false,error:'Эта заявка назначена другому мастеру'},403);const file=f.get('file');if(!(file instanceof File))return json({ok:false,error:'Файл не выбран'},400);const max=kind==='photo'?10*1024*1024:8*1024*1024;if(file.size>max)return json({ok:false,error:'Файл слишком большой'},413);const name=kind==='act'?`act_${safe(file.name||'act')}`:`photo_${idx}_${safe(file.name||'photo.jpg')}`,path=`orders/${orderId}/${safe(token)}/${name}`,buf=new Uint8Array(await file.arrayBuffer());const up=await db.storage.from(bucket).upload(path,buf,{contentType:file.type||'application/octet-stream',upsert:true});if(up.error)throw up.error;const sig=await db.storage.from(bucket).createSignedUrl(path,60*60*24*365);if(sig.error)throw sig.error;return json({ok:true,url:sig.data.signedUrl,size:file.size,name:file.name})}catch(e){return json({ok:false,error:e instanceof Error?e.message:String(e)},500)}});
