const {test,expect}=require('@playwright/test');
const {fullStack}=require('./helpers/full-stack.cjs');
test('slow and failed bootstrap retains owner values and DOM; success updates values',async({page})=>{
 const {db}=await fullStack(page,'owner');
 await page.goto('/');await expect(page.locator('#authGate')).toBeHidden();
 await page.waitForFunction(()=>!!window.BOS_ORDER_CONTROL&&!!window.BOS_REFRESH_NOW);
 await expect(page.locator('#ownerDashboard')).toBeVisible();
 await page.evaluate(()=>{window.__oldTable=document.querySelector('.odTable');window.__oldMetric=document.querySelector('[data-owner-kpi="masters"] strong');const base=api;window.__realApi=base;window.api=async(...args)=>{if(args[0]==='bootstrap'){await new Promise(r=>window.__releaseRefresh=r);if(window.__failRefresh)throw Error('offline')}return base(...args)};window.__pending=BOS_REFRESH_NOW()});
 await page.waitForFunction(()=>!!window.__releaseRefresh);
 await expect(page.locator('#ownerDashboard')).not.toHaveAttribute('aria-busy','true');
 await expect(page.locator('#bosOrderControlSummary')).not.toContainText('Загрузка');
 await expect(page.locator('#ownerDashboard .odRefreshState')).toBeHidden();
 await page.evaluate(()=>{window.__failRefresh=true;window.__releaseRefresh()});await page.evaluate(()=>window.__pending);
 await expect(page.locator('#ownerDashboard .odRefreshState')).toContainText('Не удалось');
 expect(await page.evaluate(()=>window.__oldTable===document.querySelector('.odTable'))).toBe(true);
 db.tables.orders[0].client='Изменённый клиент';
 await page.evaluate(()=>{window.api=window.__realApi;return BOS_REFRESH_NOW()});
 expect(await page.evaluate(()=>window.__oldTable===document.querySelector('.odTable'))).toBe(true);
 expect(await page.evaluate(()=>window.__oldMetric===document.querySelector('[data-owner-kpi="masters"] strong'))).toBe(true);
 await expect(page.locator('#ownerDashboard .odRefreshState')).toBeHidden();
});
test('real slow bootstrap never hides the control summary or dashboard; duplicate clicks share the refresh',async({page})=>{
 const {db}=await fullStack(page,'owner');
 await page.goto('/');await expect(page.locator('#authGate')).toBeHidden();await page.waitForFunction(()=>!!window.BOS_ORDER_CONTROL&&!!window.BOS_REFRESH_NOW);
 await expect(page.locator('#bosOrderControlSummary')).not.toContainText('Загрузка');
 let release,started;const start=new Promise(r=>started=r),gate=new Promise(r=>release=r);let calls=0;
 await page.route(/mini-app-api(?:\?|$)/,async route=>{if(route.request().postDataJSON()?.action!=='bootstrap')return route.fallback();calls++;started();await gate;return route.fallback()});
 await page.evaluate(()=>{window.__summary=document.querySelector('#bosOrderControlSummary');window.__table=document.querySelector('.odTable');window.__pending=BOS_REFRESH_NOW()});
 await start;await page.evaluate(()=>Promise.all([BOS_REFRESH_NOW(),BOS_REFRESH_NOW()]));
 await expect(page.locator('#bosOrderControlSummary')).not.toContainText('Загрузка');
 await expect(page.locator('#ownerDashboard')).not.toHaveAttribute('aria-busy','true');
 await expect(page.locator('#bosManualRefresh')).toBeDisabled();
 db.tables.orders[0].client='Новое имя';release();await page.evaluate(()=>window.__pending);
 expect(calls).toBe(1);
 expect(await page.evaluate(()=>window.__summary===document.querySelector('#bosOrderControlSummary'))).toBe(true);
 expect(await page.evaluate(()=>window.__table===document.querySelector('.odTable'))).toBe(true);
 await expect(page.locator('#bosManualRefresh')).toBeEnabled();
});
test('control cards and keyboard focus survive changed and failed background refreshes',async({page})=>{
 const {db}=await fullStack(page,'owner');await page.goto('/');await expect(page.locator('#authGate')).toBeHidden();
 await page.waitForFunction(()=>!!window.BOS_ORDER_CONTROL&&!!window.BOS_REFRESH_NOW);await page.evaluate(()=>BOS_ORDER_CONTROL.open());
 await expect(page.locator('[data-oc-order="12"]')).toBeVisible();
 await page.evaluate(()=>{window.__card=document.querySelector('[data-oc-order="12"]');window.__button=window.__card.querySelector('button');window.__button.focus()});
 db.tables.orders[1].client='Клиент после обновления';await page.evaluate(()=>BOS_REFRESH_NOW());await expect(page.locator('[data-oc-order="12"]')).toContainText('Клиент после обновления');
 expect(await page.evaluate(()=>window.__card.isConnected&&window.__button===document.activeElement)).toBe(true);
 await page.route(/mini-app-api(?:\?|$)/,route=>route.fulfill({status:503,body:'offline'}));await page.evaluate(()=>BOS_REFRESH_NOW());
 await expect(page.locator('#bosOrderControl')).toContainText('Не удалось обновить');
 expect(await page.evaluate(()=>window.__card.isConnected&&window.__button===document.activeElement)).toBe(true);
});
test('decorated order board retains cards, schedule, scroll and focus on background update',async({page})=>{
 await page.setViewportSize({width:1440,height:900});const {db}=await fullStack(page,'owner');Object.assign(db.tables.orders[0],{scheduled_date:new Date().toISOString().slice(0,10),scheduled_time:'12:00',time_slot:'12:00–13:00'});await page.goto('/');await expect(page.locator('#authGate')).toBeHidden();
 await page.locator('nav [data-page="orders"]').click();await expect(page.locator('.dh190Root')).toBeVisible();
 await page.evaluate(()=>{window.__assigned=document.querySelector('.dh190Card[data-order-id="11"]');window.__schedule=document.querySelector('.du187Root');window.__wrap=document.querySelector('.dh190GridWrap');window.__wrap.scrollLeft=140;window.__scroll=window.__wrap.scrollLeft;window.__card=document.querySelector('.dbOrderCard[data-order-id="12"]');window.__card.tabIndex=0;window.__card.focus()});
 db.tables.orders[0].client='Обновлённая Анна';db.tables.orders[1].client='Обновлённый Борис';await page.evaluate(()=>BOS_REFRESH_NOW());
 await expect(page.locator('.dbOrderCard[data-order-id="12"]')).toContainText('Обновлённый Борис');
 await expect(page.locator('.dh190Card[data-order-id="11"]')).toContainText('Обновлённая Анна');
 expect(await page.evaluate(()=>window.__assigned.isConnected)).toBe(true);
 await expect(page.locator('#bosOrderSearch')).toHaveCount(1);await expect(page.locator('.dbSchedule')).toHaveCount(1);
 await page.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));
 expect(await page.evaluate(()=>({schedule:window.__schedule.isConnected,card:window.__card.isConnected,focus:window.__card===document.activeElement,wrap:window.__wrap.isConnected,scroll:window.__wrap.scrollLeft===window.__scroll}))).toEqual({schedule:true,card:true,focus:true,wrap:true,scroll:true});
});
