const fs=require('node:fs');
const path=require('node:path');
const src=fs.readFileSync(path.join(__dirname,'..','dispatcher-horizontal-schedule-v190.js'),'utf8');
const pwa=fs.readFileSync(path.join(__dirname,'..','pwa-register.js'),'utf8');
if(!src.includes("version:'190'"))throw new Error('v190 marker missing');
if(!src.includes('Расписание дня'))throw new Error('horizontal title missing');
if(!src.includes('GRID_STEP=60,GRID_START=10*60,GRID_END=21*60'))throw new Error('fixed hourly timeline including 20:00 missing');
if(!src.includes('grid-template-columns:88px repeat(var(--dh190-times),minmax(76px,1fr))'))throw new Error('readable hourly grid missing');
if(!src.includes('startsInHour'))throw new Error('half-hour order placement support missing');
if(!src.includes('--dh190-offset'))throw new Error('within-hour card offset missing');
if(!src.includes('dh190Status-pending')||!src.includes('dh190Status-reschedule')||!src.includes('dh190Status-overdue')||!src.includes('dh190Status-done'))throw new Error('dispatcher status colors missing');
if(!src.includes('minmax(260px,300px)'))throw new Error('narrow detail panel layout missing');
if(!src.includes('--dh190-vh'))throw new Error('board-local viewport fit missing');
if(src.includes('html.dh190Active,body.dh190Active'))throw new Error('global page scroll lock must not be used');
if(!src.includes("window.BOS_PERMISSIONS.isDispatcherWorkspaceActive(st()?.user)"))throw new Error('dispatcher/owner/manager activation missing');
if(!pwa.includes("'./dispatcher-horizontal-schedule-v190.js'"))throw new Error('dispatcher module registration missing');
if(!pwa.includes('script.src=window.BOS_ASSET_URL(src)'))throw new Error('dispatcher module must use unified BUILD_ID asset URL');
if(pwa.includes('dispatcher-horizontal-schedule-v190.js?v='))throw new Error('manual dispatcher cache bust must not be used');
console.log('dispatcher horizontal schedule v190 source checks passed');
