const {test,expect}=require('@playwright/test');

test('mobile VK signed launch opens app and can create an order',async({page})=>{
  await page.setViewportSize({width:320,height:700});
  await page.route('https://unpkg.com/**',route=>route.fulfill({status:200,contentType:'application/javascript',body:`window.vkBridge={send:async()=>({})};`}));
  let sessionCalls=0,created=false;
  const sessionHandler=async route=>{sessionCalls++;const b=route.request().postDataJSON();expect(b.launch_params).toContain('vk_user_id=123456789');expect(b.access_token).toBeUndefined();await route.fulfill({status:200,contentType:'application/json',body:JSON.stringify({ok:true,session_token:'123456789.9999999999.testsignature'})})};
  await page.route('**/api/proxy/vk-session-api',sessionHandler);
  const owner={id:'owner1',vk_user_id:'123456789',external_id:'123456789',full_name:'Владелец',role:'owner',city:'Москва',is_active:true};
  const master={id:'m1',vk_user_id:'1001',external_id:'1001',full_name:'Мастер Тест',role:'master',city:'Москва',is_active:true};
  let orders=[];
  const miniAppHandler=async route=>{const req=route.request(),b=req.postDataJSON()||{},h=req.headers();if(!h['x-bos-session'])return route.fulfill({status:401,contentType:'application/json',body:JSON.stringify({ok:false,error:'Доступ не подтверждён'})});if(b.action==='bootstrap')return route.fulfill({status:200,contentType:'application/json',body:JSON.stringify({ok:true,user:owner,orders,users:[owner,master],masters:[master],masterSchedule:[],claims:[],sources:[{source:'VK'}],settings:{}})});if(b.action==='createOrder'){created=true;const o={...b,id:'99',amount:Number(b.original_amount||0),master_payout:1126.93};orders=[o];return route.fulfill({status:200,contentType:'application/json',body:JSON.stringify({ok:true,order:o})})}return route.fulfill({status:200,contentType:'application/json',body:JSON.stringify({ok:true})})};
  await page.route('**/api/proxy/mini-app-api',miniAppHandler);
  await page.route('**/api/proxy/order-meta-api',async route=>route.fulfill({status:200,contentType:'application/json',body:JSON.stringify({ok:true,order:{}})}));
  await page.goto('/?force_vk_auth=1&vk_app_id=54758847&vk_user_id=123456789&vk_language=ru&sign=signed_test_value',{waitUntil:'domcontentloaded'});
  await expect.poll(()=>sessionCalls,{timeout:15000}).toBe(1);
  await expect(page.getByText('Загруженность мастеров')).toBeVisible();
  await page.locator('nav button[data-page="orders"]').click();
  await page.getByRole('button',{name:/Новая/}).click();
  const form=page.locator('#orderForm');
  await form.locator('[name=client]').fill('Тест');
  await form.locator('#bosPhone').fill('9991234567');
  await form.locator('[name=master_vk_id]').selectOption('1001');
  await form.locator('[name=address]').fill('Адрес');
  await form.locator('#bosService').selectOption('4');
  await form.locator('[name=original_amount]').fill('3788');
  await expect(form.locator('#bosMasterPay')).toContainText('1 126,93');
  await form.getByRole('button',{name:'Сохранить'}).click();
  await expect.poll(()=>created).toBeTruthy();
});
