import copy
import hashlib
import importlib.util
import json
import os
from pathlib import Path
import tempfile
import unittest
from unittest.mock import patch

spec = importlib.util.spec_from_file_location('release', Path(__file__).resolve().parents[1] / 'scripts/ru-master-home-release.py')
r = importlib.util.module_from_spec(spec)
spec.loader.exec_module(r)

class ReleaseTests(unittest.TestCase):
    def setUp(self):
        self.tmp = tempfile.TemporaryDirectory()
        self.addCleanup(self.tmp.cleanup)
        self.root = Path(self.tmp.name) / 'frontend'
        self.root.mkdir()
        self.stage = Path(self.tmp.name) / 'backup'
        self.before = {n: ('// ' + n + '\n').encode() for n in r.SOURCES}
        self.after = {n: b'// updated\n' + data for n, data in self.before.items()}
        bundle = b'// prefix with RU routing preserved\n'
        for n in r.SOURCES[1:]:
            bundle += b'\n;\n// Source: ' + n.encode() + b'\n' + r.ru_source(self.before[n]) + b'\n'
        bundle += b'\n;\n// Source: unchanged.js\nconst API="https://139.100.237.167";\n'
        files = {r.SOURCES[0]: self.before[r.SOURCES[0]], 'startup-shell.bundle.js': bundle,
                 'index.html': ('<meta name="bos-build-id" content="' + r.BEFORE_BUILD + '"><script src="startup-shell.bundle.js?build=' + r.BEFORE_BUILD + '"></script>').encode(),
                 'sw.js': ("const BUILD_ID='" + r.BEFORE_BUILD + "';\n// existing SW behavior\n").encode(), 'unrelated.js': b'unchanged'}
        files.update({n: r.ru_source(self.before[n]) for n in r.SOURCES[1:]})
        meta = {'id': r.BEFORE_BUILD, 'shell': r.digest(files['index.html']), 'assets': {n: r.digest(files[n]) for n in (r.SOURCES[0], 'startup-shell.bundle.js', 'unrelated.js')}, 'assetBundles': {n: 'startup-shell.bundle.js' for n in r.SOURCES[1:]}}
        files['build-version.js'] = b'// Generated by npm run build. Do not edit.\nself.BOS_BUILD=' + json.dumps(meta, separators=(',', ':')).encode() + b';\n'
        for n, data in files.items():
            (self.root/n).write_bytes(data)
        self.original = {p.name:p.read_bytes() for p in self.root.iterdir()}

    def prepare(self):
        return r.prepare(self.root, self.before, self.after)

    def test_overlay_preserves_ru_routing_and_all_other_assets(self):
        old, new, build = self.prepare()
        self.assertNotEqual(build, r.BEFORE_BUILD)
        self.assertIn(b'const API="https://139.100.237.167"', new['startup-shell.bundle.js'])
        self.assertNotIn(b'obsropbslfwtanyspjbi', new['startup-shell.bundle.js'])
        self.assertEqual((self.root/'unrelated.js').read_bytes(), b'unchanged')
        meta = r.manifest(new['build-version.js'])
        self.assertEqual(meta['shell'], r.digest(new['index.html']))
        for name in (r.SOURCES[0], 'startup-shell.bundle.js'):
            self.assertEqual(meta['assets'][name], r.digest(new[name]))
        self.assertIn(build.encode(), new['sw.js'])
        self.assertEqual(self.original, {p.name:p.read_bytes() for p in self.root.iterdir()})

    def test_modified_module_is_rejected_even_with_valid_existing_manifest(self):
        self.before[r.SOURCES[1]] = b'// different baseline\n'
        with self.assertRaisesRegex(r.Stop, 'newer/different'):
            self.prepare()

    def test_corrupt_asset_is_rejected_before_writing(self):
        (self.root/'unrelated.js').write_bytes(b'drift')
        with self.assertRaisesRegex(r.Stop, 'incomplete or changed'):
            self.prepare()
        self.assertFalse(self.stage.exists())

    def test_symlink_is_rejected(self):
        p = self.root/'unrelated.js'
        target = Path(self.tmp.name)/'outside'
        target.write_bytes(b'unchanged')
        p.unlink();p.symlink_to(target)
        with self.assertRaisesRegex(r.Stop, 'symlinked'):
            self.prepare()

    def test_success_records_backup_and_can_rollback_exact_bytes(self):
        old,new,_ = self.prepare()
        calls=[]
        record=r.install(self.root,self.stage,old,new,'a'*40,lambda data:calls.append(data))
        self.assertEqual(record['status'],'deployed')
        self.assertEqual(len(calls),1)
        for name,data in new.items():self.assertEqual((self.root/name).read_bytes(),data)
        r.rollback(self.root,self.stage,record)
        self.assertEqual(record['status'],'rolled_back')
        self.assertEqual(self.original,{p.name:p.read_bytes() for p in self.root.iterdir()})

    def test_failed_public_probe_rolls_back_every_file(self):
        old,new,_=self.prepare()
        def fail(_):raise r.Stop('probe failed')
        with self.assertRaisesRegex(r.Stop,'probe failed'):
            r.install(self.root,self.stage,old,new,'a'*40,fail)
        self.assertEqual(self.original,{p.name:p.read_bytes() for p in self.root.iterdir()})
        self.assertEqual(json.loads((self.stage/'journal.json').read_text())['status'],'rolled_back')

    def test_interrupted_partial_install_restores_without_touching_unrelated_file(self):
        old,new,_=self.prepare()
        real=r.atomic
        def fail(path,data,*args,**kwargs):
            if path==self.root/'startup-shell.bundle.js' and data==new['startup-shell.bundle.js']:
                raise OSError('simulated disk error')
            return real(path,data,*args,**kwargs)
        with patch.object(r,'atomic',side_effect=fail):
            with self.assertRaises(OSError):r.install(self.root,self.stage,old,new,'a'*40,lambda _:None)
        self.assertEqual(self.original,{p.name:p.read_bytes() for p in self.root.iterdir()})

    def test_rollback_refuses_to_clobber_later_frontend_change(self):
        old,new,_=self.prepare()
        record=r.install(self.root,self.stage,old,new,'a'*40,lambda _:None)
        (self.root/'index.html').write_bytes(b'later unrelated release')
        with self.assertRaisesRegex(r.Stop,'outside this release'):
            r.rollback(self.root,self.stage,record)
        self.assertEqual((self.root/'index.html').read_bytes(),b'later unrelated release')

    def test_check_interrupted_journal_is_read_only(self):
        old,new,_=self.prepare()
        record=r.install(self.root,self.stage,old,new,'a'*40,lambda _:None)
        record['status']='installing'
        snapshot={p.name:p.read_bytes() for p in self.root.iterdir()}
        with patch.object(r,'rollback',side_effect=AssertionError('check must not write')):
            r.resume(self.root,self.stage,record,check=True)
        self.assertEqual(snapshot,{p.name:p.read_bytes() for p in self.root.iterdir()})

    def test_public_root_must_match_in_addition_to_versioned_index(self):
        _,new,build=self.prepare()
        def fake_get(url):
            if url==r.ORIGIN+'/':return b'stale root'
            name=url.split('/')[-1].split('?')[0]
            return new[name]
        with self.assertRaisesRegex(r.Stop,'entry'):
            r.verify_public(new,build,fake_get)

    def test_unsafe_asset_path_is_rejected(self):
        with self.assertRaises(r.Stop):r.local_file(self.root,'../outside')

if __name__=='__main__':unittest.main()
