import importlib.util
import json
from pathlib import Path
import tempfile
import unittest

ROOT = Path(__file__).resolve().parents[1]


def module(name, path):
    spec = importlib.util.spec_from_file_location(name, path)
    value = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(value)
    return value


release = module('review_release', ROOT / 'scripts/ru-report-review-release.py')
r = module('base_release', ROOT / 'scripts/ru-master-home-release.py')
release.configure(r)


class ReviewReleaseTests(unittest.TestCase):
    def setUp(self):
        self.tmp = tempfile.TemporaryDirectory()
        self.addCleanup(self.tmp.cleanup)
        self.root = Path(self.tmp.name) / 'frontend'
        self.root.mkdir()
        self.stage = Path(self.tmp.name) / 'backup'
        source = b'const API="https://obsropbslfwtanyspjbi.supabase.co";\n'
        sw = ("const BUILD_ID='" + '0' * 20 + "';\n" + ''.join(release.PAGES_ONLY) + "// original push/update behavior\nconst docNavigation='before';\n").encode()
        self.before = {'report-review-patch.js': source, 'sw.js': sw}
        self.after = {'report-review-patch.js': source + b'// intake date and image viewer\n', 'sw.js': sw.replace(b"docNavigation='before'", b"docNavigation='after'")}
        bundle = b'// RU network must remain unchanged\n;\n// Source: report-review-patch.js\n' + r.ru_source(source) + b'\n;\n// Source: unrelated.js\nconst unchanged=true;\n'
        html = ('<meta name="bos-build-id" content="' + release.BEFORE_BUILD + '"><script src="startup-shell.bundle.js?build=' + release.BEFORE_BUILD + '"></script>').encode()
        files = {'startup-shell.bundle.js': bundle, 'sw.js': release.ru_worker(r, sw, release.BEFORE_BUILD), 'index.html': html, 'report-review-patch.js': r.ru_source(source), 'unrelated.js': b'untouched'}
        meta = {'id': release.BEFORE_BUILD, 'shell': r.digest(html), 'assets': {n: r.digest(files[n]) for n in ('startup-shell.bundle.js', 'unrelated.js')}, 'assetBundles': {'report-review-patch.js': 'startup-shell.bundle.js'}}
        files['build-version.js'] = b'// Generated by npm run build. Do not edit.\nself.BOS_BUILD=' + json.dumps(meta, separators=(',', ':')).encode() + b';\n'
        for name, data in files.items():
            (self.root / name).write_bytes(data)
        self.snapshot = files

    def prepare(self):
        return release.prepare(r, self.root, self.before, self.after)

    def test_prepare_is_read_only_and_preserves_ru_routing_and_worker_features(self):
        old, new, build = self.prepare()
        self.assertNotEqual(build, release.BEFORE_BUILD)
        self.assertIn(b'https://139.100.237.167', new['startup-shell.bundle.js'])
        self.assertNotIn(b'obsropbslfwtanyspjbi', new['startup-shell.bundle.js'])
        self.assertIn(b'// original push/update behavior', new['sw.js'])
        self.assertIn(b"docNavigation='after'", new['sw.js'])
        self.assertNotIn(b'movedOrigin', new['sw.js'])
        self.assertEqual(self.snapshot, {p.name: p.read_bytes() for p in self.root.iterdir()})
        meta = r.manifest(new['build-version.js'])
        self.assertEqual(meta['shell'], r.digest(new['index.html']))
        self.assertEqual(meta['assets']['startup-shell.bundle.js'], r.digest(new['startup-shell.bundle.js']))
        self.assertEqual(meta['assets']['unrelated.js'], r.digest(b'untouched'))

    def test_worker_drift_stops_before_writes(self):
        with (self.root / 'sw.js').open('ab') as f:
            f.write(b'// parallel change')
        with self.assertRaisesRegex(r.Stop, 'different or newer'):
            self.prepare()
        self.assertFalse(self.stage.exists())

    def test_incomplete_asset_and_changed_report_module_stop(self):
        (self.root / 'unrelated.js').write_bytes(b'partial upload')
        with self.assertRaisesRegex(r.Stop, 'incomplete or changed'):
            self.prepare()
        (self.root / 'unrelated.js').write_bytes(b'untouched')
        self.before['report-review-patch.js'] = b'newer module'
        with self.assertRaisesRegex(r.Stop, 'newer/different'):
            self.prepare()

    def test_success_can_restore_exact_original_bytes_without_touching_other_assets(self):
        old, new, _ = self.prepare()
        record = r.install(self.root, self.stage, old, new, 'a' * 40, lambda _: None)
        self.assertEqual(record['status'], 'deployed')
        r.rollback(self.root, self.stage, record)
        self.assertEqual(self.snapshot, {p.name: p.read_bytes() for p in self.root.iterdir()})

    def test_failed_https_verification_rolls_back_worker_and_shell(self):
        old, new, _ = self.prepare()
        def fail(_):
            raise r.Stop('public verification failed')
        with self.assertRaisesRegex(r.Stop, 'public verification'):
            r.install(self.root, self.stage, old, new, 'a' * 40, fail)
        self.assertEqual(self.snapshot, {p.name: p.read_bytes() for p in self.root.iterdir()})


if __name__ == '__main__':
    unittest.main()
