import { createClient } from 'npm:@supabase/supabase-js@2';
const cors={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'content-type,x-bos-session,x-vk-launch-params','Access-Control-Allow-Methods':'POST,OPTIONS'};
const json=(x:any,s=200)=>new Response(JSON.stringify(x),{status:s,headers:{...cors,'Content-Type':'application/json'}});
function b64u(a:Uint8Array){let s='';for(const b of a)s+=String.fromCharCode(b);return btoa(s).replace(/=/g,'').replace(/\+/g,'-').replace(/\//g,'_')}
async function hmac(msg:string,secret:string){const key=await crypto.subtle.importKey('raw',new TextEncoder().encode(secret),{name:'HMAC',hash:'SHA-256'},false,['sign']);return b64u(new Uint8Array(await crypto.subtle.sign('HMAC',key,new TextEncoder().encode(msg))))}
async function verifySession(token:string,secret:string){const p=String(token||'').split('.');if(p.length!==3||!/^[A-Za-z0-9_-]{1,128}$/.test(p[0])||!/^[0-9]+$/.test(p[1]))return null;if(Number(p[1])<Math.floor(Date.now()/1000))return null;const exp=await hmac(`${p[0]}.${p[1]}`,secret);if(exp.length!==p[2].length)return null;let m=0;for(let i=0;i<exp.length;i++)m|=exp.charCodeAt(i)^p[2].charCodeAt(i);return m===0?p[0]:null}
async function verifyLaunch(raw:string,secret:string){if(!raw)return null;const p=new URLSearchParams(raw.startsWith('?')?raw.slice(1):raw),sign=p.get('sign'),app=p.get('vk_app_id'),uid=p.get('vk_user_id');if(!sign||app!=='54758847'||!uid||!/^[1-9]\d*$/.test(uid))return null;const c=[...p.entries()].filter(([k])=>k.startsWith('vk_')).sort(([a],[b])=>a.localeCompare(b)).map(([k,v])=>`${k}=${encodeURIComponent(v)}`).join('&'),exp=await hmac(c,secret);if(exp.length!==sign.length)return null;let m=0;for(let i=0;i<exp.length;i++)m|=exp.charCodeAt(i)^sign.charCodeAt(i);return m===0?uid:null}
async function makeSession(uid:string,secret:string){const exp=Math.floor(Date.now()/1000)+1800,msg=`${uid}.${exp}`;return `${msg}.${await hmac(msg,secret)}`}
Deno.serve(async(req)=>{if(req.method==='OPTIONS')return new Response('ok',{headers:cors});try{const body=await req.json();const url=Deno.env.get('SUPABASE_URL')!,key=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!,secret=Deno.env.get('VK_APP_SECRET')||'';if(!url||!key||!secret)throw new Error('Server configuration missing');const db=createClient(url,key,{auth:{persistSession:false}});const incoming=req.headers.get('x-bos-session')||'';let uid=await verifySession(incoming,secret);if(!uid)uid=await verifyLaunch(req.headers.get('x-vk-launch-params')||'',secret);if(!uid)return json({ok:false,error:'Доступ не подтверждён'},401);const aq=await db.from('business_staff').select('*').eq('external_id',uid).eq('is_active',true).maybeSingle();if(aq.error)throw aq.error;const actor=aq.data;if(!actor)return json({ok:false,error:'Сотрудник не найден'},403);let forwardSession=incoming;let session_token='';if(!forwardSession){forwardSession=await makeSession(uid,secret);session_token=forwardSession}
if(actor.role==='owner'){
 const targetId=String(body.acting_master_vk_id||'');if(!targetId)return json({ok:false,error:'В режиме просмотра выберите мастера'},403);
 const tq=await db.from('business_staff').select('*').eq('external_id',targetId).eq('role','master').eq('is_active',true).maybeSingle();if(tq.error)throw tq.error;if(!tq.data)return json({ok:false,error:'Мастер не найден'},404);
 const oq=await db.from('orders').select('id,master_staff_id').eq('id',String(body.order_id||'')).maybeSingle();if(oq.error)throw oq.error;if(!oq.data||String(oq.data.master_staff_id)!==String(tq.data.id))return json({ok:false,error:'Заявка не назначена выбранному мастеру'},403);
 forwardSession=await makeSession(String(tq.data.external_id),secret);
}else if(actor.role!=='master') return json({ok:false,error:'Отчёт может загрузить только мастер'},403);
const upstream=await fetch(`${url}/functions/v1/report-api`,{method:'POST',headers:{'Content-Type':'application/json','X-BOS-Session':forwardSession},body:JSON.stringify(body)});const text=await upstream.text();let out:any={};try{out=JSON.parse(text)}catch{}if(session_token&&out&&typeof out==='object')out.session_token=session_token;return new Response(JSON.stringify(out),{status:upstream.status,headers:{...cors,'Content-Type':'application/json'}})}catch(e){return json({ok:false,error:e instanceof Error?e.message:String(e)},500)}});
