import { createClient } from 'npm:@supabase/supabase-js@2';
const cors={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'content-type,apikey,authorization','Access-Control-Allow-Methods':'POST,OPTIONS'};
const out=(x:any,s=200)=>new Response(JSON.stringify(x),{status:s,headers:{...cors,'Content-Type':'application/json'}});
function b64u(bytes:Uint8Array){let s='';for(const b of bytes)s+=String.fromCharCode(b);return btoa(s).replace(/=/g,'').replace(/\+/g,'-').replace(/\//g,'_')}
async function hmac(msg:string,secret:string){const key=await crypto.subtle.importKey('raw',new TextEncoder().encode(secret),{name:'HMAC',hash:'SHA-256'},false,['sign']);return b64u(new Uint8Array(await crypto.subtle.sign('HMAC',key,new TextEncoder().encode(msg))))}
async function makeSession(uid:string,secret:string){const exp=Math.floor(Date.now()/1000)+43200,msg=`${uid}.${exp}`;return`${msg}.${await hmac(msg,secret)}`}
async function verifyLaunch(raw:string,secret:string){raw=String(raw||'').replace(/^\?/,'');if(!raw)return null;const p=new URLSearchParams(raw),sign=p.get('sign')||'',app=p.get('vk_app_id')||'',uid=p.get('vk_user_id')||'';if(!sign||app!=='54758847'||!/^[1-9]\d*$/.test(uid))return null;const ordered=new URLSearchParams();[...p.entries()].filter(([k])=>k.startsWith('vk_')).sort(([a],[b])=>a.localeCompare(b)).forEach(([k,v])=>ordered.append(k,v));const expected=await hmac(ordered.toString(),secret);if(expected.length!==sign.length)return null;let diff=0;for(let i=0;i<expected.length;i++)diff|=expected.charCodeAt(i)^sign.charCodeAt(i);if(diff!==0)return null;const ts=Number(p.get('vk_ts')||0);if(ts&&Math.abs(Math.floor(Date.now()/1000)-ts)>86400)return null;return uid}
async function uidFromToken(token:string){if(!token)return null;const r=await fetch(`https://api.vk.com/method/users.get?access_token=${encodeURIComponent(token)}&v=5.199`);const d=await r.json().catch(()=>({}));const uid=String(d?.response?.[0]?.id||'');return /^[1-9]\d*$/.test(uid)?{uid,profile:d.response[0]}:null}
Deno.serve(async req=>{if(req.method==='OPTIONS')return new Response('ok',{headers:cors});if(req.method!=='POST')return out({ok:false,error:'METHOD_NOT_ALLOWED'},405);try{const body=await req.json().catch(()=>({}));const url=Deno.env.get('SUPABASE_URL')!,key=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!,secret=Deno.env.get('VK_APP_SECRET')||'';if(!url||!key||!secret)throw new Error('Server configuration missing');let uid=await verifyLaunch(String(body.launch_params||''),secret),profile:any=null,method='launch';if(!uid){const t=await uidFromToken(String(body.access_token||'').trim());if(t){uid=t.uid;profile=t.profile;method='token'}}if(!uid)return out({ok:false,error:'Не удалось подтвердить аккаунт VK'},401);const db=createClient(url,key,{auth:{persistSession:false}});let q=await db.from('business_staff').select('*').eq('external_id',uid).eq('is_active',true).maybeSingle();if(q.error)throw q.error;const session_token=await makeSession(uid,secret);if(q.data)return out({ok:true,session_token,auth_method:method,user:{vk_user_id:q.data.external_id,full_name:q.data.full_name,role:q.data.role}});const owners=await db.from('business_staff').select('id').eq('role','owner').eq('is_active',true).limit(1);if(owners.error)throw owners.error;if(!(owners.data||[]).length){const full=[profile?.first_name,profile?.last_name].filter(Boolean).join(' ').trim()||'Владелец';const ins=await db.from('business_staff').insert({external_id:uid,full_name:full,role:'owner',phone:'',city:'Москва',is_active:true}).select().single();if(ins.error)throw ins.error;return out({ok:true,session_token,auth_method:method,user:{vk_user_id:uid,full_name:ins.data.full_name,role:'owner'},first_owner:true})}return out({ok:true,session_token,auth_method:method,registration_required:true,user_preview:{full_name:[profile?.first_name,profile?.last_name].filter(Boolean).join(' ').trim()}})}catch(e){return out({ok:false,error:e instanceof Error?e.message:String(e)},500)}});
