import { createClient } from 'npm:@supabase/supabase-js@2';
const cors={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'content-type,apikey,authorization,x-bos-session','Access-Control-Allow-Methods':'POST,OPTIONS'};
function b64u(bytes:Uint8Array){let s='';for(const b of bytes)s+=String.fromCharCode(b);return btoa(s).replace(/=/g,'').replace(/\+/g,'-').replace(/\//g,'_')}
async function hmac(msg:string,secret:string){const key=await crypto.subtle.importKey('raw',new TextEncoder().encode(secret),{name:'HMAC',hash:'SHA-256'},false,['sign']);return b64u(new Uint8Array(await crypto.subtle.sign('HMAC',key,new TextEncoder().encode(msg))))}
function validSubject(v:string){return /^[A-Za-z0-9_-]{1,128}$/.test(v)}
async function makeSession(uid:string,secret:string){if(!validSubject(uid))throw new Error('Invalid staff external id');const exp=Math.floor(Date.now()/1000)+43200,msg=`${uid}.${exp}`,sig=await hmac(msg,secret);return`${msg}.${sig}`}
async function verifySession(token:string,secret:string){const p=String(token||'').split('.');if(p.length!==3||!validSubject(p[0])||!/^[0-9]+$/.test(p[1]))return null;const exp=Number(p[1]);if(!Number.isFinite(exp)||exp<Math.floor(Date.now()/1000))return null;const expected=await hmac(`${p[0]}.${p[1]}`,secret);if(expected.length!==p[2].length)return null;let mismatch=0;for(let i=0;i<expected.length;i++)mismatch|=expected.charCodeAt(i)^p[2].charCodeAt(i);return mismatch===0?p[0]:null}
Deno.serve(async(req)=>{if(req.method==='OPTIONS')return new Response('ok',{headers:cors});const out=(x:any,s=200)=>new Response(JSON.stringify(x),{status:s,headers:{...cors,'Content-Type':'application/json'}});try{const url=Deno.env.get('SUPABASE_URL')!,key=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!,secret=Deno.env.get('VK_APP_SECRET')||'';if(!url||!key||!secret)throw new Error('Server configuration missing');const db=createClient(url,key,{auth:{persistSession:false}});const body=await req.json().catch(()=>({}));const action=String(body.action||'');if(action==='login'){const login=String(body.login||'').trim(),password=String(body.password||'');if(!login||!password)return out({ok:false,error:'Введите логин и пароль'},400);const vr=await db.rpc('bos_verify_staff_credentials',{p_login:login,p_password:password});if(vr.error)throw vr.error;const id=vr.data;if(!id)return out({ok:false,error:'Неверный логин или пароль'},401);const q=await db.from('business_staff').select('*').eq('id',id).eq('is_active',true).single();if(q.error)throw q.error;const uid=String(q.data.external_id||'');if(!validSubject(uid))return out({ok:false,error:'Некорректный идентификатор сотрудника. Обратитесь к владельцу.'},409);return out({ok:true,session_token:await makeSession(uid,secret),user:{id:q.data.id,full_name:q.data.full_name,role:q.data.role,phone:q.data.phone,city:q.data.city}})}
if(action==='setCredentials'){const uid=await verifySession(req.headers.get('x-bos-session')||'',secret);if(!uid)return out({ok:false,error:'Сессия истекла. Войдите снова.'},401);const q=await db.from('business_staff').select('id').eq('external_id',uid).eq('is_active',true).single();if(q.error)throw q.error;const login=String(body.login||'').trim(),password=String(body.password||'');const r=await db.rpc('bos_set_staff_credentials',{p_staff_id:q.data.id,p_login:login,p_password:password});if(r.error){const msg=String(r.error.message||'');if(msg.toLowerCase().includes('duplicate')||msg.includes('business_staff_login_unique'))return out({ok:false,error:'Такой логин уже занят'},409);throw r.error}return out({ok:true})}
return out({ok:false,error:'UNKNOWN_ACTION'},404)}catch(e){return out({ok:false,error:e instanceof Error?e.message:String(e)},500)}});
