const SPREADSHEET_ID='1lt3WoH6pRJkwsC5XbJi90wvbA9nYu9XqNIhJcKS6w_w';
const ORDER_HEADERS=['id','created_at','status','client','phone','address','work','scheduled_date','scheduled_time','master_vk_id','master_name','amount','source','city','comment','created_by_vk_id','request_id','master_payout'];
const STATUSES=['Новая','Назначена','В работе','Выполнена','Отменена'];
function doGet(e){const cb=safeCallback_(e.parameter.callback||'callback');let lock;try{const action=e.parameter.action||'bootstrap';if(action==='health')return jsonp_(cb,{ok:true,mode:'public-dev',version:'2026-09-09-5'});lock=LockService.getScriptLock();if(!lock.tryLock(10000))return jsonp_(cb,{ok:false,error:'BUSY'});ensureOrderHeaders_();const user={vk_user_id:'owner-local',full_name:'Илья',role:'owner',city:'Москва',is_active:true};const p=parsePayload_(e.parameter.payload);let r;if(action==='bootstrap')r=bootstrap_(user);else if(action==='createOrder')r=createOrder_(user,p);else if(action==='updateOrder')r=updateOrder_(user,p);else if(action==='addEmployee')r=addEmployee_(p);else if(action==='updateEmployee')r=updateEmployee_(p);else r={ok:false,error:'UNKNOWN_ACTION'};return jsonp_(cb,r)}catch(err){return jsonp_(cb,{ok:false,error:String(err&&err.message||err)})}finally{if(lock&&lock.hasLock()){try{SpreadsheetApp.flush()}finally{lock.releaseLock()}}}}
function ss_(){return SpreadsheetApp.openById(SPREADSHEET_ID)}function sheet_(n){const s=ss_().getSheetByName(n);if(!s)throw new Error('Sheet not found: '+n);return s}function rows_(n){const s=sheet_(n),v=s.getDataRange().getValues();if(!v.length)return[];const h=v[0].map(String);return v.slice(1).filter(r=>r.some(x=>x!==''&&x!==null)).map(r=>rowObject_(h,r))}
function ensureOrderHeaders_(){const s=sheet_('Orders');let h=s.getRange(1,1,1,Math.max(1,s.getLastColumn())).getValues()[0].map(String);ORDER_HEADERS.forEach(name=>{if(!h.includes(name)){s.getRange(1,h.length+1).setValue(name);h.push(name)}})}
function bootstrap_(u){return{ok:true,user:u,orders:rows_('Orders'),masters:rows_('Masters').filter(x=>truthy_(x.is_active)),sources:rows_('Sources').filter(x=>truthy_(x.is_active)),users:rows_('Users').filter(x=>truthy_(x.is_active)),settings:Object.fromEntries(rows_('Settings').map(x=>[String(x.key),x.value]))}}
function masterPayout_(amount){const n=Number(amount||0);return Math.round(n*0.85*0.65*100)/100}
function createOrder_(u,p){const s=sheet_('Orders'),h=s.getRange(1,1,1,s.getLastColumn()).getValues()[0].map(String);const master=masterById_(p.master_vk_id);const row={id:nextOrderId_(),created_at:new Date(),status:p.status&&STATUSES.includes(String(p.status))?String(p.status):(p.master_vk_id?'Назначена':'Новая'),client:p.client||'',phone:p.phone||'',address:p.address||'',work:p.work||'',scheduled_date:p.scheduled_date||'',scheduled_time:p.scheduled_time||'',master_vk_id:master?String(master.vk_user_id):'',master_name:master?String(master.full_name):'',amount:Number(p.amount||0),source:p.source||'VK',city:p.city||'Москва',comment:p.comment||'',created_by_vk_id:'owner-local',request_id:p.request_id||'',master_payout:master?masterPayout_(p.amount):0};normalizeOrder_(row);appendObject_(s,h,row);return{ok:true,order:row}}
function updateOrder_(u,p){const s=sheet_('Orders'),d=s.getDataRange().getValues(),h=d[0].map(String),ii=h.indexOf('id'),ri=d.findIndex((r,i)=>i>0&&String(r[ii])===String(p.id));if(ri<1)return{ok:false,error:'ORDER_NOT_FOUND'};const o=rowObject_(h,d[ri]);['status','client','phone','address','work','scheduled_date','scheduled_time','amount','source','city','comment'].forEach(k=>{if(Object.prototype.hasOwnProperty.call(p,k))o[k]=p[k]});if(Object.prototype.hasOwnProperty.call(p,'master_vk_id')){const m=masterById_(p.master_vk_id);o.master_vk_id=m?String(m.vk_user_id):'';o.master_name=m?String(m.full_name):''}normalizeOrder_(o);o.master_payout=o.master_vk_id?masterPayout_(o.amount):0;s.getRange(ri+1,1,1,h.length).setValues([h.map(k=>cellValue_(o[k]))]);return{ok:true,order:o}}
function normalizeOrder_(o){for(const k of ['client','address','work']){o[k]=String(o[k]||'').trim();if(!o[k])throw new Error('Заполните клиента, адрес и работу')}o.amount=Number(o.amount||0);if(!Number.isFinite(o.amount)||o.amount<0)throw new Error('Некорректная сумма');if(!STATUSES.includes(String(o.status)))o.status=o.master_vk_id?'Назначена':'Новая';if(!o.master_vk_id&&o.status==='Назначена')o.status='Новая';if(o.master_vk_id&&o.status==='Новая')o.status='Назначена'}
function masterById_(id){if(!id)return null;return rows_('Masters').find(m=>truthy_(m.is_active)&&String(m.vk_user_id)===String(id))||null}
function addEmployee_(p){const name=String(p.full_name||'').trim();if(!name)throw new Error('Укажите имя сотрудника');const us=sheet_('Users'),uh=us.getRange(1,1,1,us.getLastColumn()).getValues()[0].map(String);const role=['owner','manager','dispatcher','master'].includes(String(p.role))?String(p.role):'master';const id='staff_'+Utilities.getUuid().replace(/-/g,'').slice(0,12);const row={vk_user_id:id,full_name:name,role,city:String(p.city||'Москва').trim()||'Москва',is_active:true,phone:String(p.phone||''),comment:String(p.comment||'')};appendObject_(us,uh,row);if(role==='master')upsertMaster_(row,p);return{ok:true,user:row,master:role==='master'?masterById_(id):null}}
function updateEmployee_(p){const id=String(p.vk_user_id||'');const s=sheet_('Users'),d=s.getDataRange().getValues(),h=d[0].map(String),ii=h.indexOf('vk_user_id'),ri=d.findIndex((r,i)=>i>0&&String(r[ii])===id);if(ri<1)return{ok:false,error:'USER_NOT_FOUND'};const o=rowObject_(h,d[ri]);['full_name','phone','city','role','is_active','comment'].forEach(k=>{if(Object.prototype.hasOwnProperty.call(p,k))o[k]=p[k]});s.getRange(ri+1,1,1,h.length).setValues([h.map(k=>cellValue_(o[k]))]);if(String(o.role)==='master'&&truthy_(o.is_active))upsertMaster_(o,p);return{ok:true,user:o}}
function upsertMaster_(u,p){const s=sheet_('Masters'),d=s.getDataRange().getValues(),h=d[0].map(String),ii=h.indexOf('vk_user_id'),ri=d.findIndex((r,i)=>i>0&&String(r[ii])===String(u.vk_user_id));const m={vk_user_id:String(u.vk_user_id),full_name:u.full_name||'',phone:u.phone||'',city:u.city||'Москва',specialization:String(p.specialization||''),is_active:true,work_start:String(p.work_start||'09:00'),work_end:String(p.work_end||'18:00')};if(ri>0)s.getRange(ri+1,1,1,h.length).setValues([h.map(k=>cellValue_(m[k]))]);else appendObject_(s,h,m)}
function nextOrderId_(){const ids=rows_('Orders').map(x=>Number(String(x.id).replace(/\D/g,''))).filter(Number.isFinite);return'З-'+String((ids.length?Math.max.apply(null,ids):1000)+1)}function appendObject_(s,h,o){s.appendRow(h.map(k=>cellValue_(o[k])))}function tz_(){try{return String(ss_().getSpreadsheetTimeZone()||'Europe/Moscow')}catch(e){return'Europe/Moscow'}}function rowObject_(h,r){return Object.fromEntries(h.map((k,i)=>{let v=r[i];if(v instanceof Date){if(k==='scheduled_date')v=Utilities.formatDate(v,tz_(),'yyyy-MM-dd');else if(k==='scheduled_time')v=Utilities.formatDate(v,tz_(),'HH:mm');else v=Utilities.formatDate(v,'GMT',"yyyy-MM-dd'T'HH:mm:ss'Z'")}return[k,v]}))}function cellValue_(v){return typeof v==='string'&&/^[=+@-]/.test(v)?"'"+v:(v??'')}function truthy_(v){return v===true||String(v).toLowerCase()==='true'||String(v)==='1'}function parsePayload_(raw){if(!raw)return{};try{return JSON.parse(raw)}catch(e){try{return JSON.parse(decodeURIComponent(raw))}catch(_){throw new Error('BAD_PAYLOAD')}}}function safeCallback_(v){return/^[A-Za-z_$][0-9A-Za-z_$\.]*$/.test(v)?v:'callback'}function jsonp_(cb,obj){return ContentService.createTextOutput(cb+'('+JSON.stringify(obj)+');').setMimeType(ContentService.MimeType.JAVASCRIPT)}