const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const root=path.resolve(__dirname,'..');
const bundles=require('./bundle-assets.cjs')(root);
const hash=s=>crypto.createHash('sha256').update(s).digest('hex');
const assetExt=/\.(?:js|css|svg|webmanifest|png|jpe?g|webp|ico|woff2?)$/i;
const files=[...new Set([...fs.readdirSync(root).filter(n=>(assetExt.test(n)||n.endsWith('.html'))&&n!=='build-version.js'&&fs.statSync(path.join(root,n)).isFile()),...Object.keys(bundles.output)])].sort();
const readInput=name=>Object.hasOwn(bundles.output,name)?Buffer.from(bundles.output[name]):fs.readFileSync(path.join(root,name));
function versionHTML(text,id){
 text=text.replace(/name="bos-build-id" content="[^"]*"/,`name="bos-build-id" content="${id}"`);
 return text.replace(/\b(src|href)="([^\"]+)"/g,(attribute,key,value)=>{
  if(/^(?:[a-z]+:|\/\/|#)/i.test(value))return attribute;
  const [base,fragment]=value.split('#');const [name,query='']=base.split('?');
  if(!assetExt.test(name))return attribute;
  const params=new URLSearchParams(query.replaceAll('&amp;','&'));
  for(const key of ['v','_sw','build'])params.delete(key);
  params.set('build',id);
  return `${key}="${name}?${params.toString().replaceAll('&','&amp;')}${fragment?'#'+fragment:''}"`;
 });
}
function normalized(name,data){
 if(name==='sw.js')return Buffer.from(data.toString().replace(/const BUILD_ID='[^']*';/,"const BUILD_ID='BUILD';"));
 if(name==='index.html')return Buffer.from(versionHTML(bundles.html(data.toString()),'BUILD'));
 return data;
}
const input=crypto.createHash('sha256');
for(const name of files){input.update(name+'\0');input.update(normalized(name,readInput(name)));input.update('\0')}
const id=input.digest('hex').slice(0,20);
const output={
 ...bundles.output,
 'index.html':versionHTML(bundles.html(fs.readFileSync(path.join(root,'index.html'),'utf8')),id),
 'sw.js':fs.readFileSync(path.join(root,'sw.js'),'utf8').replace(/const BUILD_ID='[^']*';/,`const BUILD_ID='${id}';`)
};
const assets={};
for(const name of files.filter(n=>n!=='sw.js'&&!n.endsWith('.html')&&!Object.hasOwn(bundles.assetBundles,n)))assets[name]=hash(readInput(name));
output['build-version.js']='// Generated by npm run build. Do not edit.\nself.BOS_BUILD='+JSON.stringify({id,shell:hash(output['index.html']),assets,assetBundles:bundles.assetBundles})+';\n';
let stale=false;
for(const [name,text] of Object.entries(output)){
 if(!fs.existsSync(path.join(root,name))||fs.readFileSync(path.join(root,name),'utf8')!==text){
  if(process.argv.includes('--check')){console.error('Stale build artifact: '+name);stale=true}else fs.writeFileSync(path.join(root,name),text);
 }
}
if(stale){console.error('Run npm run build before committing.');process.exit(1)}
console.log('BUILD_ID='+id);
