const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const root=path.resolve(__dirname,'..');
const hash=s=>crypto.createHash('sha256').update(s).digest('hex');
const files=fs.readdirSync(root).filter(n=>/\.(js|css|svg|webmanifest|html)$/.test(n)&&n!=='build-version.js').sort();
function normalized(name,text){
 if(name==='sw.js')return text.replace(/const BUILD_ID='[^']*';/,"const BUILD_ID='BUILD';");
 if(name==='index.html')return text.replace(/name="bos-build-id" content="[^"]*"/,'name="bos-build-id" content="BUILD"').replace(/([?&]build=)[a-f0-9]+/g,'$1BUILD');
 return text;
}
const id=hash(files.map(n=>n+'\0'+normalized(n,fs.readFileSync(path.join(root,n),'utf8'))).join('\0')).slice(0,20);
const output={};
for(const name of ['index.html','sw.js']){
 let text=fs.readFileSync(path.join(root,name),'utf8');
 text=name==='sw.js'?text.replace(/const BUILD_ID='[^']*';/,`const BUILD_ID='${id}';`):text.replace(/name="bos-build-id" content="[^"]*"/,`name="bos-build-id" content="${id}"`).replace(/([?&]build=)[A-Za-z0-9]+/g,'$1'+id);
 output[name]=text;
}
const assets={};
for(const name of files.filter(n=>n!=='sw.js'&&n!=='index.html'&&!n.endsWith('.html')))assets[name]=hash(output[name]??fs.readFileSync(path.join(root,name)));
output['build-version.js']='// Generated by npm run build. Do not edit.\nself.BOS_BUILD='+JSON.stringify({id,assets})+';\n';
let stale=false;
for(const [name,text] of Object.entries(output)){
 if(!fs.existsSync(path.join(root,name))||fs.readFileSync(path.join(root,name),'utf8')!==text){
  if(process.argv.includes('--check')){console.error('Stale build artifact: '+name);stale=true}else fs.writeFileSync(path.join(root,name),text);
 }
}
if(stale){console.error('Run npm run build before committing.');process.exit(1)}
console.log('BUILD_ID='+id);
