#!/usr/bin/env python3
"""Report photo release using the existing guarded RU frontend installer.

Run on the existing Docker host. The reviewed application commit is pinned.
No containers are restarted; no backend, database or credentials are changed.
"""
import argparse
import copy
import fcntl
import hashlib
import json
import os
from pathlib import Path
import re
import stat
import subprocess
import sys
import tempfile
from urllib.request import Request, urlopen

ORIGIN = 'https://139.100.237.167'
BASE = '4d49c701a8f6346f4e95fc7a05d0396c0bb8e5dc'
BEFORE_BUILD = 'a566a9503a680dd018d5'
SOURCES = ('report-review.css', 'master-report-patch.js', 'report-review-patch.js', 'report-chunk-upload-v23.js', 'master-report-ui-v12.js', 'master-order-hands-layout-v72.js')
RUNTIME = ('report-review.css', 'startup-shell.bundle.js', 'index.html', 'build-version.js', 'sw.js')
ALLOWED = set(SOURCES + RUNTIME)

class Stop(Exception):
    pass

def digest(data):
    return hashlib.sha256(data).hexdigest()

def get(url):
    with urlopen(Request(url, headers={'Cache-Control': 'no-cache'}), timeout=25) as response:
        if response.status != 200:
            raise Stop('HTTPS check failed')
        data = response.read(4_000_001)
        if len(data) > 4_000_000:
            raise Stop('Unexpected response size')
        return data

def manifest(data):
    match = re.fullmatch(rb'// Generated by npm run build\. Do not edit\.\nself\.BOS_BUILD=(\{.*\});\n', data, re.S)
    if not match:
        raise Stop('Unknown build manifest format')
    value = json.loads(match.group(1))
    if not re.fullmatch(r'[0-9a-f]{20}', value.get('id', '')) or not isinstance(value.get('assets'), dict):
        raise Stop('Invalid build manifest')
    return value

def local_file(root, name):
    if not re.fullmatch(r'[A-Za-z0-9_.-]+', name) or name in ('.', '..'):
        raise Stop('Unsafe frontend filename')
    p = root / name
    if p.is_symlink() or not p.is_file() or p.resolve().parent != root.resolve():
        raise Stop('Missing, symlinked or unsafe frontend file: ' + name)
    if p.stat().st_size > 4_000_000:
        raise Stop('Unexpected local file size')
    return p

def ru_source(data):
    return data.replace(b'https://obsropbslfwtanyspjbi.supabase.co', ORIGIN.encode()).replace(b'https://business-os-api-gateway.netlify.app/api/proxy/report-api', (ORIGIN + '/api/proxy/report-api').encode())

def replace_module(bundle, name, before, after):
    marker = b'// Source: ' + name.encode() + b'\n'
    if bundle.count(marker) != 1:
        raise Stop('Unknown bundle module: ' + name)
    start = bundle.index(marker) + len(marker)
    end = bundle.find(b'\n;\n// Source:', start)
    if end < 0:
        raise Stop('Missing module boundary')
    body = bundle[start:end]
    if body.rstrip() != before.rstrip():
        raise Stop('Live module has newer/different fixes: ' + name)
    return bundle[:start] + after.rstrip() + body[len(body.rstrip()):] + bundle[end:]

def prepare(root, before_sources, after_sources):
    old = {name: local_file(root, name).read_bytes() for name in RUNTIME}
    meta = manifest(old['build-version.js'])
    if meta['id'] != BEFORE_BUILD:
        raise Stop('Production build changed; inspect it before preparing a new release')
    if digest(old['index.html']) != meta['shell']:
        raise Stop('Current shell does not match its manifest')
    for name, expected in meta['assets'].items():
        if digest(local_file(root, name).read_bytes()) != expected:
            raise Stop('Current frontend is incomplete or changed: ' + name)
    if old[SOURCES[0]].rstrip() != before_sources[SOURCES[0]].rstrip():
        raise Stop('Live report stylesheet contains other changes')
    new = {SOURCES[0]: after_sources[SOURCES[0]]}
    bundle = old['startup-shell.bundle.js']
    for name in SOURCES[1:]:
        before, after = ru_source(before_sources[name]), ru_source(after_sources[name])
        bundle = replace_module(bundle, name, before, after)
        # Keep an existing source checkout consistent without inventing new files.
        if (root / name).exists():
            data = local_file(root, name).read_bytes()
            if data.rstrip() != before.rstrip():
                raise Stop('Source differs from reviewed live module: ' + name)
            old[name], new[name] = data, after
    new['startup-shell.bundle.js'] = bundle
    build = digest((meta['id'] + ''.join(name + digest(new[name]) for name in sorted(new))).encode())[:20]
    new['index.html'] = old['index.html'].replace(meta['id'].encode(), build.encode())
    if new['index.html'] == old['index.html']:
        raise Stop('Missing HTML build markers')
    token = ("const BUILD_ID='" + meta['id'] + "';").encode()
    if old['sw.js'].count(token) != 1:
        raise Stop('Unknown service-worker version marker')
    new['sw.js'] = old['sw.js'].replace(token, ("const BUILD_ID='" + build + "';").encode())
    updated = copy.deepcopy(meta)
    updated['id'], updated['shell'] = build, digest(new['index.html'])
    for name, data in new.items():
        if name in updated['assets']:
            updated['assets'][name] = digest(data)
    new['build-version.js'] = b'// Generated by npm run build. Do not edit.\nself.BOS_BUILD=' + json.dumps(updated, ensure_ascii=False, separators=(',', ':')).encode() + b';\n'
    return old, new, build

def atomic(path, data, mode=0o600, uid=None, gid=None):
    fd, name = tempfile.mkstemp(prefix='.bos-release-', dir=path.parent)
    try:
        with os.fdopen(fd, 'wb') as out:
            out.write(data)
            out.flush()
            os.fchmod(out.fileno(), mode)
            if uid is not None:
                os.fchown(out.fileno(), uid, gid)
            os.fsync(out.fileno())
        os.replace(name, path)
        directory = os.open(path.parent, os.O_RDONLY)
        try:
            os.fsync(directory)
        finally:
            os.close(directory)
    finally:
        if os.path.exists(name):
            os.unlink(name)

def save_journal(stage, record):
    atomic(stage / 'journal.json', json.dumps(record, ensure_ascii=False).encode())

def rollback(root, stage, record):
    # A concurrent unrelated change must never be overwritten by rollback.
    for name, entry in record['files'].items():
        if name not in ALLOWED or digest(local_file(root, name).read_bytes()) not in (entry['before'], entry['after']):
            raise Stop('Rollback stopped: a frontend file changed outside this release')
        if digest((stage / name).read_bytes()) != entry['before']:
            raise Stop('Rollback backup is invalid')
    for name, entry in reversed(list(record['files'].items())):
        atomic(root / name, (stage / name).read_bytes(), entry['mode'], entry['uid'], entry['gid'])
    record['status'] = 'rolled_back'
    save_journal(stage, record)

def install(root, stage, old, new, revision, verify):
    stage.mkdir(mode=0o700, parents=True, exist_ok=False)
    record = {'root': str(root), 'revision': revision, 'status': 'prepared', 'files': {}}
    for name, data in old.items():
        info = local_file(root, name).stat()
        if digest(local_file(root, name).read_bytes()) != digest(data):
            raise Stop('Frontend changed during preparation')
        atomic(stage / name, data)
        record['files'][name] = {'before': digest(data), 'after': digest(new[name]), 'mode': stat.S_IMODE(info.st_mode), 'uid': info.st_uid, 'gid': info.st_gid}
    record['status'] = 'installing'
    save_journal(stage, record)
    # Runtime files first; manifest last. Existing verified PWA cache stays valid.
    order = [n for n in new if n not in ('index.html', 'sw.js', 'build-version.js')] + ['index.html', 'sw.js', 'build-version.js']
    try:
        for name in order:
            entry = record['files'][name]
            if digest(local_file(root, name).read_bytes()) != entry['before']:
                raise Stop('Concurrent frontend change')
            atomic(root / name, new[name], entry['mode'], entry['uid'], entry['gid'])
        verify(new)
        record['status'] = 'deployed'
        save_journal(stage, record)
    except BaseException:
        rollback(root, stage, record)
        raise
    return record

def verify_public(files, build, fetch=get):
    for name, data in files.items():
        if name in RUNTIME and fetch(ORIGIN + '/' + name + '?build=' + build) != data:
            raise Stop('Published file failed exact HTTPS verification: ' + name)
    if fetch(ORIGIN + '/') != files['index.html']:
        raise Stop('Published entry point differs from the new shell')

def resume(root, stage, record, check=False, rollback_requested=False):
    if check:
        print('BOS_REPORT_PHOTO_RELEASE_STATUS=' + record['status'] + '; read-only, no recovery performed')
        return
    if rollback_requested or record['status'] == 'installing':
        rollback(root, stage, record)
        print('BOS_REPORT_PHOTO_ROLLED_BACK; data untouched')
        return
    if record['status'] == 'deployed':
        files = {}
        for name, entry in record['files'].items():
            if name not in ALLOWED:
                raise Stop('Unknown release file')
            data = local_file(root, name).read_bytes()
            if digest(data) != entry['after']:
                raise Stop('Previously deployed version is no longer current')
            files[name] = data
        meta = manifest(files['build-version.js'])
        verify_public(files, meta['id'])
        print('BOS_REPORT_PHOTO_DEPLOYED BUILD_ID=' + meta['id'])
        return
    raise Stop('This release was rolled back; inspect before any new deployment')


def discover(public_manifest):
    ids = subprocess.run(['docker', 'ps', '-q'], check=True, capture_output=True, text=True, timeout=20).stdout.split()
    if not ids:
        raise Stop('No running release containers')
    containers = json.loads(subprocess.run(['docker', 'inspect', *ids], check=True, capture_output=True, text=True, timeout=20).stdout)
    candidates = set()
    for container in containers:
        for mount in container.get('Mounts', []):
            if mount.get('Type') != 'bind':
                continue
            source = Path(mount['Source']).resolve()
            if not source.is_relative_to(Path('/opt/business-os')) or not source.is_dir():
                continue
            for suffix in ('', 'public', 'frontend', 'www', 'app'):
                root = (source / suffix).resolve()
                p = root / 'build-version.js'
                if p.is_file() and not p.is_symlink() and p.read_bytes() == public_manifest:
                    candidates.add(root)
    if len(candidates) != 1:
        raise Stop('Cannot uniquely identify the active frontend mount; no changes made')
    return candidates.pop()

def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--revision', default='a639db4dea71e605446c166ec96ca5af8abacc1a', choices=['a639db4dea71e605446c166ec96ca5af8abacc1a'])
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument('--check', action='store_true')
    mode.add_argument('--rollback', action='store_true')
    args = parser.parse_args()
    if not re.fullmatch('[0-9a-f]{40}', args.revision):
        raise Stop('A full immutable reviewed Git commit is required')
    parent = Path('/opt/business-os/deploy')
    if not parent.is_dir():
        raise Stop('Existing release directory not found')
    with (parent / '.master-home-release.lock').open('a') as lock:
        fcntl.flock(lock, fcntl.LOCK_EX | fcntl.LOCK_NB)
        stage = parent / ('report-photo-' + args.revision)
        if (stage / 'journal.json').exists():
            record = json.loads((stage / 'journal.json').read_text())
            root = Path(record['root']).resolve()
            if record['revision'] != args.revision or not root.is_relative_to(Path('/opt/business-os')):
                raise Stop('Release recovery identity differs')
            resume(root, stage, record, check=args.check, rollback_requested=args.rollback)
            return
        if args.rollback:
            raise Stop('No backup for this revision')
        public = get(ORIGIN + '/build-version.js')
        root = discover(public)
        before, after = {}, {}
        for name in SOURCES:
            prefix = 'https://raw.githubusercontent.com/zuev1ilya11-afk/business-os-vk/'
            before[name] = get(prefix + BASE + '/' + name)
            after[name] = get(prefix + args.revision + '/' + name)
        old, new, build = prepare(root, before, after)
        if get(ORIGIN + '/') != old['index.html']:
            raise Stop('HTTPS shell and selected mount differ')
        print('BOS_REPORT_PHOTO_PREPARED BUILD_ID=' + build)
        if args.check:
            return
        install(root, stage, old, new, args.revision, lambda files: verify_public(files, build))
        print('BOS_REPORT_PHOTO_DEPLOYED BUILD_ID=' + build)
        print('BACKUP=' + str(stage))
        print('Frontend bytes verified. Authenticated master/device smoke remains separate.')

if __name__ == '__main__':
    try:
        main()
    except Exception as error:
        print('BOS_REPORT_PHOTO_STOPPED: ' + (str(error) if isinstance(error, Stop) else type(error).__name__))
        sys.exit(1)
