#!/usr/bin/env python3
"""Deploy only report review and the document-navigation SW fix on the RU host.

Reuse the existing reviewed frontend installer. No service restarts or DB writes.
"""
import argparse
import copy
import fcntl
import hashlib
import importlib.util
import json
from pathlib import Path
import re
import sys
import tempfile
from urllib.request import Request, urlopen

BASE = 'cedbe408deec0447c4e2a9c29286d48aa34a73d3'
BEFORE_BUILD = '5fc09a8174db824cf6d4'
PREFIX = 'https://raw.githubusercontent.com/zuev1ilya11-afk/business-os-vk/'
HELPER_HASH = '50f0ed32a8a4cd9d66a7a7ee081a6dacd5e651715de714c1c09479069a2ab760'
SOURCES = ('report-review-patch.js', 'sw.js')
RUNTIME = ('startup-shell.bundle.js', 'index.html', 'sw.js', 'build-version.js')
# These Pages-only migration lines are absent from the deployed RU worker.
PAGES_ONLY = (
    "// The Cloud database is read-only after cutover. Retire only its old Pages entry.\n",
    "const movedOrigin=scope.origin==='https://zuev1ilya11-afk.github.io'&&scope.pathname==='/business-os-vk/'?'https://139.100.237.167/':'';\n",
    " if(movedOrigin){await self.skipWaiting();return}\n",
    " // Preserve drafts/caches in open tabs; their existing update banner offers reload.\n",
    " if(movedOrigin){await self.clients.claim();return}\n",
    " if(movedOrigin){const url=new URL(request.url);return Response.redirect(movedOrigin+url.search+url.hash,302)}\n",
)


def installer(folder):
    with urlopen(Request(PREFIX + BASE + '/scripts/ru-master-home-release.py'), timeout=25) as response:
        data = response.read(50_001)
    if hashlib.sha256(data).hexdigest() != HELPER_HASH:
        raise RuntimeError('Installer digest mismatch')
    path = Path(folder) / 'installer.py'
    path.write_bytes(data)
    spec = importlib.util.spec_from_file_location('bos_frontend_installer', path)
    r = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(r)
    configure(r)
    return r


def configure(r):
    r.RUNTIME = RUNTIME
    r.ALLOWED = set(SOURCES + RUNTIME)


def ru_worker(r, data, build):
    for line in PAGES_ONLY:
        if data.count(line.encode()) != 1:
            raise r.Stop('Unknown Pages-only worker baseline')
        data = data.replace(line.encode(), b'')
    data, count = re.subn(rb"const BUILD_ID='[0-9a-f]{20}';", ("const BUILD_ID='" + build + "';").encode(), data)
    if count != 1:
        raise r.Stop('Unknown worker build marker')
    return data


def prepare(r, root, before, after):
    old = {n: r.local_file(root, n).read_bytes() for n in RUNTIME}
    meta = r.manifest(old['build-version.js'])
    if meta['id'] != BEFORE_BUILD or r.digest(old['index.html']) != meta['shell']:
        raise r.Stop('Production build changed; no changes made')
    for name, digest in meta['assets'].items():
        if r.digest(r.local_file(root, name).read_bytes()) != digest:
            raise r.Stop('Current frontend is incomplete or changed: ' + name)
    if old['sw.js'] != ru_worker(r, before['sw.js'], meta['id']):
        raise r.Stop('Worker contains a different or newer change')
    name = 'report-review-patch.js'
    old_module, new_module = r.ru_source(before[name]), r.ru_source(after[name])
    new = {'startup-shell.bundle.js': r.replace_module(old['startup-shell.bundle.js'], name, old_module, new_module),
           'sw.js': ru_worker(r, after['sw.js'], meta['id'])}
    if (root / name).exists():
        old[name] = r.local_file(root, name).read_bytes()
        if old[name].rstrip() != old_module.rstrip():
            raise r.Stop('Report review source contains a different change')
        new[name] = new_module
    build = r.digest((meta['id'] + ''.join(n + r.digest(new[n]) for n in sorted(new))).encode())[:20]
    new['index.html'] = old['index.html'].replace(meta['id'].encode(), build.encode())
    if new['index.html'] == old['index.html']:
        raise r.Stop('Missing shell version markers')
    new['sw.js'] = new['sw.js'].replace(("const BUILD_ID='" + meta['id'] + "';").encode(), ("const BUILD_ID='" + build + "';").encode())
    updated = copy.deepcopy(meta)
    updated['id'], updated['shell'] = build, r.digest(new['index.html'])
    for name, data in new.items():
        if name in updated['assets']:
            updated['assets'][name] = r.digest(data)
    new['build-version.js'] = b'// Generated by npm run build. Do not edit.\nself.BOS_BUILD=' + json.dumps(updated, ensure_ascii=False, separators=(',', ':')).encode() + b';\n'
    return old, new, build


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--revision', required=True)
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument('--check', action='store_true')
    mode.add_argument('--rollback', action='store_true')
    args = parser.parse_args()
    if not re.fullmatch('[0-9a-f]{40}', args.revision):
        raise ValueError('Use a full reviewed commit SHA')
    parent = Path('/opt/business-os/deploy')
    if not parent.is_dir():
        raise ValueError('Existing release directory not found')
    with tempfile.TemporaryDirectory(prefix='bos-review-installer-') as folder:
        r = installer(folder)
        with (parent / '.master-home-release.lock').open('a') as lock:
            fcntl.flock(lock, fcntl.LOCK_EX | fcntl.LOCK_NB)
            stage = parent / ('report-review-' + args.revision)
            if (stage / 'journal.json').exists():
                record = json.loads((stage / 'journal.json').read_text())
                root = Path(record['root']).resolve()
                if record['revision'] != args.revision or not root.is_relative_to(Path('/opt/business-os')):
                    raise r.Stop('Release recovery identity differs')
                r.resume(root, stage, record, check=args.check, rollback_requested=args.rollback)
                return
            if args.rollback:
                raise r.Stop('No backup for this revision')
            public = r.get(r.ORIGIN + '/build-version.js')
            root = r.discover(public)
            before = {n: r.get(PREFIX + BASE + '/' + n) for n in SOURCES}
            after = {n: r.get(PREFIX + args.revision + '/' + n) for n in SOURCES}
            old, new, build = prepare(r, root, before, after)
            if r.get(r.ORIGIN + '/') != old['index.html']:
                raise r.Stop('Public shell and selected mount differ')
            print('BOS_REPORT_REVIEW_PREPARED BUILD_ID=' + build)
            if args.check:
                return
            r.install(root, stage, old, new, args.revision, lambda files: r.verify_public(files, build))
            print('BOS_REPORT_REVIEW_DEPLOYED BUILD_ID=' + build)
            print('BACKUP=' + str(stage))
            print('Accept the existing app update prompt before checking acts; backend and DB untouched.')


if __name__ == '__main__':
    try:
        main()
    except Exception as error:
        # Never echo network URLs, query tokens or arbitrary exception details.
        print('BOS_REPORT_REVIEW_STOPPED=' + type(error).__name__)
        sys.exit(1)
