-- These assertions exercise the exact migration twice, not a JavaScript queue simulation.
SELECT pg_temp.check_contract((SELECT count(*)=1 FROM bos_push_private.runtime),'one runtime on repeat migration');
SELECT pg_temp.check_contract((SELECT NOT enabled FROM bos_push_private.runtime),'safe disabled default');
SELECT pg_temp.check_contract(NOT has_table_privilege('anon','public.bos_push_subscriptions','SELECT'),'anon cannot read subscriptions');
SELECT pg_temp.check_contract(NOT has_table_privilege('authenticated','public.bos_push_deliveries','SELECT'),'authenticated cannot read queue');
SELECT pg_temp.check_contract(NOT has_schema_privilege('authenticated','bos_push_private','USAGE'),'private schema not exposed');
SELECT pg_temp.check_contract(NOT EXISTS(SELECT FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace WHERE (n.nspname='bos_push_private' OR (n.nspname='public' AND p.proname LIKE 'bos_push_%')) AND (has_function_privilege('anon',p.oid,'EXECUTE') OR has_function_privilege('authenticated',p.oid,'EXECUTE'))),'all push RPCs are service-only');
SELECT pg_temp.check_contract((SELECT bool_and(relrowsecurity) FROM pg_class WHERE oid IN ('public.bos_push_subscriptions'::regclass,'public.bos_push_deliveries'::regclass,'bos_push_private.runtime'::regclass)),'RLS enabled');
SET LOCAL ROLE service_role;
SELECT public.bos_push_subscribe(id,external_id,'https://fcm.googleapis.com/fcm/send/'||external_id,repeat('a',87),repeat('b',22),repeat('c',64)) FROM public.business_staff WHERE is_active;
RESET ROLE;
SELECT pg_temp.check_contract((SELECT count(*)=4 FROM public.bos_push_subscriptions),'four separate devices');
CREATE TEMP TABLE saved_binding AS SELECT id,binding_id FROM public.bos_push_subscriptions;
SELECT public.bos_push_subscribe(id,external_id,'https://fcm.googleapis.com/fcm/send/'||external_id,repeat('a',87),repeat('b',22),repeat('c',64)) FROM public.business_staff WHERE is_active;
SELECT pg_temp.check_contract((SELECT bool_and(s.binding_id=b.binding_id) FROM public.bos_push_subscriptions s JOIN saved_binding b USING(id)),'idempotent subscription preserves binding');
SELECT pg_temp.check_contract((public.bos_push_subscribe('00000000-0000-4000-8000-000000000004','staff_master2','https://fcm.googleapis.com/fcm/send/staff_master1',repeat('a',87),repeat('b',22),repeat('d',64))->>'conflict')::boolean,'endpoint hijack rejected');
INSERT INTO public.orders(id,status,master_staff_id) VALUES(1,'В работе','00000000-0000-4000-8000-000000000003');
SELECT pg_temp.check_contract((SELECT count(*)=0 FROM public.bos_push_deliveries),'no queue while disabled');
UPDATE bos_push_private.runtime SET enabled=true;
INSERT INTO public.orders(id,status,master_staff_id) VALUES(2,'В работе','00000000-0000-4000-8000-000000000003');
SELECT pg_temp.check_contract((SELECT count(*)=3 FROM public.bos_push_deliveries),'new order goes to operations and assigned master only');
UPDATE public.orders SET master_staff_id=master_staff_id,status=status WHERE id=2;
SELECT pg_temp.check_contract((SELECT count(*)=3 FROM public.bos_push_deliveries),'repeated no-op update creates no duplicates');
UPDATE public.orders SET scheduled_time='12:00' WHERE id=2;
SELECT pg_temp.check_contract((SELECT count(*)=1 FROM public.bos_push_deliveries WHERE event_type='rescheduled'),'one schedule event');
UPDATE public.orders SET master_staff_id='00000000-0000-4000-8000-000000000004' WHERE id=2;
SELECT pg_temp.check_contract((SELECT count(*)=6 FROM public.bos_push_deliveries),'reassignment notifies both affected masters');
SET LOCAL ROLE service_role;
SELECT public.bos_push_claim();
RESET ROLE;
SELECT pg_temp.check_contract((SELECT public.bos_push_delivery(d.id,d.lease_token) IS NULL FROM public.bos_push_deliveries d JOIN public.bos_push_subscriptions s ON s.id=d.subscription_id WHERE d.event_type='assigned' AND s.external_id='staff_master1'),'stale assignment cannot leak');
SELECT pg_temp.check_contract((SELECT public.bos_push_delivery(d.id,d.lease_token)->'order_id'='null'::jsonb FROM public.bos_push_deliveries d WHERE event_type='unassigned'),'unassigned notification omits protected order ID');
SELECT pg_temp.check_contract((SELECT public.bos_push_delivery(d.id,d.lease_token)->>'order_id'='2' FROM public.bos_push_deliveries d JOIN public.bos_push_subscriptions s ON s.id=d.subscription_id WHERE d.event_type='assigned' AND s.external_id='staff_master2'),'current assignment can send');
UPDATE public.business_staff SET is_active=false WHERE external_id='staff_master2';
SELECT pg_temp.check_contract((SELECT public.bos_push_delivery(d.id,d.lease_token) IS NULL FROM public.bos_push_deliveries d JOIN public.bos_push_subscriptions s ON s.id=d.subscription_id WHERE d.event_type='assigned' AND s.external_id='staff_master2'),'staff deactivation checked immediately before sending');
UPDATE public.business_staff SET is_active=true,role='manager' WHERE external_id='staff_master2';
SELECT pg_temp.check_contract((SELECT public.bos_push_delivery(d.id,d.lease_token) IS NULL FROM public.bos_push_deliveries d JOIN public.bos_push_subscriptions s ON s.id=d.subscription_id WHERE d.event_type='assigned' AND s.external_id='staff_master2'),'role changes invalidate old events');
UPDATE public.business_staff SET role='master' WHERE external_id='staff_master2';
UPDATE public.orders SET report_review_status='pending',report_uploaded_at=now() WHERE id=2;
SELECT pg_temp.check_contract((SELECT count(*)=2 FROM public.bos_push_deliveries WHERE event_type='report_pending'),'pending reports to operations only');
UPDATE public.orders SET report_review_status='pending',report_uploaded_at=report_uploaded_at WHERE id=2;
SELECT pg_temp.check_contract((SELECT count(*)=2 FROM public.bos_push_deliveries WHERE event_type='report_pending'),'repeat pending state is idempotent');
UPDATE public.orders SET report_review_status='rejected' WHERE id=2;
SELECT pg_temp.check_contract((SELECT count(*)=1 FROM public.bos_push_deliveries WHERE event_type='report_rejected'),'rejection goes to assigned master');
UPDATE public.orders SET status='Отменена' WHERE id=2;
SELECT pg_temp.check_contract((SELECT count(*)=1 FROM public.bos_push_deliveries WHERE event_type='cancelled'),'cancellation recorded once');
SELECT public.bos_push_revoke('https://fcm.googleapis.com/fcm/send/staff_master2',repeat('d',64));
SELECT pg_temp.check_contract((SELECT active FROM public.bos_push_subscriptions WHERE external_id='staff_master2'),'wrong capability cannot revoke');
SELECT public.bos_push_revoke('https://fcm.googleapis.com/fcm/send/staff_master2',repeat('c',64));
SELECT pg_temp.check_contract((SELECT NOT active FROM public.bos_push_subscriptions WHERE external_id='staff_master2'),'logout capability revokes device');
SELECT public.bos_push_subscribe('00000000-0000-4000-8000-000000000004','staff_master2','https://fcm.googleapis.com/fcm/send/staff_master2',repeat('a',87),repeat('b',22),repeat('e',64));
SELECT pg_temp.check_contract((SELECT s.binding_id<>b.binding_id FROM public.bos_push_subscriptions s JOIN saved_binding b USING(id) WHERE s.external_id='staff_master2'),'reconnection rotates binding');
SELECT pg_temp.check_contract((SELECT public.bos_push_delivery(d.id,d.lease_token) IS NULL FROM public.bos_push_deliveries d JOIN public.bos_push_subscriptions s ON s.id=d.subscription_id WHERE d.event_type='assigned' AND s.external_id='staff_master2'),'old binding cannot deliver after reconnection');
TRUNCATE public.bos_push_deliveries;
SELECT public.bos_push_test('00000000-0000-4000-8000-000000000001','https://fcm.googleapis.com/fcm/send/100',repeat('c',64));
SELECT pg_temp.check_contract((public.bos_push_test('00000000-0000-4000-8000-000000000001','https://fcm.googleapis.com/fcm/send/100',repeat('c',64))->>'limited')::boolean,'test rate limit atomic');
SELECT pg_temp.check_contract((SELECT count(*)=1 FROM public.bos_push_deliveries),'rate-limited test creates no duplicate');
SELECT public.bos_push_claim();
SELECT public.bos_push_finish(id,gen_random_uuid(),201,false) FROM public.bos_push_deliveries;
SELECT pg_temp.check_contract((SELECT state='sending' FROM public.bos_push_deliveries),'wrong lease cannot acknowledge');
SELECT public.bos_push_finish(id,lease_token,503,true) FROM public.bos_push_deliveries;
SELECT pg_temp.check_contract((SELECT state='pending' AND attempts=1 AND next_attempt_at>=now()+interval '30 seconds' FROM public.bos_push_deliveries),'transient failure is bounded and deferred');
UPDATE public.bos_push_deliveries SET next_attempt_at=now(),attempts=4;
SELECT public.bos_push_claim();
SELECT public.bos_push_finish(id,lease_token,503,true) FROM public.bos_push_deliveries;
SELECT pg_temp.check_contract((SELECT state='discarded' AND attempts=5 FROM public.bos_push_deliveries),'retry limit is five attempts');
TRUNCATE public.bos_push_deliveries;
INSERT INTO public.bos_push_deliveries(event_id,subscription_id,binding_id,event_type) SELECT gen_random_uuid(),s.id,s.binding_id,'test' FROM public.bos_push_subscriptions s CROSS JOIN generate_series(1,15) WHERE external_id='100';
SELECT pg_temp.check_contract(jsonb_array_length(public.bos_push_claim())=12,'worker claims at most twelve');
SELECT pg_temp.check_contract(jsonb_array_length(public.bos_push_claim())=3,'simultaneous claim excludes leases');
SELECT public.bos_push_finish(id,lease_token,410,false) FROM public.bos_push_deliveries LIMIT 1;
SELECT pg_temp.check_contract((SELECT NOT active FROM public.bos_push_subscriptions WHERE external_id='100'),'provider 410 deactivates subscription');
UPDATE public.bos_push_deliveries SET expires_at=now()-interval '1 second';
SELECT pg_temp.check_contract(jsonb_array_length(public.bos_push_claim())=0,'expired events never claimed');
SELECT pg_temp.check_contract((SELECT bool_and(state='discarded') FROM public.bos_push_deliveries),'expired events discarded');
-- An isolated queue failure must not cancel the business update.
ALTER TABLE public.bos_push_deliveries ADD CONSTRAINT push_test_failure CHECK(false) NOT VALID;
UPDATE public.orders SET scheduled_time='14:00' WHERE id=1;
SELECT pg_temp.check_contract((SELECT scheduled_time='14:00'::time FROM public.orders WHERE id=1),'queue error cannot roll back order');
ALTER TABLE public.bos_push_deliveries DROP CONSTRAINT push_test_failure;
SELECT pg_temp.check_contract((SELECT count(*)=2 FROM public.orders),'business rows preserved');
ROLLBACK;
