import { createClient } from 'npm:@supabase/supabase-js@2';
const cors={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'content-type,apikey,authorization,x-vk-launch-params,x-bos-session','Access-Control-Allow-Methods':'GET,POST,OPTIONS'};
const json=(x:any,s=200)=>new Response(JSON.stringify(x),{status:s,headers:{...cors,'Content-Type':'application/json'}});
function b64u(bytes:Uint8Array){let s='';for(const b of bytes)s+=String.fromCharCode(b);return btoa(s).replace(/=/g,'').replace(/\+/g,'-').replace(/\//g,'_')}
async function hmac(msg:string,secret:string){const key=await crypto.subtle.importKey('raw',new TextEncoder().encode(secret),{name:'HMAC',hash:'SHA-256'},false,['sign']);return b64u(new Uint8Array(await crypto.subtle.sign('HMAC',key,new TextEncoder().encode(msg))))}
async function verifyLaunch(raw:string,secret:string){if(!raw)return null;const p=new URLSearchParams(raw.startsWith('?')?raw.slice(1):raw),sign=p.get('sign'),app=p.get('vk_app_id'),uid=p.get('vk_user_id');if(!sign||app!=='54758847'||!uid||!/^[1-9]\d*$/.test(uid))return null;const canonical=[...p.entries()].filter(([k])=>k.startsWith('vk_')).sort(([a],[b])=>a.localeCompare(b)).map(([k,v])=>`${k}=${encodeURIComponent(v)}`).join('&');const expected=await hmac(canonical,secret);if(expected.length!==sign.length)return null;let mismatch=0;for(let i=0;i<expected.length;i++)mismatch|=expected.charCodeAt(i)^sign.charCodeAt(i);return mismatch===0?uid:null}
async function verifySession(token:string,secret:string){const p=String(token||'').split('.');if(p.length!==3||!/^[1-9]\d*$/.test(p[0])||!/^[0-9]+$/.test(p[1]))return null;const exp=Number(p[1]);if(!Number.isFinite(exp)||exp<Math.floor(Date.now()/1000))return null;const expected=await hmac(`${p[0]}.${p[1]}`,secret);if(expected.length!==p[2].length)return null;let mismatch=0;for(let i=0;i<expected.length;i++)mismatch|=expected.charCodeAt(i)^p[2].charCodeAt(i);return mismatch===0?p[0]:null}
async function authActor(db:any,req:Request){const secret=Deno.env.get('VK_APP_SECRET')||'';if(!secret)throw new Error('VK_APP_SECRET missing');let uid=await verifySession(req.headers.get('x-bos-session')||'',secret);if(!uid)uid=await verifyLaunch(req.headers.get('x-vk-launch-params')||'',secret);if(!uid)return null;const q=await db.from('business_staff').select('*').eq('external_id',uid).eq('is_active',true).maybeSingle();if(q.error)throw q.error;return q.data||null}
async function token(c:any){const r=await fetch('https://api.avito.ru/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({grant_type:'client_credentials',client_id:c.client_id,client_secret:c.client_secret})});const d=await r.json().catch(()=>({}));if(!r.ok||!d.access_token)throw new Error(d?.error_description||d?.message||'Ошибка авторизации Авито');return String(d.access_token)}
async function get(path:string,t:string){const r=await fetch('https://api.avito.ru'+path,{headers:{Authorization:`Bearer ${t}`,'User-Agent':'BusinessOS/1.1'}}),d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d?.error?.message||d?.message||`Avito HTTP ${r.status}`);return d}
async function post(path:string,t:string,b:any){const r=await fetch('https://api.avito.ru'+path,{method:'POST',headers:{Authorization:`Bearer ${t}`,'Content-Type':'application/json','User-Agent':'BusinessOS/1.1'},body:JSON.stringify(b)}),d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d?.error?.message||d?.message||`Avito HTTP ${r.status}`);return d}
function txt(v:any){if(!v)return'';if(typeof v==='string')return v;return String(v.text||v.value||v.content||'')}
function item(c:any){const v=c?.context?.value||c?.context||c?.item||{};return{id:String(v.id||v.item_id||''),title:String(v.title||c?.title||'Заявка с Авито'),url:String(v.url||v.item_url||'')}}
function client(c:any,uid:string){const us=Array.isArray(c?.users)?c.users:[],o=us.find((u:any)=>String(u?.id||u?.user_id||'')!==uid);return String(o?.name||o?.display_name||'Клиент Авито')}
function ts(v:any){const n=Number(v||0);return n?new Date(n>1e12?n:n*1000).toISOString():null}
async function conn(db:any){const q=await db.from('avito_connections').select('*').eq('id',1).eq('is_active',true).maybeSingle();if(q.error)throw q.error;if(!q.data)throw new Error('Авито не подключено');return q.data}
async function sync(db:any,c:any){const t=await token(c),data=await get(`/messenger/v2/accounts/${c.avito_user_id}/chats?limit=100&offset=0&chat_types=u2i`,t),chats=Array.isArray(data?.chats)?data.chats:[];let created=0,updated=0;for(const ch of chats){const cid=String(ch?.id||'');if(!cid)continue;const it=item(ch),last=ch?.last_message||{},lastText=txt(last?.content)||txt(last),lastAt=ts(last?.created||ch?.updated||ch?.created),unread=Number(ch?.unread_count??ch?.unread??0)||0,ext=`avito_chat_${cid}`;const patch:any={client:client(ch,String(c.avito_user_id)),work:it.title,source:'Авито',comment:lastText,source_updated_at:lastAt||new Date().toISOString(),updated_at:new Date().toISOString(),avito_chat_id:cid,avito_item_id:it.id||null,avito_item_url:it.url||null,avito_unread_count:unread,avito_last_message_at:lastAt};const q=await db.from('orders').select('id').eq('external_source','avito').eq('external_id',ext).maybeSingle();if(q.error)throw q.error;if(q.data){const r=await db.from('orders').update(patch).eq('id',q.data.id);if(r.error)throw r.error;updated++}else{const r=await db.from('orders').insert({...patch,phone:'',address:'Авито',status:'В работе',amount:0,original_amount:0,city:'Санкт-Петербург',external_source:'avito',external_id:ext,sync_status:'synced'});if(r.error)throw r.error;created++}}const now=new Date().toISOString();await db.from('avito_connections').update({last_sync_at:now,last_error:null,updated_at:now}).eq('id',1);return{count:chats.length,created,updated,last_sync_at:now}}
Deno.serve(async(req)=>{if(req.method==='OPTIONS')return new Response('ok',{headers:cors});try{const db=createClient(Deno.env.get('SUPABASE_URL')!,Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!,{auth:{persistSession:false}}),u=new URL(req.url),hook=u.searchParams.get('webhook_secret');if(hook){const q=await db.from('avito_connections').select('*').eq('id',1).eq('is_active',true).eq('webhook_secret',hook).maybeSingle();if(!q.data)return json({ok:false},403);const task=sync(db,q.data).catch(()=>{});try{(globalThis as any).EdgeRuntime?.waitUntil?.(task)}catch(_){}return json({ok:true})}const b=req.method==='POST'?await req.json().catch(()=>({})):{};const a=String(b.action||'status'),actor=await authActor(db,req);if(!actor)return json({ok:false,error:'Доступ не подтверждён'},401);if(!['owner','manager','dispatcher'].includes(String(actor.role||'')))return json({ok:false,error:'Недостаточно прав'},403);
if(a==='status'){const q=await db.from('avito_connections').select('avito_user_id,account_name,is_active,connected_at,last_sync_at,last_error').eq('id',1).maybeSingle();return json({ok:true,connected:!!q.data?.is_active,connection:q.data||null})}
if(a==='sync'){return json({ok:true,...await sync(db,await conn(db))})}
if(a==='messages'){const c=await conn(db),t=await token(c),chat=encodeURIComponent(String(b.chat_id||''));if(!chat)return json({ok:false,error:'Не указан чат'},400);const d=await get(`/messenger/v3/accounts/${c.avito_user_id}/chats/${chat}/messages/?limit=50&offset=0`,t);const arr=Array.isArray(d?.messages)?d.messages:Array.isArray(d)?d:[];const messages=arr.map((m:any)=>({id:String(m?.id||''),text:txt(m?.content)||txt(m),created_at:ts(m?.created),direction:String(m?.author_id||m?.user_id||'')===String(c.avito_user_id)?'out':'in',type:String(m?.type||'text')}));return json({ok:true,messages})}
if(a==='sendMessage'){const text=String(b.text||'').trim(),chat=String(b.chat_id||'');if(!chat||!text)return json({ok:false,error:'Введите сообщение'},400);const c=await conn(db),t=await token(c);await post(`/messenger/v1/accounts/${c.avito_user_id}/chats/${encodeURIComponent(chat)}/messages`,t,{message:{text}});await db.from('orders').update({avito_unread_count:0,avito_last_message_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq('avito_chat_id',chat);return json({ok:true})}
if(a==='read'){const chat=String(b.chat_id||'');if(!chat)return json({ok:false,error:'Не указан чат'},400);const c=await conn(db),t=await token(c);try{await post(`/messenger/v1/accounts/${c.avito_user_id}/chats/${encodeURIComponent(chat)}/read`,t,{})}catch(_){}await db.from('orders').update({avito_unread_count:0,updated_at:new Date().toISOString()}).eq('avito_chat_id',chat);return json({ok:true})}
if(a==='connect'){if(actor.role!=='owner')return json({ok:false,error:'Только владелец может подключать Авито'},403);const client_id=String(b.client_id||'').trim(),client_secret=String(b.client_secret||'').trim();if(!client_id||!client_secret)return json({ok:false,error:'Укажите Client ID и Client Secret'},400);const t=await token({client_id,client_secret}),me=await get('/core/v1/accounts/self',t),uid=Number(me?.id);if(!uid)return json({ok:false,error:'Не удалось определить аккаунт'},400);const secret=crypto.randomUUID().replace(/-/g,''),hookUrl=`${Deno.env.get('SUPABASE_URL')}/functions/v1/avito-api?webhook_secret=${secret}`;await post('/messenger/v3/webhook',t,{url:hookUrl});const now=new Date().toISOString();await db.from('avito_connections').upsert({id:1,client_id,client_secret,avito_user_id:uid,account_name:String(me?.name||`Avito ${uid}`),is_active:true,webhook_secret:secret,connected_at:now,last_error:null,updated_at:now},{onConflict:'id'});return json({ok:true,connected:true,...await sync(db,{client_id,client_secret,avito_user_id:uid})})}
if(a==='disconnect'){if(actor.role!=='owner')return json({ok:false,error:'Только владелец может отключать Авито'},403);await db.from('avito_connections').update({is_active:false,updated_at:new Date().toISOString()}).eq('id',1);return json({ok:true,connected:false})}return json({ok:false,error:'UNKNOWN_ACTION'},404)}catch(e){return json({ok:false,error:e instanceof Error?e.message:String(e)},500)}});
