-- Correct payouts that were generated by the previous master formula:
-- amount * 0.85 * 0.35. Preserve manually adjusted payouts by only
-- touching rows whose stored value matches the old formula within 1 kopeck.
update public.orders
set master_payout = round((coalesce(amount, 0)::numeric * 0.85 * 0.65), 2),
    updated_at = now()
where master_staff_id is not null
  and abs(
    coalesce(master_payout, 0)::numeric
    - round((coalesce(amount, 0)::numeric * 0.85 * 0.35), 2)
  ) <= 0.01;
