import { createClient } from 'npm:@supabase/supabase-js@2';
const cors={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'content-type,apikey,authorization,x-vk-launch-params,x-bos-session','Access-Control-Allow-Methods':'POST,OPTIONS'};const json=(x:any,s=200)=>new Response(JSON.stringify(x),{status:s,headers:{...cors,'Content-Type':'application/json'}});const privileged=(r:any)=>['owner','manager','dispatcher'].includes(String(r||''));function b64u(a:Uint8Array){let s='';for(const b of a)s+=String.fromCharCode(b);return btoa(s).replace(/=/g,'').replace(/\+/g,'-').replace(/\//g,'_')}async function hmac(msg:string,secret:string){const key=await crypto.subtle.importKey('raw',new TextEncoder().encode(secret),{name:'HMAC',hash:'SHA-256'},false,['sign']);return b64u(new Uint8Array(await crypto.subtle.sign('HMAC',key,new TextEncoder().encode(msg))))}async function verifyLaunch(raw:string,secret:string){if(!raw)return null;const p=new URLSearchParams(raw.startsWith('?')?raw.slice(1):raw),sign=p.get('sign'),app=p.get('vk_app_id'),uid=p.get('vk_user_id');if(!sign||app!=='54758847'||!uid||!/^[1-9]\d*$/.test(uid))return null;const c=[...p.entries()].filter(([k])=>k.startsWith('vk_')).sort(([a],[b])=>a.localeCompare(b)).map(([k,v])=>`${k}=${encodeURIComponent(v)}`).join('&'),exp=await hmac(c,secret);if(exp.length!==sign.length)return null;let m=0;for(let i=0;i<exp.length;i++)m|=exp.charCodeAt(i)^sign.charCodeAt(i);return m===0?uid:null}async function verifySession(token:string,secret:string){const p=String(token||'').split('.');if(p.length!==3||!/^[A-Za-z0-9_-]{1,128}$/.test(p[0])||!/^[0-9]+$/.test(p[1]))return null;if(Number(p[1])<Math.floor(Date.now()/1000))return null;const exp=await hmac(`${p[0]}.${p[1]}`,secret);if(exp.length!==p[2].length)return null;let m=0;for(let i=0;i<exp.length;i++)m|=exp.charCodeAt(i)^p[2].charCodeAt(i);return m===0?p[0]:null}async function makeSession(uid:string,secret:string){const exp=Math.floor(Date.now()/1000)+43200,msg=`${uid}.${exp}`;return`${msg}.${await hmac(msg,secret)}`}
async function allRows(query:any){
  const data:any[]=[];
  for(let offset=0;;offset+=1000){
    const page=await query.range(offset,offset+999);
    if(page.error)return page;
    data.push(...(page.data||[]));
    if((page.data||[]).length<1000)return {data,error:null};
  }
}

Deno.serve(async(req)=>{if(req.method==='OPTIONS')return new Response('ok',{headers:cors});try{const url=Deno.env.get('SUPABASE_URL')!,key=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!,secret=Deno.env.get('VK_APP_SECRET')||'';const db=createClient(url,key,{auth:{persistSession:false}});let uid=await verifySession(req.headers.get('x-bos-session')||'',secret),session_token='';if(!uid){uid=await verifyLaunch(req.headers.get('x-vk-launch-params')||'',secret);if(uid)session_token=await makeSession(uid,secret)}if(!uid)return json({ok:false,error:'Доступ не подтверждён'},401);const aq=await db.from('business_staff').select('*').eq('external_id',uid).eq('is_active',true).maybeSingle();if(aq.error)throw aq.error;const actor=aq.data;if(!actor)return json({ok:false,error:'Сотрудник не найден'},403);const b=await req.json();const action=b.action;
if(action==='bootstrap'){let cq=db.from('order_claims').select('*').order('opened_at',{ascending:false}).order('id'),oq=db.from('orders').select('*').order('created_at',{ascending:false}).order('id');if(actor.role==='master'){cq=cq.eq('master_staff_id',actor.id);oq=oq.eq('master_staff_id',actor.id)}const [c,o,s]=await Promise.all([allRows(cq),allRows(oq),allRows(db.from('business_staff').select('*').eq('role','master').order('id'))]);for(const r of [c,o,s])if(r.error)throw r.error;const map=new Map((s.data||[]).map((x:any)=>[String(x.id),x]));const claims=(c.data||[]).map((x:any)=>({...x,master_id:x.master_staff_id?(map.get(String(x.master_staff_id))?.external_id||x.master_staff_id):x.master_id}));const orders=(o.data||[]).map((x:any)=>{const m=x.master_staff_id?map.get(String(x.master_staff_id)):null;const out:any={...x,id:String(x.id),master_vk_id:m?.external_id||'',master_name:x.master_name||m?.full_name||''};if(actor.role==='master'){delete out.amount;delete out.original_amount;delete out.manager_payout;delete out.dispatcher_payout}return out});return json({ok:true,session_token:session_token||undefined,claims,orders})}
if(action==='reopenClaim'){if(!privileged(actor.role))return json({ok:false,error:'FORBIDDEN'},403);const reason=String(b.reason||'').trim();if(!reason)return json({ok:false,error:'Укажите причину претензии'},400);const q=await db.from('orders').select('*').eq('id',b.id).single();if(q.error)throw q.error;const o=q.data;if(o.status!=='Выполнена')return json({ok:false,error:'Претензию можно открыть только по выполненной заявке'},409);if(!o.master_staff_id)return json({ok:false,error:'У заявки нет назначенного мастера'},409);const pay=!!b.pay_revisit,amount=pay?Math.max(0,Number(b.revisit_payment||0)):0;if(pay&&amount<=0)return json({ok:false,error:'Укажите сумму оплаты повторного выезда'},400);const ins=await db.from('order_claims').insert({order_id:o.id,master_staff_id:o.master_staff_id,reason,required_work:String(b.required_work||''),scheduled_date:b.scheduled_date||null,scheduled_time:b.scheduled_time||null,status:'open',created_by_role:String(actor.role),pay_revisit:pay,revisit_payment:amount,payment_note:String(b.payment_note||'')}).select().single();if(ins.error)throw ins.error;const st=await db.from('business_staff').select('external_id').eq('id',o.master_staff_id).maybeSingle();const now=new Date().toISOString();const up=await db.from('orders').update({status:'В работе',is_claim:true,claim_reason:reason,claim_opened_at:now,claim_closed_at:null,claim_parent_order_id:o.id,claim_visit_no:Number(o.claim_visit_no||0)+1,claim_revisit_payment:amount,scheduled_date:b.scheduled_date||o.scheduled_date,scheduled_time:b.scheduled_time||o.scheduled_time,completed_at:null,sync_status:'pending_sheet',updated_at:now}).eq('id',o.id).select().single();if(up.error)throw up.error;return json({ok:true,session_token:session_token||undefined,claim:{...ins.data,master_id:st.data?.external_id||o.master_staff_id},order:{...up.data,id:String(up.data.id),master_vk_id:st.data?.external_id||''}})}
if(action==='closeClaim'){const q=await db.from('orders').select('*').eq('id',b.id).single();if(q.error)throw q.error;if(!q.data.is_claim)return json({ok:false,error:'Заявка не является претензией'},409);if(actor.role==='master'&&String(q.data.master_staff_id||'')!==String(actor.id))return json({ok:false,error:'Это претензия другого мастера'},403);if(actor.role!=='master'&&!privileged(actor.role))return json({ok:false,error:'Недостаточно прав'},403);const now=new Date().toISOString();const up=await db.from('orders').update({status:'Выполнена',claim_closed_at:now,completed_at:now,sync_status:'pending_sheet',updated_at:now}).eq('id',b.id).select().single();if(up.error)throw up.error;await db.from('order_claims').update({status:'closed',closed_at:now}).eq('order_id',b.id).eq('status','open');return json({ok:true,session_token:session_token||undefined,order:{...up.data,id:String(up.data.id)}})}
return json({ok:false,error:'UNKNOWN_ACTION'},404)}catch(e){return json({ok:false,error:e instanceof Error?e.message:String(e)},500)}});
